namespace eID.RO.Contracts;

public enum LogEventCode
{
    None = 0,
    CREATE_EMPOWERMENT = 1,
    GET_EMPOWERMENTS_TO_ME_BY_FILTER = 2,
    GET_EMPOWERMENTS_FROM_ME_BY_FILTER = 3,
    WITHDRAW_EMPOWERMENT = 4,
    DISAGREE_EMPOWERMENT = 7,
    GET_EMPOWERMENTS_BY_DEAU = 8,
    SIGN_EMPOWERMENT = 9,
    GET_EMPOWERMENTS_BY_EIK = 13,
    DENY_EMPOWERMENT_BY_DEAU = 14,
    APPROVE_EMPOWERMENT_BY_DEAU = 15,
    GET_EMPOWERMENTS_BY_ADMINISTRATOR = 17,
    EXPORT_EMPOWERMENT = 18,
    CHANGE_EMPOWERMENT_STATUS = 19,
    GET_EMPOWERMENT_DOCUMENT_TO_ME = 20,
    GET_EMPOWERMENT_DOCUMENT_FROM_ME = 21,
    EMPOWERMENT_IS_COLLECTED_SIGNATURES = 22,
    EMPOWERMENT_IS_ACTIVATED = 23,
    EMPOWERMENT_IS_DENIED = 24,
    EMPOWERMENT_IS_DISAGREEMENT_DECLARED = 25,
    EMPOWERMENT_IS_WITHDRAWN = 26,
    EMPOWERMENT_IS_UNCONFIRMED = 27
}
