/*
 * ISCEI HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = IsceiSdk.Client.FileParameter;
using OpenAPIDateConverter = IsceiSdk.Client.OpenAPIDateConverter;

namespace IsceiSdk.Model
{
    /// <summary>
    /// X509CertAuthenticationRequestDto
    /// </summary>
    [DataContract(Name = "X509CertAuthenticationRequestDto")]
    public partial class X509CertAuthenticationRequestDto : IValidatableObject
    {
        /// <summary>
        /// Defines LevelOfAssurance
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum LevelOfAssuranceEnum
        {
            /// <summary>
            /// Enum LOW for value: LOW
            /// </summary>
            [EnumMember(Value = "LOW")]
            LOW = 1,

            /// <summary>
            /// Enum SUBSTANTIAL for value: SUBSTANTIAL
            /// </summary>
            [EnumMember(Value = "SUBSTANTIAL")]
            SUBSTANTIAL = 2,

            /// <summary>
            /// Enum HIGH for value: HIGH
            /// </summary>
            [EnumMember(Value = "HIGH")]
            HIGH = 3
        }


        /// <summary>
        /// Gets or Sets LevelOfAssurance
        /// </summary>
        [DataMember(Name = "levelOfAssurance", EmitDefaultValue = false)]
        public LevelOfAssuranceEnum? LevelOfAssurance { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="X509CertAuthenticationRequestDto" /> class.
        /// </summary>
        /// <param name="levelOfAssurance">levelOfAssurance.</param>
        /// <param name="requestFrom">requestFrom.</param>
        public X509CertAuthenticationRequestDto(LevelOfAssuranceEnum? levelOfAssurance = default, string requestFrom = default)
        {
            this.LevelOfAssurance = levelOfAssurance;
            this.RequestFrom = requestFrom;
        }

        /// <summary>
        /// Gets or Sets RequestFrom
        /// </summary>
        [DataMember(Name = "requestFrom", EmitDefaultValue = false)]
        public string RequestFrom { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class X509CertAuthenticationRequestDto {\n");
            sb.Append("  LevelOfAssurance: ").Append(LevelOfAssurance).Append("\n");
            sb.Append("  RequestFrom: ").Append(RequestFrom).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
