package bg.bulsi.mvr.common.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.experimental.FieldNameConstants;

@AllArgsConstructor
@RequiredArgsConstructor
@Getter
@FieldNameConstants(onlyExplicitlyIncluded = true)
public enum ErrorCode {
@FieldNameConstants.Include    CITIZEN_CERTIFICATE_NOT_FOUND_SN_AND_ISSUER("Citizen Certificate By SN And Issuer Not Found", "Citizen Certificate not found for SerialNumber: %s and Issuer: %s"),
@FieldNameConstants.Include    CITIZEN_CERTIFICATE_NOT_FOUND_ID("Citizen Certificate By ID Not Found", "Citizen Certificate not found for ID: "),
@FieldNameConstants.Include    CITIZEN_CERTIFICATE_NOT_FOUND_EIDENTITY_ID("Citizen Certificate Not Found By EidentityID", "Citizen Certificate not found for eidentityId: "),
@FieldNameConstants.Include    CITIZEN_CERTIFICATE_NOT_FOUND_BY_CERTIFICATE_AND_PROFILE_ID("Citizen Certificate Not Found By certificate and profileId", "Citizen Certificate Not Found By certificate and profileId:%s"),
@FieldNameConstants.Include    REGISTRY_ERROR("Registry Error", "An error occurred while accessing the registry."),
@FieldNameConstants.Include	EIDENTITY_CERTIFICATE_MISMATCHED("Eidentity Certificate Mismatched", "Provided Eidentity [%s] does not match the certificate.subject.uid [%s]"),
@FieldNameConstants.Include    EIDENTITY_NOT_FOUND_BY_ID("Eidentity Not Found", "Citizen Identifier not found for eidentityId: "),
@FieldNameConstants.Include    EIDENTITY_NOT_FOUND_BY_NUMBER("Eidentity Not Found", "Citizen Identifier not found by number."),
@FieldNameConstants.Include    EIDENTITY_NOT_ACTIVE("Eidentity Not Active", "Citizen Identifier is not active for eidentityId: "),
@FieldNameConstants.Include	CITIZEN_EMAIL_NOT_FOUND("Citizen Email Not Found", "Citizen not found for email: "),
@FieldNameConstants.Include	CITIZEN_PROFILE_NOT_FOUND("Citizen Profile Not Found", "Citizen Profile not found for eidentityId: %s"),
@FieldNameConstants.Include	CITIZEN_PROFILE_NOT_FOUND_BY_ID("Citizen Profile Not Found", "Citizen Profile not found for id: %s"),
@FieldNameConstants.Include    CITIZEN_ID_NOT_FOUND("Citizen ID Not Found", "Citizen not found for ID: "),
@FieldNameConstants.Include    PASSWORD_RESET_TOKEN_NOT_FOUND("Citizen Password Reset Token Not Found", "Citizen password reset token could not be found in the registry."),
@FieldNameConstants.Include    TOKEN_CANNOT_BE_NULL("Token cannot be null.", "Token cannot be null."),
@FieldNameConstants.Include    VERIFY_TOKEN_NOT_FOUND("Citizen Verify Token Not Found", "Citizen verify token could not be found in the registry."),
@FieldNameConstants.Include    APPLICATION_NOT_FOUND("Application not found", "Application with id:%s not found"),
@FieldNameConstants.Include    EID_ADMINISTRATOR_NOT_FOUND("Eid Administrator not found", "Eid Administrator with that name does not exist"),
@FieldNameConstants.Include    EID_CENTER_NOT_FOUND("Eid Center not found", "Eid Center does not exist"),
@FieldNameConstants.Include    NOMENCLATURES_NOT_FOUND("No Nomenclatures found","No Nomenclatures found"),
@FieldNameConstants.Include    REASON_NOT_FOUND("Reason not found","Reason with id:%s not found"),
@FieldNameConstants.Include    REASON_NOT_FOUND_BY_NAME("Reason not found","Reason with name:%s not found"),
@FieldNameConstants.Include    CERTIFICATE_HISTORY_NOT_FOUND("Certificate history not found","Certificate history with certificateId:%s not found"),
@FieldNameConstants.Include    CERTIFICATE_NOT_FOUND_IN_EJBCA("Certificate not found in EJBCA","Certificate in EJBCA with certificateId:%s not found"),
@FieldNameConstants.Include    EMPLOYEE_NOT_FOUND("Employee not found","Employee not found for Registered Enterprice with ID: %s"),
@FieldNameConstants.Include    EMPLOYEE_MUST_BE_ADMIN("At least one employee must be administrator","At least one employee must be administrator"),
@FieldNameConstants.Include    WRONG_APPLICATION_TYPE("Wrong Application Type","Wrong Application Type"),
@FieldNameConstants.Include    ACTIVE_APPLICATION_OF_THAT_TYPE_ALREADY_EXISTS("Active application of that type already exists","Active application of that type already exists"),
@FieldNameConstants.Include    EMPLOYEE_LIST_IS_EMPTY("There should be at least one employee","There should be at least one employee"),
@FieldNameConstants.Include    AUTHORIZED_PERSON_LIST_IS_EMPTY("There should be at least one authorized person","There should be at least one authorized person"),
@FieldNameConstants.Include    DEVICE_LIST_IS_EMPTY("There should be at least one device","There should be at least one device"),
@FieldNameConstants.Include    LINK_REQUIRED("Authorization link/Backchannel authorization link is mandatory","Authorization link/Backchannel authorization link is mandatory"),
@FieldNameConstants.Include    SECURITY_LEVEL_REQUIRED("Device security level is mandatory","Device security level is mandatory"),
@FieldNameConstants.Include    SECURITY_LEVEL_MUST_BE_INTEGER_NUMBER("Security Level must be integer number","Security Level must be integer number"),
@FieldNameConstants.Include    SECURITY_LEVEL_NOT_VALID("Security Level not valid","Security Level not valid"),
@FieldNameConstants.Include    FRONT_OFFICE_LIST_IS_EMPTY("There should be at least one front office","There should be at least one front office"),
@FieldNameConstants.Include    MUST_BE_EMPLOYEE_OF_THIS_EID_MANAGER("Must be employee of this eid manager","Must be employee of this eid manager"),
@FieldNameConstants.Include    MUST_BE_EMPLOYEE_OF_EID_MANAGER("Must be employee of eid manager","Must be employee of eid manager"),
@FieldNameConstants.Include    EIDENTITY_REQUIRED("EIdentity required","EIdentity required"),
@FieldNameConstants.Include    YOU_MUST_BE_THE_APPLICANT("You must be the applicant of that application","You must be the applicant of that application"),
@FieldNameConstants.Include    CODE_IS_REQUIRED("Code is required","Code is required"),
@FieldNameConstants.Include    NOTE_IS_REQUIRED("Note is required","Note is required"),
@FieldNameConstants.Include    WRONG_CERTIFICATE_STATUS("Certificate is revoked","Status of certificate is revoked and cannot be updated"),
@FieldNameConstants.Include    ADMINISTRATOR_FRONT_OFFICE_NOT_FOUND("Administrator Front Office not found", "Administrator Front Office with id:%s not found"),
@FieldNameConstants.Include    AUTHORIZED_PERSON_NOT_FOUND("Authorized Person not found", "Authorized Person with id:%s not found"),
@FieldNameConstants.Include    ADMINISTRATOR_FRONT_OFFICE_ID_CANNOT_BE_NULL("Administrator Front Office id cannot be null", "Administrator Front Office id cannot be null"),
@FieldNameConstants.Include    EID_ADMINISTRATOR_ID_CANNOT_BE_NULL("Administrator id cannot be null", "Administrator id cannot be null"),
@FieldNameConstants.Include    APPLICATION_IS_ALREADY_SIGNED("Application is already signed", "Application with id: %s is already signed"),
@FieldNameConstants.Include    SIGN_APPLICATION_REJECTED("Application signing rejected","The signing of the application is rejected"),
@FieldNameConstants.Include    CERTIFICATE_IS_ALREADY_GENERATED("Certificate is already generated", "Certificate for application with id: %s is already generated"),
@FieldNameConstants.Include    E_SIGNATURE_DOES_NOT_MATCH("E-Signature does not match application data", "E-signature details and application details don't match"),
@FieldNameConstants.Include    ENTITY_NOT_FOUND("%s Not Found", "%s with id:%s not found"),
@FieldNameConstants.Include    CITIZEN_PROFILE_EXISTS_BY_EMAIL("Email is already taken", "Profile with that email already exists"),
@FieldNameConstants.Include    CITIZEN_PROFILE_EXISTS_BY_PHONE_NUMBER("Phone number is already taken", "Profile with that phone number already exists"),
@FieldNameConstants.Include    EMAIL_TOKEN_NOT_FOUND("Email token not found", "Email token not found"),
@FieldNameConstants.Include    CITIZEN_IDENTIFIER_NOT_FOUND_BY_NUMBER("Citizen Identifier not found by number", "Citizen Identifier not found by number: %s"),
@FieldNameConstants.Include    VALIDATION_ERROR("Validation error", "Validation error", false),
@FieldNameConstants.Include    INTERNAL_SERVER_ERROR("Internal Server Error", "Internal Server Error", false),
@FieldNameConstants.Include    CITIZEN_IDENTIFIER_TYPE_CANNOT_BE_NULL("Citizen Identifier Type cannot be null", "Citizen Identifier Type cannot be null"),
@FieldNameConstants.Include    CITIZEN_IDENTIFIER_NUMBER_CANNOT_BE_NULL("Citizen Identifier Number cannot be null", "Citizen Identifier Number cannot be null"),
@FieldNameConstants.Include    CITIZEN_IDENTIFIER_NUMBER_NOT_VALID("Citizen Identifier Number is not valid", "Citizen Identifier Number is not valid"),
@FieldNameConstants.Include    CITIZEN_IDENTIFIER_NUMBER_LENGTH_NOT_VALID("Citizen Identifier Number length is not valid", "Citizen Identifier Number length is not valid"),
@FieldNameConstants.Include    CODE_IS_TOO_LONG("EidManager/Office code is too long", "EidManager/Office code is too long"),
@FieldNameConstants.Include    CITIZEN_IDENTIFIER_NOT_VALID("Citizen Identifier not valid", "Citizen Identifier not valid"),
@FieldNameConstants.Include    APPLICATION_SUBMISSION_TYPE_CANNOT_BE_NULL("Application submission type cannot be null", "Application submission type cannot be null"),
@FieldNameConstants.Include    APPLICATION_TYPE_CANNOT_BE_NULL("Application type cannot be null", "Application type cannot be null"),
@FieldNameConstants.Include    APPLICATION_STATUS_CANNOT_BE_NULL("Application status cannot be null", "Application status cannot be null"),
@FieldNameConstants.Include    STATUS_NOT_ALLOWED("Application status not allowed", "Application status not allowed"),
@FieldNameConstants.Include    REASON_ID_CANNOT_BE_NULL("Reason ID cannot be null", "Reason ID cannot be null"),
@FieldNameConstants.Include    PERSONAL_IDENTITY_DOCUMENT_CANNOT_BE_NULL("Personal Identity Document cannot be null", "Personal Identity Document cannot be null"),
@FieldNameConstants.Include    CERTIFICATE_ID_CANNOT_BE_NULL("Certificate ID cannot be null", "Certificate ID cannot be null"),
@FieldNameConstants.Include    REASON_CANNOT_BE_NULL("Reason cannot be null", "Reason cannot be null"),
@FieldNameConstants.Include    CITIZENSHIP_CANNOT_BE_NULL("Citizenship cannot be null", "Citizenship cannot be null"),
@FieldNameConstants.Include    GUARDIAN_FIRST_NAME_CANNOT_BE_BLANK("Guardian first name cannot be blank", "Guardian first name cannot be blank"),
@FieldNameConstants.Include    GUARDIAN_SECOND_OR_LAST_NAME_CANNOT_BE_BLANK("At least one of the Guardian Second or Last name must be provided", "At least one of the Guardian Second or Last name must be provided"),
@FieldNameConstants.Include    GUARDIAN_SECOND_NAME_CANNOT_BE_BLANK("Guardian second name cannot be blank", "Guardian second name cannot be blank"),
@FieldNameConstants.Include    GUARDIAN_LAST_NAME_CANNOT_BE_BLANK("Guardian last name cannot be blank", "Guardian last name cannot be blank"),
@FieldNameConstants.Include    GUARDIAN_CITIZEN_IDENTIFIER_NUMBER_CANNOT_BE_BLANK("Guardian citizen identifier number cannot be blank", "Guardian citizen identifier number cannot be blank"),
@FieldNameConstants.Include    GUARDIAN_CITIZEN_IDENTIFIER_TYPE_CANNOT_BE_NULL("Guardian citizen identifier type cannot be blank", "Guardian citizen identifier type cannot be blank"),
@FieldNameConstants.Include    GUARDIAN_IDENTITY_DOCUMENT_CANNOT_BE_NULL("Guardian identity document cannot be null", "Guardian identity document cannot be null"),
@FieldNameConstants.Include    GUARDIAN_IDENTITY_ISSUE_DATE_CANNOT_BE_NULL("Guardian personal identity document issue date cannot be null", "Guardian personal identity document issue date cannot be null"),
@FieldNameConstants.Include    GUARDIAN_IDENTITY_VALIDITY_DATE_CANNOT_BE_NULL("Guardian personal identity document validity date cannot be null", "Guardian personal identity document validity date cannot be null"),
@FieldNameConstants.Include    GUARDIAN_IDENTITY_TYPE_CANNOT_BE_BLANK("Guardian personal identity document identity type cannot be blank", "Guardian personal identity document identity type cannot be blank"),
@FieldNameConstants.Include    GUARDIAN_IDENTITY_NUMBER_CANNOT_BE_BLANK("Guardian personal identity document identity number cannot be blank", "Guardian personal identity document identity number cannot be blank"),
@FieldNameConstants.Include    IDENTITY_ISSUE_DATE_CANNOT_BE_NULL("Personal identity document issue date cannot be null", "Personal identity document issue date cannot be null"),
@FieldNameConstants.Include    IDENTITY_VALIDITY_DATE_CANNOT_BE_NULL("Personal identity document validity date cannot be null", "Personal identity document validity date cannot be null"),
@FieldNameConstants.Include    BIRTH_DATE_CANNOT_BE_NULL("Birth date cannot be null", "Birth date cannot be null"),
@FieldNameConstants.Include    EMAIL_NOT_VALID("Email is not valid", "Email is not valid"),
@FieldNameConstants.Include    PHONE_NUMBER_NOT_VALID("Phone number is not valid", "Phone number is not valid"),
@FieldNameConstants.Include    GUARDIAN_DETAILS_CANNOT_BE_NULL("Guardian details are required", "Guardian details are required"),
@FieldNameConstants.Include    ENDPOINT_IS_FOR_CHANGE_STATUS_APPLICATIONS("Only change status applications allowed","Endpoint can only be used for applications, which change the status of a certificate"),
@FieldNameConstants.Include    ENDPOINT_IS_FOR_RESUME_AND_REVOKE_APPLICATIONS("Only Resume and Revoke applications allowed","Endpoint can only be used for applications, which Resume or Revoke certificate"),
@FieldNameConstants.Include    ONLINE_OFFICE_REQUIRES_EID_SUBMISSION("Online office requires EID submission","Online office requires EID submitted application"),
@FieldNameConstants.Include    ONLINE_OFFICE_REQUIRES_MOBILE("Online office requires Mobile certificate","Online office can only be used for mobile certificates"),
@FieldNameConstants.Include    APPLICATION_WITH_THAT_ID_ALREADY_EXISTS("Application already exists","Application with that id already exists"),
@FieldNameConstants.Include    ENDPOINT_IS_ONLY_FOR_ISSUE_EID("Endpoint is only for Issue EID","Endpoint can only be used for issuing certificates"),
@FieldNameConstants.Include    APPLICATION_TYPE_WITH_PROVIDED_LOA_REQUIRES_XML_SIGNING("Application type with provided LOA requires XML signing","Application type with provided LOA requires XML signing"),
@FieldNameConstants.Include    APPLICATION_CANNOT_BE_DENIED("Application cannot be denied","Status:%s is final and application with id:%s cannot be denied"),
@FieldNameConstants.Include    STATUS_NOT_EXPECTED("Status not expected","Status:%s is not expected for application with id:%s"),
@FieldNameConstants.Include    APPLICATION_CANNOT_BE_CONFIRMED("Application cannot be confirmed","Application is not eligible to confirmation"),
@FieldNameConstants.Include    ONLY_ONE_ACTIVE_APPLICATION_ALLOWED("You can only have one active application at a time.","You can only have one active application at a time."),
@FieldNameConstants.Include    CANNOT_CONFIRM_STORAGE("Cannot confirm storage","Cannot confirm storage for certificate"),
@FieldNameConstants.Include    OPERATION_NOT_SUPPORTED("Operation not supported","Operation not supported for application with id:%s"),
@FieldNameConstants.Include    MORE_THAN_ONE_VALID_PIPELINES_EXIST("More than one valid pipelines exist","More than one valid pipelines are found (%s) that can process application with id: %s"),
@FieldNameConstants.Include    NO_VALID_PIPELINES_EXIST("No valid pipelines exist","No valid pipelines are found that can process the application"),
@FieldNameConstants.Include    REASON_TEXT_CANNOT_BE_BLANK("Reason text cannot be blank","Reason text cannot be blank"),
@FieldNameConstants.Include    REASON_NOT_SUPPORTED("Reason ID not supported","The given application does not support the selected reasonId"),
@FieldNameConstants.Include    REASON_NOT_ALLOWED("Reason ID not allowed in the current module/context","Reason ID not allowed in the current module/context"),
@FieldNameConstants.Include    REASON_TEXT_REQUIRES_DIFFERENT_REASON("Reason text requires different reasonType","Reason text cannot be used with this reasonType"),
@FieldNameConstants.Include    DEVICE_NOT_RECOGNIZED("Device type not recognized","Device type not recognized"),
@FieldNameConstants.Include    DEVICE_ID_CANNOT_BE_NULL("Device ID cannot be null","Device ID cannot be null"),
@FieldNameConstants.Include    MISSING_USER_IDS("User IDs are missing","userid and citizenProfileId cannot be null"),
@FieldNameConstants.Include    MULTIPLE_CARRIERS_FOUND_FOR_SN("Multiple carriers found for SN","More than one carrier found for this serial number"),
@FieldNameConstants.Include    NO_CARRIERS_FOUND_FOR_SN("No carriers found for SN","No carrier found for this serial number"),
@FieldNameConstants.Include    PERSONAL_DETAILS_ARE_INCORRECT("Personal Details are incorrect","Personal Details are incorrect"),
@FieldNameConstants.Include    APPLICATION_ID_CANNOT_BE_NULL("Application ID cannot be null","Application ID cannot be null"),
@FieldNameConstants.Include    NAIF_APPLICATION_NR_CANNOT_BE_NULL("NAIF Application Number refference cannot be null","Application Nr. cannot be null"),
@FieldNameConstants.Include    ISSUER_CANNOT_BE_BLANK("Issuer cannot be blank","Issuer cannot be blank"),
@FieldNameConstants.Include    CANNOT_GENERATE_QR_CODE("Cannot generate QR Code","Cannot generate QR Code"),
@FieldNameConstants.Include    OTP_CODE_DOES_NOT_EXIST("OTP Code does not exist","OTP Code does not exist"),
@FieldNameConstants.Include    OTP_SECRET_CANNOT_BE_NULL("OTP secret cannot be null","OTP secret cannot be null"),
@FieldNameConstants.Include    OTP_ISSUER_CANNOT_BE_NULL("OTP issuer cannot be null","OTP issuer cannot be null"),
@FieldNameConstants.Include    OTP_CODE_IS_NOT_VALID("OTP Code is not valid","OTP Code is not valid"),
@FieldNameConstants.Include    COULD_NOT_VERIFY_CITIZEN_DATA("Could not verify citizen data","Could not verify citizen data. IdentifierType not supported"),
@FieldNameConstants.Include    REGIX_EXCEPTION("Regix could not verify request","Regix could not verify request"),
@FieldNameConstants.Include    SIGNS_DESK_AND_BASE_PROFILE_APPLICATIONS("Application cannot be signed","Only base profile and desk applications can be signed with this URL"),
@FieldNameConstants.Include    CONFIRM_IS_NOT_FOR_ONLINE_OFFICE("Confirm is not for online office","This confirm is not for online office"),
@FieldNameConstants.Include    CONFIRMS_ONLY_ONLINE_OFFICE("Confirm is only for online office","This confirm is only for online office"),
@FieldNameConstants.Include    SIGN_IS_NOT_FOR_ONLINE_OFFICE("Sign is not for online office","This sign is not for online office"),
@FieldNameConstants.Include    SIGNS_MOBILE_APPLICATIONS("Signs only mobile certificates","Sign can be used only for mobile certificates"),
@FieldNameConstants.Include    ENROLLS_DESK_APPLICATIONS("Enrolls only desk applications","This enroll can only be used for Desk created applications"),
@FieldNameConstants.Include    ENROLLS_CHIP_CARD_CERTIFICATES("Enrolls only chip card certificates","Enroll can be used only for chip card applications"),
@FieldNameConstants.Include    ENROLLS_NON_CHIP_CARD_CERTIFICATES("Enrolls only non chip card certificates","Enroll can be used only for non chip card applications"),
@FieldNameConstants.Include    ENROLLS_DESK_AND_BASE_PROFILE_APPLICATIONS("Enrolls only desk and base profile applications","This enroll can only be used for Desk and Base Profile created applications"),
@FieldNameConstants.Include    ENROLLS_MOBILE_CERTIFICATES("Enrolls mobile certificates","Enroll can be used only for mobile certificate"),
@FieldNameConstants.Include    ENROLLS_EID_APPLICATIONS("Enrolls eid applications","This enroll can only be used for EID created applications"),
@FieldNameConstants.Include    ENROLLS_ONLY_ONLINE_OFFICE("Enrolls only applications with online office","Enrolls only applications with online office"),
@FieldNameConstants.Include    CERTICATE_CA_NAME_CANNOT_BE_BLANK("Certificate CA name cannot be blank", "Certificate CA name cannot be blank"),
@FieldNameConstants.Include    CERTICATE_SIGNING_REQUEST_CANNOT_BE_BLANK("Certificate signing request cannot be blank", "Certificate signing request cannot be blank"),
@FieldNameConstants.Include    CERTICATE_SIGNING_REQUEST_DATA_NOT_VALID("Certificate signing request %s is not valid", "Certificate signing request %s is not valid"),
@FieldNameConstants.Include    SIGNS_CHIP_CARD_APPLICATIONS("Sign is for identity card applications","Sign can be used only for identity card applications"),
@FieldNameConstants.Include    CITIZEN_PROFILE_ID_CANNOT_BE_NULL("Citizen Profile Id cannot be null","citizenProfileId cannot be null"),
@FieldNameConstants.Include    CONFIRMS_MOBILE_STORAGE("Confirms only mobile applications","Only mobile applications can be confirmed with this URL"),
@FieldNameConstants.Include    CONFIRMS_DESK_AND_BASE_PROFILE_APPLICATIONS("Confirms only base profile and desk applications","Only base profile and desk applications can be confirmed with this URL"),
@FieldNameConstants.Include    CONFIRMS_EID_APPLICATIONS("Confirms only eid applications","Only eid applications can be confirmed with this URL"),
@FieldNameConstants.Include    USER_ID_CANNOT_BE_NULL("User ID cannot be null","userId cannot be null"),
@FieldNameConstants.Include    APPLICATION_NOT_IN_REQUIRED_PIPELINE_STATUS("Application is in wrong status","Application is not in the required pipeline status"),
@FieldNameConstants.Include    ONLY_MOBILE_APPLICATION_SETS_GUARDIANS("Cannot set guardians","Only mobile application can require manually set guardians"),
@FieldNameConstants.Include    APPLICATION_DOES_NOT_REQUIRE_GUARDIANS("Cannot set guardians","Application does not require guardians"),
@FieldNameConstants.Include    PUN_CARRIER_CANNOT_BE_NULL("PunCarrier cannot be null","PunCarrier cannot be null"),
@FieldNameConstants.Include    START_DATE_CANNOT_BE_NULL("Start date cannot be null","Start date cannot be null"),
@FieldNameConstants.Include    END_DATE_CANNOT_BE_NULL("End date cannot be null","End date cannot be null"),
@FieldNameConstants.Include    OPERATORS_CANNOT_BE_NULL("Operators cannot be null","Operators cannot be null"),
@FieldNameConstants.Include    EIDENTITY_CANNOT_BE_CREATED("There was a problem with EIdentity creation","There was a problem with EIdentity creation"),
@FieldNameConstants.Include    EIDENTITY_NOT_FOUND("There was a problem with Get EIdentity","There was a problem with Get EIdentity"),
@FieldNameConstants.Include    FIRST_NAME_IS_DIFFERENT_FROM_EXISTING_ONE("The provided FIRST_NAME does not correspond to the existing one","The provided FIRST_NAME does not correspond to the existing one"),
@FieldNameConstants.Include    SECOND_NAME_IS_DIFFERENT_FROM_EXISTING_ONE("The provided SECOND_NAME does not correspond to the existing one","The provided SECOND_NAME does not correspond to the existing one"),
@FieldNameConstants.Include    LAST_NAME_IS_DIFFERENT_FROM_EXISTING_ONE("The provided LAST_NAME does not correspond to the existing one","The provided LAST_NAME does not correspond to the existing one"),
@FieldNameConstants.Include    CITIZEN_IDENTIFIER_NUMBER_IS_DIFFERENT_FROM_EXISTING_ONE("The provided CITIZEN_IDENTIFIER_NUMBER does not correspond to the existing one","The provided CITIZEN_IDENTIFIER_NUMBER does not correspond to the existing one"),
@FieldNameConstants.Include    CITIZEN_IDENTIFIER_TYPE_IS_DIFFERENT_FROM_EXISTING_ONE("The provided CITIZEN_IDENTIFIER_TYPE does not correspond to the existing one","The provided CITIZEN_IDENTIFIER_TYPE does not correspond to the existing one"),
@FieldNameConstants.Include    PHONE_NUMBER_IS_DIFFERENT_FROM_EXISTING_ONE("The provided PHONE_NUMBER does not correspond to the existing one","The provided PHONE_NUMBER does not correspond to the existing one"),
@FieldNameConstants.Include    EMAIL_IS_DIFFERENT_FROM_EXISTING_ONE("The provided EMAIL does not correspond to the existing one","The provided EMAIL does not correspond to the existing one"),
@FieldNameConstants.Include    REQUESTER_IS_NOT_OWNER("Requester doesn't match with certificate's owner","Requester doesn't match with certificate's owner"),
@FieldNameConstants.Include    PROFILE_MUST_BE_VERIFIED("Profile must be first verified","Profile must be first verified"),
@FieldNameConstants.Include    CITIZEN_PROFILE_CANNOT_BE_ATTACHED("Citizen Profile cannot be attached to EIdentity","Citizen Profile cannot be attached to EIdentity"),
@FieldNameConstants.Include    NO_CERTIFICATES_FOUND_FOR_EIDENTITY_ID("No certificates found for eidentity ID","No certificates found for user with eidentityId:%s"),
@FieldNameConstants.Include    IDENTITY_ISSUE_DATE_IS_DIFFERENT_FROM_EXISTING_ONE("The provided PERSONAL_ID_DOCUMENT.IDENTITY_ISSUE_DATE does not correspond to the existing one","The provided PERSONAL_ID_DOCUMENT.IDENTITY_ISSUE_DATE does not correspond to the existing one"),
@FieldNameConstants.Include    IDENTITY_VALIDITY_TO_DATE_IS_DIFFERENT_FROM_EXISTING_ONE("The provided PERSONAL_ID_DOCUMENT.IDENTITY_VALIDITY_TO_DATE does not correspond to the existing one","The provided PERSONAL_ID_DOCUMENT.IDENTITY_VALIDITY_TO_DATE does not correspond to the existing one"),
@FieldNameConstants.Include    IDENTITY_NUMBER_IS_DIFFERENT_FROM_EXISTING_ONE("The provided PERSONAL_ID_DOCUMENT.IDENTITY_NUMBER does not correspond to the existing one","The provided PERSONAL_ID_DOCUMENT.IDENTITY_NUMBER does not correspond to the existing one"),
@FieldNameConstants.Include    IDENTITY_TYPE_IS_DIFFERENT_FROM_EXISTING_ONE("The provided PERSONAL_ID_DOCUMENT.IDENTITY_TYPE does not correspond to the existing one","The provided PERSONAL_ID_DOCUMENT.IDENTITY_TYPE does not correspond to the existing one"),
@FieldNameConstants.Include    FIRST_NAME_LATIN_IS_DIFFERENT_FROM_EXISTING_ONE("The provided FIRST_NAME_LATIN does not correspond to the existing one","The provided FIRST_NAME_LATIN does not correspond to the existing one"),
@FieldNameConstants.Include    SECOND_NAME_LATIN_IS_DIFFERENT_FROM_EXISTING_ONE("The provided SECOND_NAME_LATIN does not correspond to the existing one","The provided SECOND_NAME_LATIN does not correspond to the existing one"),
@FieldNameConstants.Include    LAST_NAME_LATIN_IS_DIFFERENT_FROM_EXISTING_ONE("The provided LAST_NAME_LATIN does not correspond to the existing one","The provided LAST_NAME_LATIN does not correspond to the existing one"),
@FieldNameConstants.Include    NATIONALITY_IS_DIFFERENT_FROM_EXISTING_ONE("The provided CITIZENSHIP/NATIONALITY does not correspond to the existing one","The provided CITIZENSHIP/NATIONALITY does not correspond to the existing one"),
@FieldNameConstants.Include    APPLICATION_TYPE_REQUIRES_DESK_FOR_FOREIGNER("Application type requires Desk submission for foreigner","Application type requires Desk submission for foreigner"),
@FieldNameConstants.Include    CERTIFICATE_CANNOT_BE_STOPPED("Certificate cannot be stopped","Certificate with id: %s is %s and cannot be stopped"),
@FieldNameConstants.Include    CERTIFICATE_CANNOT_BE_REVOKED("Certificate cannot be revoked","Certificate with id: %s is %s and cannot be revoked"),
@FieldNameConstants.Include    CERTIFICATE_CANNOT_BE_RESUMED("Certificate cannot be resumed","Certificate with id: %s is %s and cannot be resumed"),
@FieldNameConstants.Include    DEVICE_TYPE_NOT_RECOGNIZED("Device Type not recognized","Device Type not recognized"),
@FieldNameConstants.Include    CERTIFICATE_IS_EXPIRED_OR_INVALID("Certificate is expired or invalid","Certificate is expired or invalid"),
@FieldNameConstants.Include    CITIZEN_IS_DEAD("The citizen is dead","The citizen is dead"),
@FieldNameConstants.Include    CITIZEN_IS_PROHIBITED("Citizen is prohibited from creating online applications","Citizen is prohibited from creating online applications"),
@FieldNameConstants.Include    PASSWORDS_DONT_MATCH("Passwords don't match","Passwords don't match"),
@FieldNameConstants.Include    NEW_AND_OLD_PASSWORD_MATCH("The new and old password are the same","The new and old password are the same"),
@FieldNameConstants.Include    ONLY_DESK_APPLICATIONS_CAN_BE_REVOKED("Only desk applications support the Revoke operation","Only desk applications support the Revoke operation"),
@FieldNameConstants.Include    USER_ID_OR_CITIZEN_PROFILE_ID_MUST_BE_PROVIDED("Either userId or citizenProfileId must be provided","Either userId or citizenProfileId must be provided"),
@FieldNameConstants.Include    EIDENTITY_ID_CANNOT_BE_NULL("EidentityId cannot be null","EidentityId cannot be null"),
@FieldNameConstants.Include    PROFILE_WITH_THAT_EIDENTITY_ID_EXISTS("Profile with that eidentityId already exist","Profile with that eidentityId already exist"),
@FieldNameConstants.Include    PASSWORD_IS_INCORRECT("Password is incorrect","Password is incorrect"),
@FieldNameConstants.Include    MOBILE_APPLICATION_INSTANCE_ID_NOT_VALID("MobileApplicationInstanceId is not valid","MobileApplicationInstanceId is not valid"),
@FieldNameConstants.Include    MOBILE_APPLICATION_INSTANCE_CANNOT_BE_EMPTY("MobileApplicationInstanceId cannot be empty","MobileApplicationInstanceId cannot be empty"),
@FieldNameConstants.Include    MOBILE_ASSOCIATED_TO_DIFFERENT_PROFILE("Mobile device with instanceId:%s is associated to a different profile","Mobile device with instanceId:%s is associated to a different profile"),
@FieldNameConstants.Include    ADMINISTRATOR_FRONT_OFFICE_NAME_REQUIRED("Administrator Front Office Name is required","Administrator Front Office Name is required"),
@FieldNameConstants.Include    ADMINISTRATOR_FRONT_OFFICE_LOCATION_REQUIRED("Administrator Front Office Location is required","Administrator Front Office Location is required"),
@FieldNameConstants.Include    ADMINISTRATOR_FRONT_OFFICE_CONTACT_REQUIRED("Administrator Front Office Contact is required","Administrator Front Office Contact is required"),
@FieldNameConstants.Include    ADMINISTRATOR_FRONT_OFFICE_EID_ADMINISTRATOR_ID_REQUIRED("Administrator Front Office Eid Administrator ID is required","Administrator Front Office Eid Administrator ID is required"),
@FieldNameConstants.Include    ADMINISTRATOR_FRONT_OFFICE_ACTIVE_STATUS_REQUIRED("Administrator Front Office Active Status is required","Administrator Front Office Active Status is required"),
@FieldNameConstants.Include    IS_ACTIVE_CANNOT_BE_NULL("isActive cannot be null","isActive cannot be null"),
@FieldNameConstants.Include    COORDINATES_MUST_BE_WITHIN_BULGARIA("Coordinates must be within Bulgaria","Coordinates must be within Bulgaria"),
@FieldNameConstants.Include    COORDINATES_MUST_BE_DECIMAL_NUMBER("Coordinates must be decimal number","Coordinates must be decimal number"),
@FieldNameConstants.Include    EID_ADMINISTRATOR_NAME_REQUIRED("Eid Administrator Name is required","Eid Administrator Name is required"),
@FieldNameConstants.Include    EID_ADMINISTRATOR_NAME_LATIN_REQUIRED("Eid Administrator Name Latin is required","Eid Administrator Name Latin is required"),
@FieldNameConstants.Include    EID_ADMINISTRATOR_ACTIVE_STATUS_REQUIRED("Eid Administrator Active Status is required","Eid Administrator Active Status is required"),
@FieldNameConstants.Include    EID_ADMINISTRATOR_EIK_NUMBER_REQUIRED("Eid Administrator EikNumber is required","Eid Administrator EikNumber is required"),
@FieldNameConstants.Include    EID_MANAGER_ALREADY_EXISTS("Eid Manager already exists","Eid Manager already exists"),
@FieldNameConstants.Include    EID_MANAGER_WITH_THIS_CODE_ALREADY_EXISTS("Eid Manager with this code already exists","Eid Manager with this code already exists"),
@FieldNameConstants.Include    WRONG_CURRENT_EID_MANAGER_STATUS("The current status of Eid Manager is wrong","The current status of Eid Manager is wrong"),
@FieldNameConstants.Include    REGISTER_APPLICATION_FOR_EID_MANAGER_WITH_THIS_CODE_ALREADY_EXISTS("Register Application for Eid Manager with this code already exists","Register Application for Eid Manager with this code already exists"),
@FieldNameConstants.Include    EID_MANAGER_FRONT_OFFICE_WITH_THIS_CODE_ALREADY_EXISTS("Eid Manager Front Office with this code already exists","Eid Manager Front Office with this code already exists"),
@FieldNameConstants.Include    EID_CENTER_NAME_REQUIRED("Eid Center Name is required","Eid Center Name is required"),
@FieldNameConstants.Include    DOWNLOAD_URL_REQUIRED("Download URL is required","Download URL is required"),
@FieldNameConstants.Include    EID_CENTER_NAME_LATIN_REQUIRED("Eid Center Name Latin is required","Eid Center Name Latin is required"),
@FieldNameConstants.Include    EID_CENTER_ACTIVE_STATUS_REQUIRED("Eid Center Active Status is required","Eid Center Active Status is required"),
@FieldNameConstants.Include    EID_MANAGER_PENDING_FOR_ATTACHMENTS_STATUS_REQUIRED("Eid Manager Pending For Attachments Status is required","Eid Manager Pending For Attachments Status is required"),
@FieldNameConstants.Include    APPLICATION_RETURNED_FOR_CORRECTION_STATUS_REQUIRED("Application Returned For Correction Status is required","Application Returned For Correction Status is required"),
@FieldNameConstants.Include    EID_MANAGER_IN_REVIEW_STATUS_REQUIRED("Eid Manager In Review Status is required","Eid Manager In Review Status is required"),
@FieldNameConstants.Include    EID_MANAGER_IN_REVIEW_OR_TECHNICAL_CHECK_STATUS_REQUIRED("Eid Manager In Review or Technical Check Status is required","Eid Manager In Review or Technical Check Status is required"),
@FieldNameConstants.Include    EID_CENTER_EIK_NUMBER_REQUIRED("Eid Center EikNumber is required","Eid Center EikNumber is required"),
@FieldNameConstants.Include    FILE_ATTACHMENT_REQUIRED("File Attachment is required","File Attachment is required"),
@FieldNameConstants.Include    SECURITY_CLIENT_REQUIRED("Security Client is required","Security Client is required"),
@FieldNameConstants.Include    CLIENT_ID_MUST_BE_UNIQUE("ClientId must be unique","ClientId must be unique"),
@FieldNameConstants.Include	   PROVIDED_SERVICE_NOT_FOUND_BY_ID("Provided Service Not Found", "Provided Service Not Found for id: %s"),
@FieldNameConstants.Include	   PROVIDED_SERVICE_NOT_FOUND_BY_APPLICATION_TYPE("Provided Service Not Found", "Provided Service Not Found for type: %s"),
@FieldNameConstants.Include    INVALID_APPLICATION_NUMBER_PREFIX_TYPE("Invalid application number prefix type","Invalid application number prefix type"),
@FieldNameConstants.Include    ADMINISTRATOR_FRONT_OFFICE_NOT_FOUND_BY_NAME("Administrator Front Office not found", "Administrator Front Office with name:%s not found"),
@FieldNameConstants.Include    DEVICE_NOT_FOUND_BY_TYPE("Device Not Found", "Device with type:%s not found"),
@FieldNameConstants.Include    DEVICE_NOT_SUPPORTED_BY_EID_ADMINISTRATOR("Device not supported by Eid Administrator", "Device not supported by Eid Administrator"),
@FieldNameConstants.Include    INVALID_REPORT_FORMAT_TYPE("Invalid format", "Report with format:%s is not supported"),
@FieldNameConstants.Include    FIRST_NAME_CANNOT_BE_BLANK("First name cannot be blank", "First Name cannot be blank"),
@FieldNameConstants.Include    NAME_CANNOT_BE_BLANK("Name cannot be blank", "Name cannot be blank"),
@FieldNameConstants.Include    FIRST_NAME_LATIN_CANNOT_BE_BLANK("First name latin cannot be blank", "First Name latin cannot be blank"),
@FieldNameConstants.Include    NAME_LATIN_CANNOT_BE_BLANK("Name latin cannot be blank", "Name latin cannot be blank"),
//    LAST_NAME_CANNOT_BE_BLANK("First name cannot be blank", "First Name cannot be blank"),
//    FIRST_NAME_CANNOT_EXCEED_LENGTH("First name too long", "First Name cannot exceed 40 characters"),
//    SECOND_NAME_CANNOT_EXCEED_LENGTH("Second name too long", "Second Name cannot exceed 40 characters"),
//    LAST_NAME_CANNOT_EXCEED_LENGTH("Last name too long", "Last Name cannot exceed 60 characters"),
@FieldNameConstants.Include    FIRST_NAME_NOT_VALID("First name is not valid", "First Name is not valid"),
@FieldNameConstants.Include    SECOND_NAME_NOT_VALID("Second name is not valid", "Second Name is not valid"),
@FieldNameConstants.Include    LAST_NAME_NOT_VALID("Last name is not valid", "Last Name is not valid"),
@FieldNameConstants.Include    NAME_NOT_VALID("Name is not valid", "Name is not valid"),
//@FieldNameConstants.Include    FIRST_NAME_LENGTH_NOT_VALID("First name length is not valid", "First Name length is not valid"),
//@FieldNameConstants.Include    SECOND_NAME_LENGTH_NOT_VALID("Second name length is not valid", "Second Name length is not valid"),
//@FieldNameConstants.Include    LAST_NAME_LENGTH_NOT_VALID("Last name length is not valid", "Last Name length is not valid"),
@FieldNameConstants.Include    FIRST_NAME_LATIN_NOT_VALID("First name latin is not valid", "First name latin is not valid"),
@FieldNameConstants.Include    SECOND_NAME_LATIN_NOT_VALID("Second name latin is not valid", "Second name latin is not valid"),
@FieldNameConstants.Include    LAST_NAME_LATIN_NOT_VALID("Last name latin is not valid", "Last name latin is not valid"),
@FieldNameConstants.Include    NAME_LATIN_NOT_VALID("Name latin is not valid", "Name latin is not valid"),
@FieldNameConstants.Include    SECOND_OR_LAST_NAME_REQUIRED("At least one of Second or Last name must be provided", "At least one of Second or Last name must be provided"),
@FieldNameConstants.Include    EMAIL_CANNOT_BE_BLANK("Email cannot be blank", "Email cannot be blank"),
@FieldNameConstants.Include    SECOND_OR_LAST_NAME_LATIN_REQUIRED("At least one of Second or Last latin name must be provided", "At least one of Second or Last latin name must be provided"),
@FieldNameConstants.Include    PASSWORD_CANNOT_BE_BLANK("Password cannot be blank", "Password cannot be blank"),
@FieldNameConstants.Include    CONFIRM_PASSWORD_CANNOT_BE_BLANK("Confirm password cannot be blank", "Confirm password cannot be blank"),
@FieldNameConstants.Include    PASSWORD_NOT_VALID("Password is not valid", "Password is not valid"),
@FieldNameConstants.Include    CONFIRM_PASSWORD_NOT_VALID("Confirm password is not valid", "Confirm password is not valid"),
@FieldNameConstants.Include    EXPIRING_CERTIFICATES_CACHE_IS_EMPTY("Expiring certificates cache is empty", "Expiring certificates cache is empty"),
@FieldNameConstants.Include	   REGION_CANNOT_BE_NULL("Region cannot be null", "Region cannot be null"),
@FieldNameConstants.Include	   INVALID_TARIFF_TYPE("Invalid tariff type", "Invalid tariff type"),
@FieldNameConstants.Include	   TARIFF_ALREADY_EXISTS_FOR_THE_DATE("Tariff already exists for the date", "Tariff already exists for the date"),
@FieldNameConstants.Include	   DISCOUNT_ALREADY_EXISTS_FOR_THE_DATE("Discount already exists for the date", "Discount already exists for the date"),
@FieldNameConstants.Include	   PUK_CANNOT_BE_OBTAINED("Puk cannot be obtained", "Puk cannot be obtained. Message:\n%s"),
@FieldNameConstants.Include	   WRONG_NUMBER_OF_CLIENTS_FOR_EIK("Wrong number of clients found for EIK number", "Wrong number of clients found for EIK number"),
@FieldNameConstants.Include	   MISEP_PAYMENT_CREATION_FAILED("MISEP Payment creation failed", "MISEP Payment creation failed"),
@FieldNameConstants.Include	   HELP_PAGE_NOT_FOUND_BY_ID("Help page not found by id", "Help page not found by id:%s"),
@FieldNameConstants.Include	   STATUS_NOT_SUPPORTED("Certificate status not supported", "Certificate status not supported"),
@FieldNameConstants.Include	   CITIZEN_IDENTIFIER_IS_THE_SAME("Citizen identifier is the same", "Citizen identifier is the same"),
@FieldNameConstants.Include	   HELP_PAGE_EXISTS_BY_PAGE_NAME("Help page exists by pageName", "Help page exists by pageName"),
@FieldNameConstants.Include	   HELP_PAGE_NOT_FOUND_BY_PAGE_NAME("Help page not found by pageName", "Help page not found by pageName:%s"),
@FieldNameConstants.Include	   HELP_PAGE_PAGE_NAME_CANNOT_BE_NULL("Help page name cannot be null", "Help page name cannot be null"),
@FieldNameConstants.Include	   CERTIFICATES_ALIAS_NOT_VALID("Alias is not valid", "Alias is not valid"),
@FieldNameConstants.Include	   CERTIFICATES_INFO_KEYWORD_CANNOT_BE_NULL("Find certificates info keyword cannot be null", "Find certificates info keyword cannot be null"),
@FieldNameConstants.Include	   EXPORT_CONFIRMATION_IS_NOT_POSSIBLE("Export confirmation is not possible", "Export confirmation is not possible"),
@FieldNameConstants.Include	   EXISTING_DEACTIVATED_EID("Existing deactivated eID", "An eID already exists created for that citizen and it need to be activated first"),
@FieldNameConstants.Include	   APPLICATION_NOT_PAID("Application not paid", "You need to pay the application first"),
@FieldNameConstants.Include	   CERTIFICATE_CANNOT_BE_BLANK("Certificate cannot be blank", "Certificate cannot be left blank"),
@FieldNameConstants.Include	   CERTIFICATE_SERIAL_NUMBER_CANNOT_BE_BLANK("Certificate serial number cannot be blank", "Certificate serial number cannot be blank"),
@FieldNameConstants.Include	   EID_ADMINISTRATOR_CANNOT_BE_MVR("Eid Administrator cannot be MVR", "Eid Administrator cannot be MVR"),

@FieldNameConstants.Include   AUTHENTICATION_REQUEST_NOT_FOUND("The authentication request with the given ID is missing or expired","The authentication request with the given ID is missing or expired"),
@FieldNameConstants.Include   SIGNATURE_DOES_NOT_MATCH("Signature does not match the initial data", "Signature does not match the initial data"),
@FieldNameConstants.Include   CERTIFICATE_IS_NOT_VALID("The provided x509 Certificate is not valid","The provided x509 Certificate is not valid"),
@FieldNameConstants.Include   CERTIFICATE_IS_NOT_ACTIVE("The X509 Certificate is not ACTIVE","The X509 Certificate is not ACTIVE"),
@FieldNameConstants.Include   INVALID_SCOPE_PARAM("The provided scope param is not valid","The provided scope param is not valid"),
@FieldNameConstants.Include   CERTIFICATES_DO_NOT_MATCH("The provided Certificate do not match with the one in the Registry", "The provided Certificate do not match with the one in the Registry"),
@FieldNameConstants.Include   CERTIFICATE_CHAIN_GENERAL_FAILURE("The provided Certificate Chain could not be verified", "The provided Certificate Chain could not be verified"),
@FieldNameConstants.Include   BASE_PROFILE_AUTHENTICATION_REQUIRED("The citizen must first authenticate using Base Profile", "The citizen must first authenticate using Base Profile"),
@FieldNameConstants.Include   EID_AUTHENTICATION_REQUIRED("The citizen must first authenticate using EID", "The citizen must first authenticate using EID"),
@FieldNameConstants.Include   BASE_PROFILE_NOT_ACTIVE("Base profile Not Active", "Base profile Not Active"),
@FieldNameConstants.Include   OTP_CODE_MAX_ATTEMPTS_REACHED("You have exceeded the maximum number of OTP code attempts","You have exceeded the maximum number of OTP code attempts"),
@FieldNameConstants.Include   SESSION_IS_NOT_VALID("The provided session is not valid or does not exist","The provided session is not valid or does not exist")
;

	public final String title;
    private final String detail;
    private boolean isInResponse = true;
}
