//
//  ErrorCode.swift
//  eID-Mobile-iOS
//
//  Created by Sunay Gyultekin on 8.02.24.
//

import Foundation


enum ErrorCode: Int {
    case noInternet = 0
    case unauthorized = 401
    case notFound = 404
    case serverFailureLowerBound = 500
    case serverFailureUpperBound = 599
}

/*
enum ErrorMessage: String, Codable {
    CITIZEN_CERTIFICATE_NOT_FOUND_SN_AND_ISSUER("Citizen Certificate By SN And Issuer Not Found", "Citizen Certificate not found for SerialNumber: %s and Issuer: %s"),
        CITIZEN_CERTIFICATE_NOT_FOUND_ID("Citizen Certificate By ID Not Found", "Citizen Certificate not found for ID: "),
        CITIZEN_CERTIFICATE_NOT_FOUND_EIDENTITY_ID("Citizen Certificate Not Found By EidentityID", "Citizen Certificate not found for eidentityId: "),
        CITIZEN_CERTIFICATE_NOT_FOUND_BY_CERTIFICATE_AND_PROFILE_ID("Citizen Certificate Not Found By certificate and profileId", "Citizen Certificate Not Found By certificate and profileId:%s"),
        REGISTRY_ERROR("Registry Error", "An error occurred while accessing the registry."),
        EIDENTITY_CERTIFICATE_MISMATCHED("Eidentity Certificate Mismatched", "Provided Eidentity [%s] does not match the certificate.subject.uid [%s]"),
        EIDENTITY_NOT_FOUND_BY_ID("Eidentity Not Found", "Citizen Identifier not found for eidentityId: "),
        EIDENTITY_NOT_FOUND_BY_NUMBER("Eidentity Not Found", "Citizen Identifier not found by number."),
        EIDENTITY_NOT_ACTIVE("Eidentity Not Active", "Citizen Identifier is not active for eidentityId: "),
        CITIZEN_EMAIL_NOT_FOUND("Citizen Email Not Found", "Citizen not found for email: "),
        CITIZEN_PROFILE_NOT_FOUND("Citizen Profile Not Found", "Citizen Profile not found for eidentityId: %s"),
        CITIZEN_PROFILE_NOT_FOUND_BY_ID("Citizen Profile Not Found", "Citizen Profile not found for id: %s"),
        CITIZEN_ID_NOT_FOUND("Citizen ID Not Found", "Citizen not found for ID: "),
        PASSWORD_RESET_TOKEN_NOT_FOUND("Citizen Password Reset Token Not Found", "Citizen password reset token could not be found in the registry."),
        VERIFY_TOKEN_NOT_FOUND("Citizen Verify Token Not Found", "Citizen verify token could not be found in the registry."),
        APPLICATION_NOT_FOUND("Application not found", "Application with id:%s not found"),
        EID_ADMINISTRATOR_NOT_FOUND("Eid Administrator not found", "Eid Administrator with that name does not exist"),
        NOMENCLATURES_NOT_FOUND("No Nomenclatures found","No Nomenclatures found"),
        REASON_NOT_FOUND("Reason not found","Reason with id:%s not found"),
        REASON_NOT_FOUND_BY_NAME("Reason not found","Reason with name:%s not found"),
        CERTIFICATE_HISTORY_NOT_FOUND("Certificate history not found","Certificate history with certificateId:%s not found"),
        CERTIFICATE_NOT_FOUND_IN_EJBCA("Certificate not found in EJBCA","Certificate in EJBCA with certificateId:%s not found"),
        WRONG_CERTIFICATE_STATUS("Certificate is revoked","Status of certificate is revoked and cannot be updated"),
        ADMINISTRATOR_FRONT_OFFICE_NOT_FOUND("Administrator Front Office not found", "Administrator Front Office with id:%s not found"),
        ADMINISTRATOR_FRONT_OFFICE_ID_CANNOT_BE_NULL("Administrator Front Office id cannot be null", "Administrator Front Office id cannot be null"),
        EID_ADMINISTRATOR_ID_CANNOT_BE_NULL("Administrator id cannot be null", "Administrator id cannot be null"),
        APPLICATION_IS_ALREADY_SIGNED("Application is already signed", "Application with id: %s is already signed"),
        CERTIFICATE_IS_ALREADY_GENERATED("Certificate is already generated", "Certificate for application with id: %s is already generated"),
        E_SIGNATURE_DOES_NOT_MATCH("E-Signature does not match application data", "E-signature details and application details don't match"),
        ENTITY_NOT_FOUND("%s Not Found", "%s with id:%s not found"),
        CITIZEN_PROFILE_EXISTS_BY_EMAIL("Email is already taken", "Profile with that email already exists"),
        CITIZEN_PROFILE_EXISTS_BY_PHONE_NUMBER("Phone number is already taken", "Profile with that phone number already exists"),
        EMAIL_TOKEN_NOT_FOUND("Email token not found", "Email token not found"),
        CITIZEN_IDENTIFIER_NOT_FOUND_BY_NUMBER("Citizen Identifier not found by number", "Citizen Identifier not found by number: %s"),
        VALIDATION_ERROR("Validation error", "Validation error", false),
        INTERNAL_SERVER_ERROR("Internal Server Error", "Internal Server Error", false),
        CITIZEN_IDENTIFIER_TYPE_CANNOT_BE_NULL("Citizen Identifier Type cannot be null", "Citizen Identifier Type cannot be null"),
        CITIZEN_IDENTIFIER_NUMBER_CANNOT_BE_NULL("Citizen Identifier Number cannot be null", "Citizen Identifier Number cannot be null"),
        CITIZEN_IDENTIFIER_NUMBER_NOT_VALID("Citizen Identifier Number is not valid", "Citizen Identifier Number is not valid"),
        CITIZEN_IDENTIFIER_NOT_VALID("Citizen Identifier not valid", "Citizen Identifier not valid"),
        APPLICATION_SUBMISSION_TYPE_CANNOT_BE_NULL("Application submission type cannot be null", "Application submission type cannot be null"),
        CERTIFICATE_ID_CANNOT_BE_NULL("Certificate ID cannot be null", "Certificate ID cannot be null"),
        REASON_CANNOT_BE_NULL("Reason cannot be null", "Reason cannot be null"),
        CITIZENSHIP_CANNOT_BE_NULL("Citizenship cannot be null", "Citizenship cannot be null"),
        GUARDIAN_FIRST_NAME_CANNOT_BE_BLANK("Guardian first name cannot be blank", "Guardian first name cannot be blank"),
        GUARDIAN_SECOND_NAME_CANNOT_BE_BLANK("Guardian second name cannot be blank", "Guardian second name cannot be blank"),
        GUARDIAN_LAST_NAME_CANNOT_BE_BLANK("Guardian last name cannot be blank", "Guardian last name cannot be blank"),
        GUARDIAN_CITIZEN_IDENTIFIER_NUMBER_CANNOT_BE_BLANK("Guardian citizen identifier number cannot be blank", "Guardian citizen identifier number cannot be blank"),
        GUARDIAN_CITIZEN_IDENTIFIER_TYPE_CANNOT_BE_NULL("Guardian citizen identifier type cannot be blank", "Guardian citizen identifier type cannot be blank"),
        GUARDIAN_IDENTITY_DOCUMENT_CANNOT_BE_NULL("Guardian identity document cannot be null", "Guardian identity document cannot be null"),
        GUARDIAN_IDENTITY_ISSUE_DATE_CANNOT_BE_NULL("Guardian personal identity document issue date cannot be null", "Guardian personal identity document issue date cannot be null"),
        GUARDIAN_IDENTITY_VALIDITY_DATE_CANNOT_BE_NULL("Guardian personal identity document validity date cannot be null", "Guardian personal identity document validity date cannot be null"),
        GUARDIAN_IDENTITY_TYPE_CANNOT_BE_BLANK("Guardian personal identity document identity type cannot be blank", "Guardian personal identity document identity type cannot be blank"),
        GUARDIAN_IDENTITY_NUMBER_CANNOT_BE_BLANK("Guardian personal identity document identity number cannot be blank", "Guardian personal identity document identity number cannot be blank"),
        GUARDIAN_IDENTITY_ISSUER_CANNOT_BE_BLANK("Guardian personal identity document identity issuer cannot be blank", "Guardian personal identity document identity issuer cannot be blank"),
        EMAIL_NOT_VALID("Email is not valid", "Email is not valid"),
        PHONE_NUMBER_NOT_VALID("Phone number is not valid", "Phone number is not valid"),
        GUARDIAN_DETAILS_CANNOT_BE_NULL("Guardian details are required", "Guardian details are required"),
        ENDPOINT_IS_FOR_CHANGE_STATUS_APPLICATIONS("Only change status applications allowed","Endpoint can only be used for applications, which change the status of a certificate"),
        ONLINE_OFFICE_REQUIRES_EID_SUBMISSION("Online office requires EID submission","Online office requires EID submitted application"),
        ONLINE_OFFICE_REQUIRES_MOBILE("Online office requires Mobile certificate","Online office can only be used for mobile certificates"),
        APPLICATION_WITH_THAT_ID_ALREADY_EXISTS("Application already exists","Application with that id already exists"),
        ENDPOINT_IS_ONLY_FOR_ISSUE_EID("Endpoint is only for Issue EID","Endpoint can only be used for issuing certificates"),
        APPLICATION_CANNOT_BE_DENIED("Application cannot be denied","Status:%s is final and application with id:%s cannot be denied"),
        STATUS_NOT_EXPECTED("Status not expected","Status:%s is not expected for application with id:%s"),
        APPLICATION_CANNOT_BE_CONFIRMED("Application cannot be confirmed","Application is not eligible to confirmation"),
        CANNOT_CONFIRM_STORAGE("Cannot confirm storage","Cannot confirm storage for certificate"),
        OPERATION_NOT_SUPPORTED("Operation not supported","Operation not supported for application with id:%s"),
        MORE_THAN_ONE_VALID_PIPELINES_EXIST("More than one valid pipelines exist","More than one valid pipelines are found (%s) that can process application with id: %s"),
        NO_VALID_PIPELINES_EXIST("No valid pipelines exist","No valid pipelines are found that can process application with id:%s"),
        REASON_TEXT_CANNOT_BE_BLANK("Reason text cannot be blank","Reason text cannot be blank"),
        REASON_NOT_SUPPORTED("Reason ID not supported","The given application does not support the selected reasonId"),
        REASON_TEXT_REQUIRES_DIFFERENT_REASON("Reason text requires different reasonType","Reason text cannot be used with this reasonType"),
        DEVICE_NOT_RECOGNIZED("Device type not recognized","Device type not recognized"),
        MISSING_USER_IDS("User IDs are missing","userid and citizenProfileId cannot be null"),
        MULTIPLE_CARRIERS_FOUND_FOR_SN("Multiple carriers found for SN","More than one carrier found for this serial number"),
        PERSONAL_DETAILS_ARE_INCORRECT("Personal Details are incorrect","Personal Details are incorrect"),
        APPLICATION_ID_CANNOT_BE_NULL("Application ID cannot be null","Application ID cannot be null"),
        ISSUER_CANNOT_BE_BLANK("Issuer cannot be blank","Issuer cannot be blank"),
        CANNOT_GENERATE_QR_CODE("Cannot generate QR Code","Cannot generate QR Code"),
        OTP_CODE_DOES_NOT_EXIST("OTP Code does not exist","OTP Code does not exist"),
        OTP_SECRET_CANNOT_BE_NULL("OTP secret cannot be null","OTP secret cannot be null"),
        OTP_ISSUER_CANNOT_BE_NULL("OTP issuer cannot be null","OTP issuer cannot be null"),
        OTP_CODE_IS_NOT_VALID("OTP Code is not valid","OTP Code is not valid"),
        COULD_NOT_VERIFY_CITIZEN_DATA("Could not verify citizen data","Could not verify citizen data. IdentifierType not supported"),
        REGIX_EXCEPTION("Regix could not verify request","Regix could not verify request"),
        SIGNS_DESK_AND_BASE_PROFILE_APPLICATIONS("Application cannot be signed","Only base profile and desk applications can be signed with this URL"),
        CONFIRM_IS_NOT_FOR_ONLINE_OFFICE("Confirm is not for online office","This confirm is not for online office"),
        CONFIRMS_ONLY_ONLINE_OFFICE("Confirm is only for online office","This confirm is only for online office"),
        SIGN_IS_NOT_FOR_ONLINE_OFFICE("Sign is not for online office","This sign is not for online office"),
        SIGNS_MOBILE_APPLICATIONS("Signs only mobile certificates","Sign can be used only for mobile certificates"),
        ENROLLS_DESK_APPLICATIONS("Enrolls only desk applications","This enroll can only be used for Desk created applications"),
        ENROLLS_CHIP_CARD_CERTIFICATES("Enrolls only chip card certificates","Enroll can be used only for chip card applications"),
        ENROLLS_DESK_AND_BASE_PROFILE_APPLICATIONS("Enrolls only desk and base profile applications","This enroll can only be used for Desk and Base Profile created applications"),
        ENROLLS_MOBILE_CERTIFICATES("Enrolls mobile certificates","Enroll can be used only for mobile certificate"),
        ENROLLS_EID_APPLICATIONS("Enrolls eid applications","This enroll can only be used for EID created applications"),
        ENROLLS_ONLY_ONLINE_OFFICE("Enrolls only applications with online office","Enrolls only applications with online office"),
        SIGNS_CHIP_CARD_APPLICATIONS("Sign is for identity card applications","Sign can be used only for identity card applications"),
        CITIZEN_PROFILE_ID_CANNOT_BE_NULL("Citizen Profile Id cannot be null","citizenProfileId cannot be null"),
        CONFIRMS_MOBILE_STORAGE("Confirms only mobile applications","Only mobile applications can be confirmed with this URL"),
        CONFIRMS_DESK_AND_BASE_PROFILE_APPLICATIONS("Confirms only base profile and desk applications","Only base profile and desk applications can be confirmed with this URL"),
        CONFIRMS_EID_APPLICATIONS("Confirms only eid applications","Only eid applications can be confirmed with this URL"),
        USER_ID_CANNOT_BE_NULL("User ID cannot be null","userId cannot be null"),
        APPLICATION_NOT_IN_REQUIRED_PIPELINE_STATUS("Application is in wrong status","Application is not in the required pipeline status"),
        ONLY_MOBILE_APPLICATION_SETS_GUARDIANS("Cannot set guardians","Only mobile application can require manually set guardians"),
        APPLICATION_DOES_NOT_REQUIRE_GUARDIANS("Cannot set guardians","Application does not require guardians"),
        PUN_CARRIER_CANNOT_BE_NULL("PunCarrier cannot be null","PunCarrier cannot be null"),
        EIDENTITY_CANNOT_BE_CREATED("There was a problem with EIdentity creation","There was a problem with EIdentity creation"),
        EIDENTITY_NOT_FOUND("There was a problem with Get EIdentity","There was a problem with Get EIdentity"),
        FIRST_NAME_IS_DIFFERENT_FROM_EXISTING_ONE("The provided FIRST_NAME does not correspond to the existing one","The provided FIRST_NAME does not correspond to the existing one"),
        SECOND_NAME_IS_DIFFERENT_FROM_EXISTING_ONE("The provided SECOND_NAME does not correspond to the existing one","The provided SECOND_NAME does not correspond to the existing one"),
        LAST_NAME_IS_DIFFERENT_FROM_EXISTING_ONE("The provided LAST_NAME does not correspond to the existing one","The provided LAST_NAME does not correspond to the existing one"),
        CITIZEN_IDENTIFIER_NUMBER_IS_DIFFERENT_FROM_EXISTING_ONE("The provided CITIZEN_IDENTIFIER_NUMBER does not correspond to the existing one","The provided CITIZEN_IDENTIFIER_NUMBER does not correspond to the existing one"),
        CITIZEN_IDENTIFIER_TYPE_IS_DIFFERENT_FROM_EXISTING_ONE("The provided CITIZEN_IDENTIFIER_TYPE does not correspond to the existing one","The provided CITIZEN_IDENTIFIER_TYPE does not correspond to the existing one"),
        PHONE_NUMBER_IS_DIFFERENT_FROM_EXISTING_ONE("The provided PHONE_NUMBER does not correspond to the existing one","The provided PHONE_NUMBER does not correspond to the existing one"),
        EMAIL_IS_DIFFERENT_FROM_EXISTING_ONE("The provided EMAIL does not correspond to the existing one","The provided EMAIL does not correspond to the existing one"),
        REQUESTER_IS_NOT_OWNER("Requester doesn't match with certificate's owner","Requester doesn't match with certificate's owner"),
        PROFILE_MUST_BE_VERIFIED("Profile must be first verified","Profile must be first verified"),
        CITIZEN_PROFILE_CANNOT_BE_CREATED("Citizen Profile cannot be created","There was a problem with the Citizen Profile Creation"),
        NO_CERTIFICATES_FOUND_FOR_EIDENTITY_ID("No certificates found for eidentity ID","No certificates found for user with eidentityId:%s"),
        IDENTITY_ISSUE_DATE_IS_DIFFERENT_FROM_EXISTING_ONE("The provided PERSONAL_ID_DOCUMENT.IDENTITY_ISSUE_DATE does not correspond to the existing one","The provided PERSONAL_ID_DOCUMENT.IDENTITY_ISSUE_DATE does not correspond to the existing one"),
        IDENTITY_VALIDITY_TO_DATE_IS_DIFFERENT_FROM_EXISTING_ONE("The provided PERSONAL_ID_DOCUMENT.IDENTITY_VALIDITY_TO_DATE does not correspond to the existing one","The provided PERSONAL_ID_DOCUMENT.IDENTITY_VALIDITY_TO_DATE does not correspond to the existing one"),
        IDENTITY_ISSUER_IS_DIFFERENT_FROM_EXISTING_ONE("The provided PERSONAL_ID_DOCUMENT.IDENTITY_ISSUER does not correspond to the existing one","The provided PERSONAL_ID_DOCUMENT.IDENTITY_ISSUER does not correspond to the existing one"),
        IDENTITY_NUMBER_IS_DIFFERENT_FROM_EXISTING_ONE("The provided PERSONAL_ID_DOCUMENT.IDENTITY_NUMBER does not correspond to the existing one","The provided PERSONAL_ID_DOCUMENT.IDENTITY_NUMBER does not correspond to the existing one"),
        IDENTITY_TYPE_IS_DIFFERENT_FROM_EXISTING_ONE("The provided PERSONAL_ID_DOCUMENT.IDENTITY_TYPE does not correspond to the existing one","The provided PERSONAL_ID_DOCUMENT.IDENTITY_TYPE does not correspond to the existing one"),
        FIRST_NAME_LATIN_IS_DIFFERENT_FROM_EXISTING_ONE("The provided FIRST_NAME_LATIN does not correspond to the existing one","The provided FIRST_NAME_LATIN does not correspond to the existing one"),
        SECOND_NAME_LATIN_IS_DIFFERENT_FROM_EXISTING_ONE("The provided SECOND_NAME_LATIN does not correspond to the existing one","The provided SECOND_NAME_LATIN does not correspond to the existing one"),
        LAST_NAME_LATIN_IS_DIFFERENT_FROM_EXISTING_ONE("The provided LAST_NAME_LATIN does not correspond to the existing one","The provided LAST_NAME_LATIN does not correspond to the existing one"),
        NATIONALITY_IS_DIFFERENT_FROM_EXISTING_ONE("The provided CITIZENSHIP/NATIONALITY does not correspond to the existing one","The provided CITIZENSHIP/NATIONALITY does not correspond to the existing one"),
        CERTIFICATE_CANNOT_BE_STOPPED("Certificate cannot be stopped","Certificate with id: %s is %s and cannot be stopped"),
        CERTIFICATE_CANNOT_BE_REVOKED("Certificate cannot be revoked","Certificate with id: %s is %s and cannot be revoked"),
        CERTIFICATE_CANNOT_BE_RESUMED("Certificate cannot be resumed","Certificate with id: %s is %s and cannot be resumed"),
        DEVICE_TYPE_NOT_RECOGNIZED("Device Type not recognized","Device Type not recognized"),
        CERTIFICATE_IS_EXPIRED_OR_INVALID("Certificate is expired or invalid","Certificate is expired or invalid"),
        CITIZEN_IS_DEAD("The citizen is dead","The citizen is dead"),
        CITIZEN_IS_PROHIBITED("Citizen is prohibited from creating online applications","Citizen is prohibited from creating online applications"),
        PASSWORDS_DONT_MATCH("Passwords don't match","Passwords don't match"),
        ONLY_DESK_APPLICATIONS_CAN_BE_REVOKED("Only desk applications support the Revoke operation","Only desk applications support the Revoke operation"),
        USER_ID_OR_CITIZEN_PROFILE_ID_MUST_BE_PROVIDED("Either userId or citizenProfileId must be provided","Either userId or citizenProfileId must be provided"),
        EIDENTITY_ID_CANNOT_BE_NULL("EidentityId cannot be null","EidentityId cannot be null"),
        PROFILE_WITH_THAT_EIDENTITY_ID_EXISTS("Profile with that eidentityId already exist","Profile with that eidentityId already exist"),
        PASSWORD_IS_INCORRECT("Password is incorrect","Password is incorrect"),
        MOBILE_APPLICATION_INSTANCE_ID_NOT_VALID("MobileApplicationInstanceId is not valid","MobileApplicationInstanceId is not valid"),
        MOBILE_ASSOCIATED_TO_DIFFERENT_PROFILE("Mobile device with instanceId:%s is associated to a different profile","Mobile device with instanceId:%s is associated to a different profile"),
        ADMINISTRATOR_FRONT_OFFICE_NAME_REQUIRED("Administrator Front Office Name is required","Administrator Front Office Name is required"),
        ADMINISTRATOR_FRONT_OFFICE_LOCATION_REQUIRED("Administrator Front Office Location is required","Administrator Front Office Location is required"),
        ADMINISTRATOR_FRONT_OFFICE_CONTACT_REQUIRED("Administrator Front Office Contact is required","Administrator Front Office Contact is required"),
        ADMINISTRATOR_FRONT_OFFICE_EID_ADMINISTRATOR_ID_REQUIRED("Administrator Front Office Eid Administrator ID is required","Administrator Front Office Eid Administrator ID is required"),
        ADMINISTRATOR_FRONT_OFFICE_ACTIVE_STATUS_REQUIRED("Administrator Front Office Active Status is required","Administrator Front Office Active Status is required"),
        EID_ADMINISTRATOR_NAME_REQUIRED("Eid Administrator Name is required","Eid Administrator Name is required"),
        EID_ADMINISTRATOR_ACTIVE_STATUS_REQUIRED("Eid Administrator Active Status is required","Eid Administrator Active Status is required"),
        EID_ADMINISTRATOR_EIK_NUMBER_REQUIRED("Eid Administrator EikNumber is required","Eid Administrator EikNumber is required"),
        INVALID_APPLICATION_NUMBER_PREFIX_TYPE("Invalid application number prefix type","Invalid application number prefix type"),
        ADMINISTRATOR_FRONT_OFFICE_NOT_FOUND_BY_NAME("Administrator Front Office not found", "Administrator Front Office with name:%s not found"),
        DEVICE_NOT_FOUND_BY_TYPE("Device Not Found", "Device with type:%s not found"),
        INVALID_REPORT_FORMAT_TYPE("Invalid format", "Report with format:%s is not supported"),
        FIRST_NAME_CANNOT_BE_BLANK("First name cannot be blank", "First Name cannot be blank"),
        LAST_NAME_CANNOT_BE_BLANK("First name cannot be blank", "First Name cannot be blank"),
        FIRST_NAME_CANNOT_EXCEED_LENGTH("First name too long", "First Name cannot exceed 50 characters"),
        SECOND_NAME_CANNOT_EXCEED_LENGTH("Second name too long", "Second Name cannot exceed 50 characters"),
        LAST_NAME_CANNOT_EXCEED_LENGTH("Last name too long", "Last Name cannot exceed 50 characters"),
        FIRST_NAME_NOT_VALID("First name is not valid", "First Name is not valid"),
        SECOND_NAME_NOT_VALID("Second name is not valid", "Second Name is not valid"),
        LAST_NAME_NOT_VALID("Last name is not valid", "Last Name is not valid"),
        EMAIL_CANNOT_BE_BLANK("Email cannot be blank", "Email cannot be blank"),
        PASSWORD_CANNOT_BE_BLANK("Password cannot be blank", "Password cannot be blank"),
        PASSWORD_NOT_VALID("Password is not valid", "Password is not valid"),

        AUTHENTICATION_REQUEST_NOT_FOUND("The authentication request with the given ID is missing or expired","The authentication request with the given ID is missing or expired"),
        SIGNATURE_DOES_NOT_MATCH("Signature does not match the initial data", "Signature does not match the initial data"),
        CERTIFICATE_IS_NOT_VALID("The provided x509 Certificate is not valid","The provided x509 Certificate is not valid"),
        CERTIFICATE_IS_NOT_ACTIVE("The X509 Certificate is not ACTIVE","The X509 Certificate is not ACTIVE"),
        CERTIFICATES_DO_NOT_MATCH("The provided Certificate do not match with the one in the Registry", "The provided Certificate do not match with the one in the Registry")
}
*/
