spring:
  datasource:
    url: jdbc:postgresql://mvreid-db.local:5432/mvr_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000 #maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 3 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 10 #maximum pool size
      idle-timeout: 15000 #maximum idle time for connection
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true #default auto-commit behavior.
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: false #2nd step to run db/schema.sql, db/data.sql scripts
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect #net.optionfactory.hj.postgres.PostgreSQL95DialectWithJsonb
    hibernate:
      ddl-auto: update #none, validate, update, create, create-drop
    generate-ddl: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  h2:
    console:
      enabled: false
  sql:
    init:
      encoding: UTF-8
      mode: always
      #      schema-locations: 'classpath:db/schema.sql'
      #      data-locations: 'classpath:db/data.sql'
      continue-on-error: true
 