spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb;INIT=RUNSCRIPT FROM 'src/main/resources/db/test/test_db_init.sql';DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=2000;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 30000 #maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 3 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 10 #maximum pool size
      idle-timeout: 15000 #maximum idle time for connection
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true #default auto-commit behavior.
  jpa:
    database: h2
    hibernate:
      ddl-auto: update #none, validate, update, create, create-drop
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
      org.hibernate.envers:
        #        default_schema: audit
        audit_table_suffix: _audit
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true #2nd step to run db/schema.sql, db/data.sql scripts
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      encoding: UTF-8
      mode: always
      #      schema-locations: 'classpath:db/test/v0001_db_init.sql'
      #      data-locations: 'classpath:db/data.sql'
      continue-on-error: true