/*
 * ISCEI HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using IsceiSdk.Client;

namespace IsceiSdk.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IStatisticsControllerApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="IsceiSdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDateFrom"></param>
        /// <param name="createDateTo"></param>
        /// <param name="systemType"> (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="isEmployee"> (optional)</param>
        /// <param name="success"> (optional)</param>
        /// <returns>List&lt;List&lt;string&gt;&gt;</returns>
        List<List<string>> ReportDetailed(DateTime createDateFrom, DateTime createDateTo, string systemType = default, string clientId = default, bool? isEmployee = default, bool? success = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IsceiSdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDateFrom"></param>
        /// <param name="createDateTo"></param>
        /// <param name="systemType"> (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="isEmployee"> (optional)</param>
        /// <param name="success"> (optional)</param>
        /// <returns>ApiResponse of List&lt;List&lt;string&gt;&gt;</returns>
        ApiResponse<List<List<string>>> ReportDetailedWithHttpInfo(DateTime createDateFrom, DateTime createDateTo, string systemType = default, string clientId = default, bool? isEmployee = default, bool? success = default);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="IsceiSdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDateFrom"></param>
        /// <param name="createDateTo"></param>
        /// <param name="systemType"> (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <returns>List&lt;List&lt;string&gt;&gt;</returns>
        List<List<string>> ReportRequestsCount(DateTime createDateFrom, DateTime createDateTo, string systemType = default, string clientId = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IsceiSdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDateFrom"></param>
        /// <param name="createDateTo"></param>
        /// <param name="systemType"> (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <returns>ApiResponse of List&lt;List&lt;string&gt;&gt;</returns>
        ApiResponse<List<List<string>>> ReportRequestsCountWithHttpInfo(DateTime createDateFrom, DateTime createDateTo, string systemType = default, string clientId = default);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="IsceiSdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="year"></param>
        /// <returns>List&lt;List&lt;string&gt;&gt;</returns>
        List<List<string>> ReportRequestsTotal(int year);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IsceiSdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="year"></param>
        /// <returns>ApiResponse of List&lt;List&lt;string&gt;&gt;</returns>
        ApiResponse<List<List<string>>> ReportRequestsTotalWithHttpInfo(int year);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IStatisticsControllerApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IsceiSdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDateFrom"></param>
        /// <param name="createDateTo"></param>
        /// <param name="systemType"> (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="isEmployee"> (optional)</param>
        /// <param name="success"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;List&lt;string&gt;&gt;</returns>
        System.Threading.Tasks.Task<List<List<string>>> ReportDetailedAsync(DateTime createDateFrom, DateTime createDateTo, string systemType = default, string clientId = default, bool? isEmployee = default, bool? success = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IsceiSdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDateFrom"></param>
        /// <param name="createDateTo"></param>
        /// <param name="systemType"> (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="isEmployee"> (optional)</param>
        /// <param name="success"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;List&lt;string&gt;&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<List<string>>>> ReportDetailedWithHttpInfoAsync(DateTime createDateFrom, DateTime createDateTo, string systemType = default, string clientId = default, bool? isEmployee = default, bool? success = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IsceiSdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDateFrom"></param>
        /// <param name="createDateTo"></param>
        /// <param name="systemType"> (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;List&lt;string&gt;&gt;</returns>
        System.Threading.Tasks.Task<List<List<string>>> ReportRequestsCountAsync(DateTime createDateFrom, DateTime createDateTo, string systemType = default, string clientId = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IsceiSdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDateFrom"></param>
        /// <param name="createDateTo"></param>
        /// <param name="systemType"> (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;List&lt;string&gt;&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<List<string>>>> ReportRequestsCountWithHttpInfoAsync(DateTime createDateFrom, DateTime createDateTo, string systemType = default, string clientId = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IsceiSdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="year"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;List&lt;string&gt;&gt;</returns>
        System.Threading.Tasks.Task<List<List<string>>> ReportRequestsTotalAsync(int year, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IsceiSdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="year"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;List&lt;string&gt;&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<List<string>>>> ReportRequestsTotalWithHttpInfoAsync(int year, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IStatisticsControllerApi : IStatisticsControllerApiSync, IStatisticsControllerApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class StatisticsControllerApi : IDisposable, IStatisticsControllerApi
    {
        private IsceiSdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="StatisticsControllerApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public StatisticsControllerApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StatisticsControllerApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public StatisticsControllerApi(string basePath)
        {
            this.Configuration = IsceiSdk.Client.Configuration.MergeConfigurations(
                IsceiSdk.Client.GlobalConfiguration.Instance,
                new IsceiSdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new IsceiSdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = IsceiSdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StatisticsControllerApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public StatisticsControllerApi(IsceiSdk.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = IsceiSdk.Client.Configuration.MergeConfigurations(
                IsceiSdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new IsceiSdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = IsceiSdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StatisticsControllerApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public StatisticsControllerApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StatisticsControllerApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public StatisticsControllerApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = IsceiSdk.Client.Configuration.MergeConfigurations(
                IsceiSdk.Client.GlobalConfiguration.Instance,
                new IsceiSdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new IsceiSdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = IsceiSdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StatisticsControllerApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public StatisticsControllerApi(HttpClient client, IsceiSdk.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = IsceiSdk.Client.Configuration.MergeConfigurations(
                IsceiSdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new IsceiSdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = IsceiSdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StatisticsControllerApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public StatisticsControllerApi(IsceiSdk.Client.ISynchronousClient client, IsceiSdk.Client.IAsynchronousClient asyncClient, IsceiSdk.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = IsceiSdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public IsceiSdk.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public IsceiSdk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public IsceiSdk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IsceiSdk.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IsceiSdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IsceiSdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDateFrom"></param>
        /// <param name="createDateTo"></param>
        /// <param name="systemType"> (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="isEmployee"> (optional)</param>
        /// <param name="success"> (optional)</param>
        /// <returns>List&lt;List&lt;string&gt;&gt;</returns>
        public List<List<string>> ReportDetailed(DateTime createDateFrom, DateTime createDateTo, string systemType = default, string clientId = default, bool? isEmployee = default, bool? success = default)
        {
            IsceiSdk.Client.ApiResponse<List<List<string>>> localVarResponse = ReportDetailedWithHttpInfo(createDateFrom, createDateTo, systemType, clientId, isEmployee, success);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IsceiSdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDateFrom"></param>
        /// <param name="createDateTo"></param>
        /// <param name="systemType"> (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="isEmployee"> (optional)</param>
        /// <param name="success"> (optional)</param>
        /// <returns>ApiResponse of List&lt;List&lt;string&gt;&gt;</returns>
        public IsceiSdk.Client.ApiResponse<List<List<string>>> ReportDetailedWithHttpInfo(DateTime createDateFrom, DateTime createDateTo, string systemType = default, string clientId = default, bool? isEmployee = default, bool? success = default)
        {
            IsceiSdk.Client.RequestOptions localVarRequestOptions = new IsceiSdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = IsceiSdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = IsceiSdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(IsceiSdk.Client.ClientUtils.ParameterToMultiMap("", "createDateFrom", createDateFrom));
            localVarRequestOptions.QueryParameters.Add(IsceiSdk.Client.ClientUtils.ParameterToMultiMap("", "createDateTo", createDateTo));
            if (systemType != null)
            {
                localVarRequestOptions.QueryParameters.Add(IsceiSdk.Client.ClientUtils.ParameterToMultiMap("", "systemType", systemType));
            }
            if (clientId != null)
            {
                localVarRequestOptions.QueryParameters.Add(IsceiSdk.Client.ClientUtils.ParameterToMultiMap("", "clientId", clientId));
            }
            if (isEmployee != null)
            {
                localVarRequestOptions.QueryParameters.Add(IsceiSdk.Client.ClientUtils.ParameterToMultiMap("", "isEmployee", isEmployee));
            }
            if (success != null)
            {
                localVarRequestOptions.QueryParameters.Add(IsceiSdk.Client.ClientUtils.ParameterToMultiMap("", "success", success));
            }

            // authentication (ISCEI) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<List<string>>>("/api/v1/statistics/report/detailed", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReportDetailed", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IsceiSdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDateFrom"></param>
        /// <param name="createDateTo"></param>
        /// <param name="systemType"> (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="isEmployee"> (optional)</param>
        /// <param name="success"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;List&lt;string&gt;&gt;</returns>
        public async System.Threading.Tasks.Task<List<List<string>>> ReportDetailedAsync(DateTime createDateFrom, DateTime createDateTo, string systemType = default, string clientId = default, bool? isEmployee = default, bool? success = default, System.Threading.CancellationToken cancellationToken = default)
        {
            IsceiSdk.Client.ApiResponse<List<List<string>>> localVarResponse = await ReportDetailedWithHttpInfoAsync(createDateFrom, createDateTo, systemType, clientId, isEmployee, success, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IsceiSdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDateFrom"></param>
        /// <param name="createDateTo"></param>
        /// <param name="systemType"> (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="isEmployee"> (optional)</param>
        /// <param name="success"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;List&lt;string&gt;&gt;)</returns>
        public async System.Threading.Tasks.Task<IsceiSdk.Client.ApiResponse<List<List<string>>>> ReportDetailedWithHttpInfoAsync(DateTime createDateFrom, DateTime createDateTo, string systemType = default, string clientId = default, bool? isEmployee = default, bool? success = default, System.Threading.CancellationToken cancellationToken = default)
        {

            IsceiSdk.Client.RequestOptions localVarRequestOptions = new IsceiSdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = IsceiSdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = IsceiSdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(IsceiSdk.Client.ClientUtils.ParameterToMultiMap("", "createDateFrom", createDateFrom));
            localVarRequestOptions.QueryParameters.Add(IsceiSdk.Client.ClientUtils.ParameterToMultiMap("", "createDateTo", createDateTo));
            if (systemType != null)
            {
                localVarRequestOptions.QueryParameters.Add(IsceiSdk.Client.ClientUtils.ParameterToMultiMap("", "systemType", systemType));
            }
            if (clientId != null)
            {
                localVarRequestOptions.QueryParameters.Add(IsceiSdk.Client.ClientUtils.ParameterToMultiMap("", "clientId", clientId));
            }
            if (isEmployee != null)
            {
                localVarRequestOptions.QueryParameters.Add(IsceiSdk.Client.ClientUtils.ParameterToMultiMap("", "isEmployee", isEmployee));
            }
            if (success != null)
            {
                localVarRequestOptions.QueryParameters.Add(IsceiSdk.Client.ClientUtils.ParameterToMultiMap("", "success", success));
            }

            // authentication (ISCEI) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<List<string>>>("/api/v1/statistics/report/detailed", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReportDetailed", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IsceiSdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDateFrom"></param>
        /// <param name="createDateTo"></param>
        /// <param name="systemType"> (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <returns>List&lt;List&lt;string&gt;&gt;</returns>
        public List<List<string>> ReportRequestsCount(DateTime createDateFrom, DateTime createDateTo, string systemType = default, string clientId = default)
        {
            IsceiSdk.Client.ApiResponse<List<List<string>>> localVarResponse = ReportRequestsCountWithHttpInfo(createDateFrom, createDateTo, systemType, clientId);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IsceiSdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDateFrom"></param>
        /// <param name="createDateTo"></param>
        /// <param name="systemType"> (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <returns>ApiResponse of List&lt;List&lt;string&gt;&gt;</returns>
        public IsceiSdk.Client.ApiResponse<List<List<string>>> ReportRequestsCountWithHttpInfo(DateTime createDateFrom, DateTime createDateTo, string systemType = default, string clientId = default)
        {
            IsceiSdk.Client.RequestOptions localVarRequestOptions = new IsceiSdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = IsceiSdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = IsceiSdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(IsceiSdk.Client.ClientUtils.ParameterToMultiMap("", "createDateFrom", createDateFrom));
            localVarRequestOptions.QueryParameters.Add(IsceiSdk.Client.ClientUtils.ParameterToMultiMap("", "createDateTo", createDateTo));
            if (systemType != null)
            {
                localVarRequestOptions.QueryParameters.Add(IsceiSdk.Client.ClientUtils.ParameterToMultiMap("", "systemType", systemType));
            }
            if (clientId != null)
            {
                localVarRequestOptions.QueryParameters.Add(IsceiSdk.Client.ClientUtils.ParameterToMultiMap("", "clientId", clientId));
            }

            // authentication (ISCEI) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<List<string>>>("/api/v1/statistics/report/requests-count", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReportRequestsCount", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IsceiSdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDateFrom"></param>
        /// <param name="createDateTo"></param>
        /// <param name="systemType"> (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;List&lt;string&gt;&gt;</returns>
        public async System.Threading.Tasks.Task<List<List<string>>> ReportRequestsCountAsync(DateTime createDateFrom, DateTime createDateTo, string systemType = default, string clientId = default, System.Threading.CancellationToken cancellationToken = default)
        {
            IsceiSdk.Client.ApiResponse<List<List<string>>> localVarResponse = await ReportRequestsCountWithHttpInfoAsync(createDateFrom, createDateTo, systemType, clientId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IsceiSdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDateFrom"></param>
        /// <param name="createDateTo"></param>
        /// <param name="systemType"> (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;List&lt;string&gt;&gt;)</returns>
        public async System.Threading.Tasks.Task<IsceiSdk.Client.ApiResponse<List<List<string>>>> ReportRequestsCountWithHttpInfoAsync(DateTime createDateFrom, DateTime createDateTo, string systemType = default, string clientId = default, System.Threading.CancellationToken cancellationToken = default)
        {

            IsceiSdk.Client.RequestOptions localVarRequestOptions = new IsceiSdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = IsceiSdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = IsceiSdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(IsceiSdk.Client.ClientUtils.ParameterToMultiMap("", "createDateFrom", createDateFrom));
            localVarRequestOptions.QueryParameters.Add(IsceiSdk.Client.ClientUtils.ParameterToMultiMap("", "createDateTo", createDateTo));
            if (systemType != null)
            {
                localVarRequestOptions.QueryParameters.Add(IsceiSdk.Client.ClientUtils.ParameterToMultiMap("", "systemType", systemType));
            }
            if (clientId != null)
            {
                localVarRequestOptions.QueryParameters.Add(IsceiSdk.Client.ClientUtils.ParameterToMultiMap("", "clientId", clientId));
            }

            // authentication (ISCEI) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<List<string>>>("/api/v1/statistics/report/requests-count", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReportRequestsCount", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IsceiSdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="year"></param>
        /// <returns>List&lt;List&lt;string&gt;&gt;</returns>
        public List<List<string>> ReportRequestsTotal(int year)
        {
            IsceiSdk.Client.ApiResponse<List<List<string>>> localVarResponse = ReportRequestsTotalWithHttpInfo(year);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IsceiSdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="year"></param>
        /// <returns>ApiResponse of List&lt;List&lt;string&gt;&gt;</returns>
        public IsceiSdk.Client.ApiResponse<List<List<string>>> ReportRequestsTotalWithHttpInfo(int year)
        {
            IsceiSdk.Client.RequestOptions localVarRequestOptions = new IsceiSdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = IsceiSdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = IsceiSdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(IsceiSdk.Client.ClientUtils.ParameterToMultiMap("", "year", year));

            // authentication (ISCEI) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<List<string>>>("/api/v1/statistics/report/requests-total", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReportRequestsTotal", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IsceiSdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="year"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;List&lt;string&gt;&gt;</returns>
        public async System.Threading.Tasks.Task<List<List<string>>> ReportRequestsTotalAsync(int year, System.Threading.CancellationToken cancellationToken = default)
        {
            IsceiSdk.Client.ApiResponse<List<List<string>>> localVarResponse = await ReportRequestsTotalWithHttpInfoAsync(year, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IsceiSdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="year"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;List&lt;string&gt;&gt;)</returns>
        public async System.Threading.Tasks.Task<IsceiSdk.Client.ApiResponse<List<List<string>>>> ReportRequestsTotalWithHttpInfoAsync(int year, System.Threading.CancellationToken cancellationToken = default)
        {

            IsceiSdk.Client.RequestOptions localVarRequestOptions = new IsceiSdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = IsceiSdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = IsceiSdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(IsceiSdk.Client.ClientUtils.ParameterToMultiMap("", "year", year));

            // authentication (ISCEI) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<List<string>>>("/api/v1/statistics/report/requests-total", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReportRequestsTotal", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
