methods:
  post:
    summary: Create Application
    operationId: createDeskApplication
    tags:
      - ExternalAdministrators
    requestBody:
      required: true
      content:
        application/json;charset=UTF-8:
          schema:
            $ref: '../../components/application/desk_application_request_v1.yaml#/schemas/DeskApplicationRequest'
    responses:
      '200':
        description: Success
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/application/application_response_v1.yaml#/schemas/ApplicationResponse'
      '400':
        description: Bad Request
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/validation_problem_details_v1.yaml#/schemas/ValidationProblemDetails'
      '404':
        description: Not Found
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/problem_details_v1.yaml#/schemas/ProblemDetails'
      '409':
        description: Conflict
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/problem_details_v1.yaml#/schemas/ProblemDetails'
      '500':
        description: Server Error
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/problem_details_v1.yaml#/schemas/ProblemDetails'
      '504':
        description: Time Out
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/problem_details_v1.yaml#/schemas/ProblemDetails'
