server:
  port: 8098
  ssl:
    enabled: false
    trust-store:
    trust-store-password:
    trust-store-type: PKCS12
logging:
  secret-key:
spring:
  data:
    redis:
      host:
      port:
      password:
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    listener:
      simple:
        concurrency: 3
    host:
    username:
    password:
custom:
  rabbitmq:
    queue-prefix: raeicei.rpcqueue.
    management:
      port: