/*
 * eID - RO HTTP API
 *
 * Регистър на овластяванията (РО)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RoSdk.Model;
using RoSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RoSdk.Test.Model
{
    /// <summary>
    ///  Class for testing EmpowermentsFromMeSortBy
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmpowermentsFromMeSortByTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmpowermentsFromMeSortBy
        //private EmpowermentsFromMeSortBy instance;

        public EmpowermentsFromMeSortByTests()
        {
            // TODO uncomment below to create an instance of EmpowermentsFromMeSortBy
            //instance = new EmpowermentsFromMeSortBy();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmpowermentsFromMeSortBy
        /// </summary>
        [Fact]
        public void EmpowermentsFromMeSortByInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmpowermentsFromMeSortBy
            //Assert.IsType<EmpowermentsFromMeSortBy>(instance);
        }
    }
}
