/*
 * eID - RO HTTP API
 *
 * Регистър на овластяванията (РО)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RoSdk.Model;
using RoSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RoSdk.Test.Model
{
    /// <summary>
    ///  Class for testing EmpowermentDisagreementResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmpowermentDisagreementResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmpowermentDisagreementResult
        //private EmpowermentDisagreementResult instance;

        public EmpowermentDisagreementResultTests()
        {
            // TODO uncomment below to create an instance of EmpowermentDisagreementResult
            //instance = new EmpowermentDisagreementResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmpowermentDisagreementResult
        /// </summary>
        [Fact]
        public void EmpowermentDisagreementResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmpowermentDisagreementResult
            //Assert.IsType<EmpowermentDisagreementResult>(instance);
        }

        /// <summary>
        /// Test the property 'ActiveDateTime'
        /// </summary>
        [Fact]
        public void ActiveDateTimeTest()
        {
            // TODO unit test for the property 'ActiveDateTime'
        }

        /// <summary>
        /// Test the property 'IssuerUid'
        /// </summary>
        [Fact]
        public void IssuerUidTest()
        {
            // TODO unit test for the property 'IssuerUid'
        }

        /// <summary>
        /// Test the property 'IssuerUidType'
        /// </summary>
        [Fact]
        public void IssuerUidTypeTest()
        {
            // TODO unit test for the property 'IssuerUidType'
        }

        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
    }
}
