/*
 * eID - RO HTTP API
 *
 * Регистър на овластяванията (РО)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RoSdk.Model;
using RoSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RoSdk.Test.Model
{
    /// <summary>
    ///  Class for testing EmpowermentStatementFromMeResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmpowermentStatementFromMeResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmpowermentStatementFromMeResult
        //private EmpowermentStatementFromMeResult instance;

        public EmpowermentStatementFromMeResultTests()
        {
            // TODO uncomment below to create an instance of EmpowermentStatementFromMeResult
            //instance = new EmpowermentStatementFromMeResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmpowermentStatementFromMeResult
        /// </summary>
        [Fact]
        public void EmpowermentStatementFromMeResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmpowermentStatementFromMeResult
            //Assert.IsType<EmpowermentStatementFromMeResult>(instance);
        }

        /// <summary>
        /// Test the property 'EmpowermentSignatures'
        /// </summary>
        [Fact]
        public void EmpowermentSignaturesTest()
        {
            // TODO unit test for the property 'EmpowermentSignatures'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Fact]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }

        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }

        /// <summary>
        /// Test the property 'ExpiryDate'
        /// </summary>
        [Fact]
        public void ExpiryDateTest()
        {
            // TODO unit test for the property 'ExpiryDate'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Uid'
        /// </summary>
        [Fact]
        public void UidTest()
        {
            // TODO unit test for the property 'Uid'
        }

        /// <summary>
        /// Test the property 'UidType'
        /// </summary>
        [Fact]
        public void UidTypeTest()
        {
            // TODO unit test for the property 'UidType'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'OnBehalfOf'
        /// </summary>
        [Fact]
        public void OnBehalfOfTest()
        {
            // TODO unit test for the property 'OnBehalfOf'
        }

        /// <summary>
        /// Test the property 'AuthorizerUids'
        /// </summary>
        [Fact]
        public void AuthorizerUidsTest()
        {
            // TODO unit test for the property 'AuthorizerUids'
        }

        /// <summary>
        /// Test the property 'EmpoweredUids'
        /// </summary>
        [Fact]
        public void EmpoweredUidsTest()
        {
            // TODO unit test for the property 'EmpoweredUids'
        }

        /// <summary>
        /// Test the property 'ProviderId'
        /// </summary>
        [Fact]
        public void ProviderIdTest()
        {
            // TODO unit test for the property 'ProviderId'
        }

        /// <summary>
        /// Test the property 'ProviderName'
        /// </summary>
        [Fact]
        public void ProviderNameTest()
        {
            // TODO unit test for the property 'ProviderName'
        }

        /// <summary>
        /// Test the property 'ServiceId'
        /// </summary>
        [Fact]
        public void ServiceIdTest()
        {
            // TODO unit test for the property 'ServiceId'
        }

        /// <summary>
        /// Test the property 'ServiceName'
        /// </summary>
        [Fact]
        public void ServiceNameTest()
        {
            // TODO unit test for the property 'ServiceName'
        }

        /// <summary>
        /// Test the property 'VolumeOfRepresentation'
        /// </summary>
        [Fact]
        public void VolumeOfRepresentationTest()
        {
            // TODO unit test for the property 'VolumeOfRepresentation'
        }

        /// <summary>
        /// Test the property 'CreatedOn'
        /// </summary>
        [Fact]
        public void CreatedOnTest()
        {
            // TODO unit test for the property 'CreatedOn'
        }

        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Fact]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }

        /// <summary>
        /// Test the property 'IssuerPosition'
        /// </summary>
        [Fact]
        public void IssuerPositionTest()
        {
            // TODO unit test for the property 'IssuerPosition'
        }

        /// <summary>
        /// Test the property 'XmlRepresentation'
        /// </summary>
        [Fact]
        public void XmlRepresentationTest()
        {
            // TODO unit test for the property 'XmlRepresentation'
        }

        /// <summary>
        /// Test the property 'DenialReason'
        /// </summary>
        [Fact]
        public void DenialReasonTest()
        {
            // TODO unit test for the property 'DenialReason'
        }

        /// <summary>
        /// Test the property 'EmpowermentWithdrawals'
        /// </summary>
        [Fact]
        public void EmpowermentWithdrawalsTest()
        {
            // TODO unit test for the property 'EmpowermentWithdrawals'
        }

        /// <summary>
        /// Test the property 'EmpowermentDisagreements'
        /// </summary>
        [Fact]
        public void EmpowermentDisagreementsTest()
        {
            // TODO unit test for the property 'EmpowermentDisagreements'
        }

        /// <summary>
        /// Test the property 'StatusHistory'
        /// </summary>
        [Fact]
        public void StatusHistoryTest()
        {
            // TODO unit test for the property 'StatusHistory'
        }

        /// <summary>
        /// Test the property 'CalculatedStatusOn'
        /// </summary>
        [Fact]
        public void CalculatedStatusOnTest()
        {
            // TODO unit test for the property 'CalculatedStatusOn'
        }
    }
}
