/*
 * eID - RO HTTP API
 *
 * Регистър на овластяванията (РО)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RoSdk.Model;
using RoSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RoSdk.Test.Model
{
    /// <summary>
    ///  Class for testing LanguageType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LanguageTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LanguageType
        //private LanguageType instance;

        public LanguageTypeTests()
        {
            // TODO uncomment below to create an instance of LanguageType
            //instance = new LanguageType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LanguageType
        /// </summary>
        [Fact]
        public void LanguageTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" LanguageType
            //Assert.IsType<LanguageType>(instance);
        }
    }
}
