/*
 * eID - RO HTTP API
 *
 * Регистър на овластяванията (РО)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RoSdk.Model;
using RoSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RoSdk.Test.Model
{
    /// <summary>
    ///  Class for testing SignEmpowermentPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SignEmpowermentPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SignEmpowermentPayload
        //private SignEmpowermentPayload instance;

        public SignEmpowermentPayloadTests()
        {
            // TODO uncomment below to create an instance of SignEmpowermentPayload
            //instance = new SignEmpowermentPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SignEmpowermentPayload
        /// </summary>
        [Fact]
        public void SignEmpowermentPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" SignEmpowermentPayload
            //Assert.IsType<SignEmpowermentPayload>(instance);
        }

        /// <summary>
        /// Test the property 'SignatureProvider'
        /// </summary>
        [Fact]
        public void SignatureProviderTest()
        {
            // TODO unit test for the property 'SignatureProvider'
        }

        /// <summary>
        /// Test the property 'DetachedSignature'
        /// </summary>
        [Fact]
        public void DetachedSignatureTest()
        {
            // TODO unit test for the property 'DetachedSignature'
        }
    }
}
