/*
 * eID - RO HTTP API
 *
 * Регистър на овластяванията (РО)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RoSdk.Model;
using RoSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RoSdk.Test.Model
{
    /// <summary>
    ///  Class for testing StatusHistoryResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StatusHistoryResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StatusHistoryResult
        //private StatusHistoryResult instance;

        public StatusHistoryResultTests()
        {
            // TODO uncomment below to create an instance of StatusHistoryResult
            //instance = new StatusHistoryResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StatusHistoryResult
        /// </summary>
        [Fact]
        public void StatusHistoryResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" StatusHistoryResult
            //Assert.IsType<StatusHistoryResult>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'DateTime'
        /// </summary>
        [Fact]
        public void DateTimeTest()
        {
            // TODO unit test for the property 'DateTime'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
