/*
 * eID - RO HTTP API
 *
 * Регистър на овластяванията (РО)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RoSdk.Model;
using RoSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RoSdk.Test.Model
{
    /// <summary>
    ///  Class for testing UidAndUidTypeData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UidAndUidTypeDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UidAndUidTypeData
        //private UidAndUidTypeData instance;

        public UidAndUidTypeDataTests()
        {
            // TODO uncomment below to create an instance of UidAndUidTypeData
            //instance = new UidAndUidTypeData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UidAndUidTypeData
        /// </summary>
        [Fact]
        public void UidAndUidTypeDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" UidAndUidTypeData
            //Assert.IsType<UidAndUidTypeData>(instance);
        }

        /// <summary>
        /// Test the property 'Uid'
        /// </summary>
        [Fact]
        public void UidTest()
        {
            // TODO unit test for the property 'Uid'
        }

        /// <summary>
        /// Test the property 'UidType'
        /// </summary>
        [Fact]
        public void UidTypeTest()
        {
            // TODO unit test for the property 'UidType'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
