/*
 * eID - RO HTTP API
 *
 * Регистър на овластяванията (РО)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RoSdk.Model;
using RoSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RoSdk.Test.Model
{
    /// <summary>
    ///  Class for testing WithdrawEmpowermentRequestPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WithdrawEmpowermentRequestPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WithdrawEmpowermentRequestPayload
        //private WithdrawEmpowermentRequestPayload instance;

        public WithdrawEmpowermentRequestPayloadTests()
        {
            // TODO uncomment below to create an instance of WithdrawEmpowermentRequestPayload
            //instance = new WithdrawEmpowermentRequestPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WithdrawEmpowermentRequestPayload
        /// </summary>
        [Fact]
        public void WithdrawEmpowermentRequestPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" WithdrawEmpowermentRequestPayload
            //Assert.IsType<WithdrawEmpowermentRequestPayload>(instance);
        }

        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
    }
}
