/*
 * ISCEI HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import eid.sdk.iscei.ApiException;
import org.openapitools.client.model.AuthenticationRequestChallengeResponse;
import org.openapitools.client.model.BasicLoginRequestDto;
import org.openapitools.client.model.SignedChallenge;
import org.openapitools.client.model.VerifyOtpDto;
import org.openapitools.client.model.X509CertAuthenticationRequestDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CommonLoginControllerApi
 */
@Disabled
public class CommonLoginControllerApiTest {

    private final CommonLoginControllerApi api = new CommonLoginControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void associateEidWithCitizenProfileTest() throws ApiException {
        String clientId = null;
        SignedChallenge signedChallenge = null;
        api.associateEidWithCitizenProfile(clientId, signedChallenge);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void basicLoginTest() throws ApiException {
        BasicLoginRequestDto basicLoginRequestDto = null;
        Object response = api.basicLogin(basicLoginRequestDto);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateAuthenticationChallengeTest() throws ApiException {
        X509CertAuthenticationRequestDto x509CertAuthenticationRequestDto = null;
        AuthenticationRequestChallengeResponse response = api.generateAuthenticationChallenge(x509CertAuthenticationRequestDto);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifyOtpTest() throws ApiException {
        VerifyOtpDto verifyOtpDto = null;
        String response = api.verifyOtp(verifyOtpDto);
        // TODO: test validations
    }

}
