/*
 * ISCEI HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import eid.sdk.iscei.ApiException;
import org.openapitools.client.model.MobileSignedChallenge;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MobileControllerApi
 */
@Disabled
public class MobileControllerApiTest {

    private final MobileControllerApi api = new MobileControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void mobileX509CertificateLoginTest() throws ApiException {
        MobileSignedChallenge mobileSignedChallenge = null;
        String response = api.mobileX509CertificateLogin(mobileSignedChallenge);
        // TODO: test validations
    }

}
