schemas:
  ApplicationSubmissionType:
    type: string
    x-field-extra-annotation: '@jakarta.validation.constraints.NotNull(message = bg.bulsi.mvr.common.exception.ErrorCode.Fields.APPLICATION_SUBMISSION_TYPE_CANNOT_BE_NULL)'
    enum:
      - DESK
      - BASE_PROFILE
#    todo check if renaming of EID is needed
      - EID
      - PERSO_CENTRE