schemas:
  ApplicationResponse:
    type: object
    properties:
      id:
        type: string
        format: uuid
      applicationNumber:
        type: string
      status:
        $ref: './application_status_v1.yaml#/schemas/ApplicationStatus'
      eidAdministratorName:
        type: string
      fee:
        type: number
        format: double
      feeCurrency:
        type: string
      secondaryFee:
        type: number
        format: double
      secondaryFeeCurrency:
        type: string