schemas:
  ApplicationDetailsExternalResponse:
    type: object
    properties:
      id:
        type: string
        format: uuid
      firstName:
        type: string
      secondName:
        type: string
      lastName:
        type: string
      applicationType:
        $ref: './application_type_v1.yaml#/schemas/ApplicationType'
      certificateId:
        type: string
        format: uuid
      serialNumber:
        type: string
      status:
        $ref: './application_status_v1.yaml#/schemas/ApplicationStatus'
      createDate:
        type: string
        format: date-time
        description: Certificate created date
      deviceId:
        type: string
        format: uuid
      eidAdministratorName:
        type: string
      eidAdministratorOfficeName:
        type: string
      eidAdministratorFrontOfficeId:
        type: string
        format: uuid
      eidentityId:
        type: string
        format: uuid
      email:
        type: string
      phoneNumber:
        type: string
      reasonId:
        type: string
        format: uuid
      reasonText:
        type: string
      xml:
        type: string
      submissionType:
        $ref: './application_submission_type_v1.yaml#/schemas/ApplicationSubmissionType'
      identityNumber:
        type: string
      identityType:
        type: string
      identityIssueDate:
        type: string
        format: date
      identityValidityToDate:
        type: string
        format: date
      applicationNumber:
        type: string
      paymentAccessCode:
        type: string