/*
 * eID - PAN Public HTTP API
 *
 * Подсистема за автоматични нотификации (ПАН) Публична
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PanSdk.Model;
using PanSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PanSdk.Test.Model
{
    /// <summary>
    ///  Class for testing RegisteredSystemTranslationResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RegisteredSystemTranslationResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RegisteredSystemTranslationResult
        //private RegisteredSystemTranslationResult instance;

        public RegisteredSystemTranslationResultTests()
        {
            // TODO uncomment below to create an instance of RegisteredSystemTranslationResult
            //instance = new RegisteredSystemTranslationResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RegisteredSystemTranslationResult
        /// </summary>
        [Fact]
        public void RegisteredSystemTranslationResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" RegisteredSystemTranslationResult
            //Assert.IsType<RegisteredSystemTranslationResult>(instance);
        }

        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
