/*
 * eID - PAN Public HTTP API
 *
 * Подсистема за автоматични нотификации (ПАН) Публична
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PanSdk.Model;
using PanSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PanSdk.Test.Model
{
    /// <summary>
    ///  Class for testing RegisteredSystemResultIPaginatedData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RegisteredSystemResultIPaginatedDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RegisteredSystemResultIPaginatedData
        //private RegisteredSystemResultIPaginatedData instance;

        public RegisteredSystemResultIPaginatedDataTests()
        {
            // TODO uncomment below to create an instance of RegisteredSystemResultIPaginatedData
            //instance = new RegisteredSystemResultIPaginatedData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RegisteredSystemResultIPaginatedData
        /// </summary>
        [Fact]
        public void RegisteredSystemResultIPaginatedDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" RegisteredSystemResultIPaginatedData
            //Assert.IsType<RegisteredSystemResultIPaginatedData>(instance);
        }

        /// <summary>
        /// Test the property 'PageIndex'
        /// </summary>
        [Fact]
        public void PageIndexTest()
        {
            // TODO unit test for the property 'PageIndex'
        }

        /// <summary>
        /// Test the property 'TotalItems'
        /// </summary>
        [Fact]
        public void TotalItemsTest()
        {
            // TODO unit test for the property 'TotalItems'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
