/*
 * eID - PAN Public HTTP API
 *
 * Подсистема за автоматични нотификации (ПАН) Публична
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PanSdk.Model;
using PanSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PanSdk.Test.Model
{
    /// <summary>
    ///  Class for testing TranslationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TranslationRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TranslationRequest
        //private TranslationRequest instance;

        public TranslationRequestTests()
        {
            // TODO uncomment below to create an instance of TranslationRequest
            //instance = new TranslationRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TranslationRequest
        /// </summary>
        [Fact]
        public void TranslationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" TranslationRequest
            //Assert.IsType<TranslationRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }

        /// <summary>
        /// Test the property 'ShortDescription'
        /// </summary>
        [Fact]
        public void ShortDescriptionTest()
        {
            // TODO unit test for the property 'ShortDescription'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
    }
}
