/*
 * eID - RO HTTP API
 * Регистър на овластяванията (РО)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import eid.sdk.ro.JSON;

/**
 * Approve Unconfirmed empowerment by DEAU
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-11T17:57:54.980305500+03:00[Europe/Kiev]", comments = "Generator version: 7.13.0")
public class ApproveEmpowermentByDeauRequest {
  public static final String SERIALIZED_NAME_EMPOWERMENT_ID = "empowermentId";
  @SerializedName(SERIALIZED_NAME_EMPOWERMENT_ID)
  @javax.annotation.Nullable
  private UUID empowermentId;

  public ApproveEmpowermentByDeauRequest() {
  }

  public ApproveEmpowermentByDeauRequest empowermentId(@javax.annotation.Nullable UUID empowermentId) {
    this.empowermentId = empowermentId;
    return this;
  }

  /**
   * EmpowermentId : the unconfirmed empowerment to approve
   * @return empowermentId
   */
  @javax.annotation.Nullable
  public UUID getEmpowermentId() {
    return empowermentId;
  }

  public void setEmpowermentId(@javax.annotation.Nullable UUID empowermentId) {
    this.empowermentId = empowermentId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApproveEmpowermentByDeauRequest approveEmpowermentByDeauRequest = (ApproveEmpowermentByDeauRequest) o;
    return Objects.equals(this.empowermentId, approveEmpowermentByDeauRequest.empowermentId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(empowermentId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApproveEmpowermentByDeauRequest {\n");
    sb.append("    empowermentId: ").append(toIndentedString(empowermentId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("empowermentId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ApproveEmpowermentByDeauRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ApproveEmpowermentByDeauRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ApproveEmpowermentByDeauRequest is not found in the empty JSON string", ApproveEmpowermentByDeauRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ApproveEmpowermentByDeauRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ApproveEmpowermentByDeauRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("empowermentId") != null && !jsonObj.get("empowermentId").isJsonNull()) && !jsonObj.get("empowermentId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `empowermentId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("empowermentId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ApproveEmpowermentByDeauRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ApproveEmpowermentByDeauRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ApproveEmpowermentByDeauRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ApproveEmpowermentByDeauRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<ApproveEmpowermentByDeauRequest>() {
           @Override
           public void write(JsonWriter out, ApproveEmpowermentByDeauRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ApproveEmpowermentByDeauRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ApproveEmpowermentByDeauRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ApproveEmpowermentByDeauRequest
   * @throws IOException if the JSON string is invalid with respect to ApproveEmpowermentByDeauRequest
   */
  public static ApproveEmpowermentByDeauRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ApproveEmpowermentByDeauRequest.class);
  }

  /**
   * Convert an instance of ApproveEmpowermentByDeauRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

