/*
 * eID - RO HTTP API
 * Регистър на овластяванията (РО)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets LanguageType
 */
@JsonAdapter(LanguageType.Adapter.class)
public enum LanguageType {
  
  BG("Bg"),
  
  EN("En");

  private String value;

  LanguageType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static LanguageType fromValue(String value) {
    for (LanguageType b : LanguageType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<LanguageType> {
    @Override
    public void write(final JsonWriter jsonWriter, final LanguageType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public LanguageType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return LanguageType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    LanguageType.fromValue(value);
  }
}

