spring:
  rabbitmq:
    listener:
      simple:
        concurrency: 3
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
custom:
  rabbitmq:
    queue-prefix: raeicei.rpcqueue.
    management:
      port:
    listener:
      dispatcher: bg.bulsi.mvr.raeicei.backend.rabbitmq.ListenerDispatcher
