methods:
  put:
    tags:
      - ChangeApplicationStatus
    summary: Change Application Status
    operationId: changeApplicationStatus
    parameters:
      - name: id
        in: path
        description: 'Id'
        required: true
        schema:
          type: string
          format: uuid
      - name: applicationStatus
        in: query
        description: 'New Application Status'
        required: true
        schema:
          $ref: '../../components/application/application_status_v1.yaml#/schemas/ApplicationStatus'
      - name: code
        in: query
        description: 'code'
        required: false
        schema:
          type: string
    requestBody:
      required: true
      content:
        application/json;charset=UTF-8:
          schema:
            $ref: '../../components/common/note_documents.yaml#/schemas/NoteAndDocumentsDTO'
    responses:
      '200':
        description: Success
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/http_response_v1.yaml#/schemas/HttpResponse'
      '400':
        description: Bad Request
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/validation_problem_details_v1.yaml#/schemas/ValidationProblemDetailsDTO'
      '404':
        description: Not Found
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/problem_details_v1.yaml#/schemas/ProblemDetailsDTO'
      '409':
        description: Conflict
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/problem_details_v1.yaml#/schemas/ProblemDetailsDTO'
      '500':
        description: Server Error
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/problem_details_v1.yaml#/schemas/ProblemDetailsDTO'
      '504':
        description: Time Out
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/problem_details_v1.yaml#/schemas/ProblemDetailsDTO'