methods:
  get:
    tags:
      - ChangeApplicationStatus
    summary: Get Documents Notes For Application
    operationId: getDocumentsNotesForApplication
    parameters:
      - name: id
        in: path
        description: 'Id'
        required: true
        schema:
          type: string
          format: uuid
    responses:
      '200':
        description: Success
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/EidAdministrator/documents-notes.yaml#/schemas/DocumentNoteDTO'
      '400':
        description: Bad Request
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/validation_problem_details_v1.yaml#/schemas/ValidationProblemDetailsDTO'
      '404':
        description: Not Found
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/problem_details_v1.yaml#/schemas/ProblemDetailsDTO'
      '500':
        description: Server Error
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/problem_details_v1.yaml#/schemas/ProblemDetailsDTO'
      '504':
        description: Time Out
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/problem_details_v1.yaml#/schemas/ProblemDetailsDTO'