methods:
  post:
    summary: Add guardians to application
    operationId: addGuardiansToApplication
    tags:
      - Application
    parameters:
      - name: applicationId
        in: path
        description: 'Application ID'
        required: true
        schema:
          type: string
          format: uuid
    requestBody:
      required: true
      content:
        application/json;charset=UTF-8:
          schema:
            $ref: '../../components/application/application_add_guardians_v1.yaml#/schemas/ApplicationAddGuardiansRequest'
    responses:
      '200':
        description: Success
        content:
          application/json;charset=UTF-8:
            schema:
              type: string
      '400':
        description: Bad Request
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/validation_problem_details_v1.yaml#/schemas/ValidationProblemDetails'
      '404':
        description: Not Found
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/problem_details_v1.yaml#/schemas/ProblemDetails'
      '409':
        description: Conflict
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/problem_details_v1.yaml#/schemas/ProblemDetails'
      '500':
        description: Server Error
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/problem_details_v1.yaml#/schemas/ProblemDetails'
      '504':
        description: Time Out
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/problem_details_v1.yaml#/schemas/ProblemDetails'