<?php
/**
 * NotificationsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  PanSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eID - PAN Public HTTP API
 *
 * Подсистема за автоматични нотификации (ПАН) Публична
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace PanSdk\Test\Api;

use \PanSdk\Configuration;
use \PanSdk\ApiException;
use \PanSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * NotificationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  PanSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NotificationsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV1NotificationsDeactivatePost
     *
     * Register deactivated user events.
     *
     */
    public function testApiV1NotificationsDeactivatePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1NotificationsDeactivatedGet
     *
     * Get deactivated user notifications.
     *
     */
    public function testApiV1NotificationsDeactivatedGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1NotificationsGet
     *
     * Get all Systems and notifications.
     *
     */
    public function testApiV1NotificationsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for registerOrUpdateSystemAsync
     *
     * Register or update a system with its events..
     *
     */
    public function testRegisterOrUpdateSystemAsync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendNotificationAsync
     *
     * Send notification to a user via users' selected channels or fallback to default(SMTP) channel..
     *
     */
    public function testSendNotificationAsync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
