/*
 * eID - RO HTTP API
 *
 * Регистър на овластяванията (РО)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = RoSdk.Client.FileParameter;
using OpenAPIDateConverter = RoSdk.Client.OpenAPIDateConverter;

namespace RoSdk.Model
{
    /// <summary>
    /// Defines EmpowermentsByEikFilterStatus
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum EmpowermentsByEikFilterStatus
    {
        /// <summary>
        /// Enum Created for value: Created
        /// </summary>
        [EnumMember(Value = "Created")]
        Created = 1,

        /// <summary>
        /// Enum CollectingAuthorizerSignatures for value: CollectingAuthorizerSignatures
        /// </summary>
        [EnumMember(Value = "CollectingAuthorizerSignatures")]
        CollectingAuthorizerSignatures = 2,

        /// <summary>
        /// Enum Active for value: Active
        /// </summary>
        [EnumMember(Value = "Active")]
        Active = 3,

        /// <summary>
        /// Enum Denied for value: Denied
        /// </summary>
        [EnumMember(Value = "Denied")]
        Denied = 4,

        /// <summary>
        /// Enum DisagreementDeclared for value: DisagreementDeclared
        /// </summary>
        [EnumMember(Value = "DisagreementDeclared")]
        DisagreementDeclared = 5,

        /// <summary>
        /// Enum Withdrawn for value: Withdrawn
        /// </summary>
        [EnumMember(Value = "Withdrawn")]
        Withdrawn = 6,

        /// <summary>
        /// Enum Expired for value: Expired
        /// </summary>
        [EnumMember(Value = "Expired")]
        Expired = 7,

        /// <summary>
        /// Enum Unconfirmed for value: Unconfirmed
        /// </summary>
        [EnumMember(Value = "Unconfirmed")]
        Unconfirmed = 8
    }

}
