/*
 * eID - RO HTTP API
 *
 * Регистър на овластяванията (РО)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = RoSdk.Client.FileParameter;
using OpenAPIDateConverter = RoSdk.Client.OpenAPIDateConverter;

namespace RoSdk.Model
{
    /// <summary>
    /// Defines EmpowermentsToMeFilterStatus
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum EmpowermentsToMeFilterStatus
    {
        /// <summary>
        /// Enum Active for value: Active
        /// </summary>
        [EnumMember(Value = "Active")]
        Active = 1,

        /// <summary>
        /// Enum Denied for value: Denied
        /// </summary>
        [EnumMember(Value = "Denied")]
        Denied = 2,

        /// <summary>
        /// Enum DisagreementDeclared for value: DisagreementDeclared
        /// </summary>
        [EnumMember(Value = "DisagreementDeclared")]
        DisagreementDeclared = 3,

        /// <summary>
        /// Enum Withdrawn for value: Withdrawn
        /// </summary>
        [EnumMember(Value = "Withdrawn")]
        Withdrawn = 4,

        /// <summary>
        /// Enum Expired for value: Expired
        /// </summary>
        [EnumMember(Value = "Expired")]
        Expired = 5,

        /// <summary>
        /// Enum Unconfirmed for value: Unconfirmed
        /// </summary>
        [EnumMember(Value = "Unconfirmed")]
        Unconfirmed = 6
    }

}
