package com.digitall.eid.models.empowerment.common.details

import com.digitall.eid.R
import com.digitall.eid.domain.models.base.TypeEnum
import com.digitall.eid.models.common.StringSource

enum class EmpowermentDenialReasonEnum(
    override val type: String,
    val title: StringSource
) : TypeEnum {

    NONE("None", StringSource("")),
    DECEASED_UID(
        "DeceasedUid",
        StringSource(R.string.empowerment_details_denial_reason_deceased_uid_enum_type)
    ),
    PROHIBITED_UID(
        "ProhibitedUid",
        StringSource(R.string.empowerment_details_denial_reason_prohibited_uid_enum_type)
    ),
    NTR_CHECK_FAILED(
        "NTRCheckFailed",
        StringSource(R.string.empowerment_details_denial_reason_ntr_check_failed_enum_type)
    ),
    TIMED_OUT(
        "TimedOut",
        StringSource(R.string.empowerment_details_denial_reason_timed_out_enum_type)
    ),
    BELOW_LAWFUL_AGE(
        "BelowLawfulAge",
        StringSource(R.string.empowerment_details_denial_reason_below_lawful_age_enum_type)
    ),
    NO_PERMIT(
        "NoPermit",
        StringSource(R.string.empowerment_details_denial_reason_no_permit_enum_type)
    ),
    LAWFUL_AGE_INFO_NOT_AVAILABLE(
        "LawfulAgeInfoNotAvailable",
        StringSource(R.string.empowerment_details_denial_reason_lawful_age_info_not_available_enum_type)
    ),
    UNSUCCESSFUL_RESTRICTIONS_CHECK(
        "UnsuccessfulRestrictionsCheck",
        StringSource(R.string.empowerment_details_denial_reason_unsuccessful_restrictions_check_enum_type)
    ),
    LEGAL_ENTITY_NOT_ACTIVE(
        "LegalEntityNotActive",
        StringSource(R.string.empowerment_details_denial_reason_legal_entity_not_active_enum_type)
    ),
    LEGAL_ENTITY_REPRESENTATION_NOT_MATCH(
        "LegalEntityRepresentationNotMatch",
        StringSource(R.string.empowerment_details_denial_reason_legal_entity_representation_not_match_enum_type)
    ),
    UNSUCCESSFUL_LEGAL_ENTITY_CHECK(
        "UnsuccessfulLegalEntityCheck",
        StringSource(R.string.empowerment_details_denial_reason_unsuccessful_legal_entity_check_enum_type)
    ),
    EMPOWERMENT_STATEMENT_NOT_FOUND(
        "EmpowermentStatementNotFound",
        StringSource(R.string.empowerment_details_denial_reason_empowerment_statement_not_found_enum_type)
    ),
    BULSTAT_CHECK_FAILED(
        "BulstatCheckFailed",
        StringSource(R.string.empowerment_details_denial_reason_bulstat_check_failed_enum_type)
    ),
    REREGISTERED_IN_NTR(
        "ReregisteredInNTR",
        StringSource(R.string.empowerment_details_denial_reason_reregistered_in_ntr_enum_type)
    ),
    ARCHIVED_IN_BULSTAT(
        "ArchivedInBulstat",
        StringSource(R.string.empowerment_details_denial_reason_archived_in_bulstat_enum_type)
    ),
    IN_INSOLVENCY_PROCEEDINGS_IN_BULSTAT(
        "InInsolvencyProceedingsInBulstat",
        StringSource(R.string.empowerment_details_denial_reason_in_insolvency_proceedings_in_bulstat_enum_type)
    ),
    INSOLVENT_IN_BULSTAT(
        "InsolventInBulstat",
        StringSource(R.string.empowerment_details_denial_reason_insolvent_in_bulstat_enum_type)
    ),
    IN_LIQUIDATION_IN_BULSTAT(
        "InLiquidationInBulstat",
        StringSource(R.string.empowerment_details_denial_reason_in_liquidation_in_bulstat_enum_type)
    ),
    INACTIVE_IN_BULSTAT(
        "InactiveInBulstat",
        StringSource(R.string.empowerment_details_denial_reason_inactive_in_bulstat_enum_type)
    ),
    CLOSED_IN_BULSTAT(
        "ClosedInBulstat",
        StringSource(R.string.empowerment_details_denial_reason_closed_in_bulstat_enum_type)
    ),
    TERMINATED_THROUGH_MERGER_IN_BULSTAT(
        "TerminatedThroughMergerInBulstat",
        StringSource(R.string.empowerment_details_denial_reason_terminated_through_merger_in_bulstat_enum_type)
    ),
    TERMINATED_THROUGH_INCORPORATION_IN_BULSTAT(
        "TerminatedThroughIncorporationInBulstat",
        StringSource(R.string.empowerment_details_denial_reason_terminated_through_incorporation_in_bulstat_enum_type)
    ),
    TERMINATED_THROUGH_DIVISION_IN_BULSTAT(
        "TerminatedThroughDivisionInBulstat",
        StringSource(R.string.empowerment_details_denial_reason_terminated_through_division_in_bulstat_enum_type)
    ),
    DELETED_FROM_JUDICIAL_REGISTER(
        "DeletedFromJudicialRegister",
        StringSource(R.string.empowerment_details_denial_reason_deleted_from_judicial_register_enum_type)
    ),
    DELETED_FROM_BTPP_REGISTER(
        "DeletedFromBTPPRegister",
        StringSource(R.string.empowerment_details_denial_reason_deleted_from_btpp_register_enum_type)
    ),
    REGISTRATION_ANNULLED_IN_BULSTAT(
        "RegistrationAnnulledInBulstat",
        StringSource(R.string.empowerment_details_denial_reason_registration_annulled_in_bulstat_enum_type)
    ),
    TERMINATED_DUE_TO_ENTERPRISE_TRANSACTION_IN_BULSTAT(
        "TerminatedDueToEnterpriseTransactionInBulstat",
        StringSource(R.string.empowerment_details_denial_reason_terminated_due_to_enterprise_transaction_in_bulstat_enum_type)
    ),
    DEREGISTERED_IN_BULSTAT(
        "DeregisteredInBulstat",
        StringSource(R.string.empowerment_details_denial_reason_deregistered_in_bulstat_enum_type)
    ),
    UNSUCCESSFUL_TIMESTAMPING(
        "UNSUCCESSFUL_TIMESTAMPING",
        StringSource(R.string.empowerment_details_denial_reason_unsuccessful_timestamping_enum_type)
    ),
    SIGNATURE_COLLECTION_TIME_OUT(
        "SignatureCollectionTimeOut",
        StringSource(R.string.empowerment_details_denial_reason_signature_collection_time_out_enum_type)
    ),
    DENIED_BY_DEAU_ADMINISTRATOR(
        "DeniedByDeauAdministrator",
        StringSource(R.string.empowerment_details_denial_reason_denied_by_deau_administrator_enum_type)
    ),
    INVALID_UID_REGISTRATION_STATUS_DETECTED(
        "InvalidUidRegistrationStatusDetected",
        StringSource(R.string.empowerment_details_denial_reason_invalid_uid_registration_status_detected_enum_type)
    ),
    UIDS_REGISTRATION_STATUS_INFO_NOT_AVAILABLE(
        "UidsRegistrationStatusInfoNotAvailable",
        StringSource(R.string.empowerment_details_denial_reason_uids_registration_status_info_not_available_enum_type)
    ),
    REGISTRATION_STATUS_UNAVAILABLE(
        "RegistrationStatusUnavailable",
        StringSource(R.string.empowerment_details_denial_reason_registration_status_unavailable_enum_type)
    ),
    INACTIVE_PROFILE(
        "InactiveProfile",
        StringSource(R.string.empowerment_details_denial_reason_inactive_profile_enum_type)
    ),
    NO_BASE_PROFILE(
        "NoBaseProfile",
        StringSource(R.string.empowerment_details_denial_reason_no_base_profile_enum_type)
    ),
    NAME_MISMATCH(
        "NameMismatch",
        StringSource(R.string.empowerment_details_denial_reason_name_mismatch_enum_type)
    ),
    NO_REGISTRATION(
        "NoRegistration",
        StringSource(R.string.empowerment_details_denial_reason_no_registration_enum_type)
    )
}