namespace eID.PAN.Contracts;

public enum LogEventCode
{
    None = 0,
    SEND_EMAIL = 1,
    UPDATE_SMTP_CONFIGURATION = 3,
    MODIFY_NOTIFICATION_CHANNEL = 4,
    REGISTER_NOTIFICATION_CHANNEL = 6,
    APPROVE_NOTIFICATION_CHANNEL = 7,
    REJECT_NOTIFICATION_CHANNEL = 8,
    ARCHIVE_NOTIFICATION_CHANNEL = 9,
    RESTORE_NOTIFICATION_CHANNEL = 10,
    REGISTER_SYSTEM = 13,
    MODIFY_EVENT = 15,
    REGISTER_USER_NOTIFICATION_CHANNELS = 18,
    GET_DEACTIVATED_USER_NOTIFICATIONS = 20,
    REJECT_SYSTEM = 21,
    APPROVE_SYSTEM = 22,
    ARCHIVE_SYSTEM = 23,
    RESTORE_SYSTEM = 24,
    SEND_SMS = 26,
    SEND_NOTIFICATION = 27,
    CREATE_SMTP_CONFIGURATION = 29,
    DELETE_SMTP_CONFIGURATION = 30,
    DEACTIVATE_USER_NOTIFICATIONS = 32,
    SEND_PUSH_NOTIFICATION = 33,
    SEND_DIRECT_EMAIL = 34,
    TEST_NOTIFICATION_CHANNEL = 35
}
