namespace eID.PAN.Contracts;

public enum LogEventCode
{
    None = 0,
    SendEmail = 10,
    GetSmtpConfigurationById = 20,
    UpdateSmtpConfiguration = 30,
    ModifyNotificationChannel = 40,
    GetAllNotificationChannels = 50,
    RegisterNotificationChannel = 60,
    ApproveNotificationChannel = 70,
    RejectNotificationChannel = 80,
    ArchiveNotificationChannel = 90,
    RestoreNotificationChannel = 100,
    GetNotificationsByFilter = 110,
    GetSystemById = 120,
    RegisterSystem = 130,
    ModifyEvent = 150,
    GetUserNotificationChannelsByFilter = 160,
    GetUserNotificationChannels = 170,
    RegisterUserNotificationChannels = 180,
    GetUserNotificationsByFilter = 190,
    GetDeactivatedUserNotifications = 200,
    RejectSystem = 210,
    ApproveSystem = 220,
    ArchiveSystem = 230,
    RestoreSystem = 240,
    GetRegisteredSystemsRejected = 250,
    SendSms = 260,
    SendNotification = 270,
    GetSmtpConfigurationsByFilter = 280,
    CreateSmtpConfiguration = 290,
    DeleteSmtpConfiguration = 300,
    GetSystemsByFilter = 310,
    DeactivateUserNotifications = 320,
    SendPushNotification = 321,
    SendDirectEmail = 330
}
