//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.09 at 10:28:18 AM EEST 
//


package bg.bulsi.mvr.mpozei.model.pivr;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import javax.xml.datatype.XMLGregorianCalendar;

import bg.bulsi.mvr.mpozei.model.pivr.common.BirthPlace;
import bg.bulsi.mvr.mpozei.model.pivr.common.Nationality;
import bg.bulsi.mvr.mpozei.model.pivr.common.PersonNames;
import bg.bulsi.mvr.mpozei.model.pivr.common.ReturnInformation;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import lombok.Data;


/**
 * Документ за самоличност и пребиваване
 * 
 * <p>Java class for IdentityDocument complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IdentityDocument"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DocumentType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DocumentTypeLatin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IdentityDocumentNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IssueDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="IssuePlace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IssuePlaceLatin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IssuerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IssuerNameLatin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ValidDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="RPRemarks" type="{http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse}RPRemarkType" minOccurs="0"/&gt;
 *         &lt;element name="RPTypeOfPermit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="StatusReasonCyrillic" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *         &lt;element name="StatusDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="StatusCyrillic" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdentityDocument", propOrder = {
    "documentType",
    "documentTypeLatin",
    "identityDocumentNumber",
    "issueDate",
    "issuePlace",
    "issuePlaceLatin",
    "issuerName",
    "issuerNameLatin",
    "validDate",
    "rpRemarks",
    "rpTypeOfPermit",
    "statusReasonCyrillic",
    "statusDate",
    "statusCyrillic"
})
@Data
public class IdentityDocument {

    @XmlElement(name = "DocumentType")
    protected String documentType;
    @XmlElement(name = "DocumentTypeLatin")
    protected String documentTypeLatin;
    @XmlElement(name = "IdentityDocumentNumber")
    protected String identityDocumentNumber;
    @XmlElement(name = "IssueDate")
    @XmlSchemaType(name = "dateTime")
    protected LocalDate issueDate;
    @XmlElement(name = "IssuePlace")
    protected String issuePlace;
    @XmlElement(name = "IssuePlaceLatin")
    protected String issuePlaceLatin;
    @XmlElement(name = "IssuerName")
    protected String issuerName;
    @XmlElement(name = "IssuerNameLatin")
    protected String issuerNameLatin;
    @XmlElement(name = "ValidDate")
    @XmlSchemaType(name = "dateTime")
    protected LocalDate validDate;
    @XmlElement(name = "RPRemarks")
    protected List<String> rpRemarks;
    @XmlElement(name = "RPTypeOfPermit")
    protected String rpTypeOfPermit;
    @XmlElement(name = "StatusReasonCyrillic", required = true)
    protected Object statusReasonCyrillic;
    @XmlElement(name = "StatusDate", required = true)
    @XmlSchemaType(name = "date")
    protected LocalDate statusDate;
    @XmlElement(name = "StatusCyrillic", required = true)
    protected String statusCyrillic;

}
