/*
 * ISCEI HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IsceiSdk.Model;
using IsceiSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IsceiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing ApprovalRequestResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApprovalRequestResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApprovalRequestResponse
        //private ApprovalRequestResponse instance;

        public ApprovalRequestResponseTests()
        {
            // TODO uncomment below to create an instance of ApprovalRequestResponse
            //instance = new ApprovalRequestResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApprovalRequestResponse
        /// </summary>
        [Fact]
        public void ApprovalRequestResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApprovalRequestResponse
            //Assert.IsType<ApprovalRequestResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

        /// <summary>
        /// Test the property 'LevelOfAssurance'
        /// </summary>
        [Fact]
        public void LevelOfAssuranceTest()
        {
            // TODO unit test for the property 'LevelOfAssurance'
        }

        /// <summary>
        /// Test the property 'RequestFrom'
        /// </summary>
        [Fact]
        public void RequestFromTest()
        {
            // TODO unit test for the property 'RequestFrom'
        }

        /// <summary>
        /// Test the property 'CreateDate'
        /// </summary>
        [Fact]
        public void CreateDateTest()
        {
            // TODO unit test for the property 'CreateDate'
        }

        /// <summary>
        /// Test the property 'MaxTtl'
        /// </summary>
        [Fact]
        public void MaxTtlTest()
        {
            // TODO unit test for the property 'MaxTtl'
        }

        /// <summary>
        /// Test the property 'ExpiresIn'
        /// </summary>
        [Fact]
        public void ExpiresInTest()
        {
            // TODO unit test for the property 'ExpiresIn'
        }
    }
}
