<?php
/**
 * EmpowermentStatementResult
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  RoSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eID - RO HTTP API
 *
 * Регистър на овластяванията (РО)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace RoSdk\Model;

use \ArrayAccess;
use \RoSdk\ObjectSerializer;

/**
 * EmpowermentStatementResult Class Doc Comment
 *
 * @category Class
 * @package  RoSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EmpowermentStatementResult implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'EmpowermentStatementResult';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'number' => 'string',
        'start_date' => '\DateTime',
        'expiry_date' => '\DateTime',
        'status' => '\RoSdk\Model\EmpowermentStatementStatus',
        'uid' => 'string',
        'uid_type' => '\RoSdk\Model\IdentifierType',
        'name' => 'string',
        'on_behalf_of' => '\RoSdk\Model\OnBehalfOf',
        'authorizer_uids' => '\RoSdk\Model\UidResult[]',
        'empowered_uids' => '\RoSdk\Model\UidResult[]',
        'provider_id' => 'string',
        'provider_name' => 'string',
        'service_id' => 'int',
        'service_name' => 'string',
        'volume_of_representation' => '\RoSdk\Model\VolumeOfRepresentationResult[]',
        'created_on' => '\DateTime',
        'created_by' => 'string',
        'issuer_position' => 'string',
        'xml_representation' => 'string',
        'denial_reason' => '\RoSdk\Model\EmpowermentsDenialReason',
        'empowerment_withdrawals' => '\RoSdk\Model\EmpowermentWithdrawResult[]',
        'empowerment_disagreements' => '\RoSdk\Model\EmpowermentDisagreementResult[]',
        'status_history' => '\RoSdk\Model\StatusHistoryResult[]',
        'calculated_status_on' => '\RoSdk\Model\CalculatedEmpowermentStatus'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'number' => null,
        'start_date' => 'date-time',
        'expiry_date' => 'date-time',
        'status' => null,
        'uid' => null,
        'uid_type' => null,
        'name' => null,
        'on_behalf_of' => null,
        'authorizer_uids' => null,
        'empowered_uids' => null,
        'provider_id' => null,
        'provider_name' => null,
        'service_id' => 'int32',
        'service_name' => null,
        'volume_of_representation' => null,
        'created_on' => 'date-time',
        'created_by' => null,
        'issuer_position' => null,
        'xml_representation' => null,
        'denial_reason' => null,
        'empowerment_withdrawals' => null,
        'empowerment_disagreements' => null,
        'status_history' => null,
        'calculated_status_on' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'number' => true,
        'start_date' => false,
        'expiry_date' => true,
        'status' => false,
        'uid' => true,
        'uid_type' => false,
        'name' => true,
        'on_behalf_of' => false,
        'authorizer_uids' => true,
        'empowered_uids' => true,
        'provider_id' => true,
        'provider_name' => true,
        'service_id' => false,
        'service_name' => true,
        'volume_of_representation' => true,
        'created_on' => true,
        'created_by' => true,
        'issuer_position' => true,
        'xml_representation' => true,
        'denial_reason' => false,
        'empowerment_withdrawals' => true,
        'empowerment_disagreements' => true,
        'status_history' => true,
        'calculated_status_on' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'number' => 'number',
        'start_date' => 'startDate',
        'expiry_date' => 'expiryDate',
        'status' => 'status',
        'uid' => 'uid',
        'uid_type' => 'uidType',
        'name' => 'name',
        'on_behalf_of' => 'onBehalfOf',
        'authorizer_uids' => 'authorizerUids',
        'empowered_uids' => 'empoweredUids',
        'provider_id' => 'providerId',
        'provider_name' => 'providerName',
        'service_id' => 'serviceId',
        'service_name' => 'serviceName',
        'volume_of_representation' => 'volumeOfRepresentation',
        'created_on' => 'createdOn',
        'created_by' => 'createdBy',
        'issuer_position' => 'issuerPosition',
        'xml_representation' => 'xmlRepresentation',
        'denial_reason' => 'denialReason',
        'empowerment_withdrawals' => 'empowermentWithdrawals',
        'empowerment_disagreements' => 'empowermentDisagreements',
        'status_history' => 'statusHistory',
        'calculated_status_on' => 'calculatedStatusOn'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'number' => 'setNumber',
        'start_date' => 'setStartDate',
        'expiry_date' => 'setExpiryDate',
        'status' => 'setStatus',
        'uid' => 'setUid',
        'uid_type' => 'setUidType',
        'name' => 'setName',
        'on_behalf_of' => 'setOnBehalfOf',
        'authorizer_uids' => 'setAuthorizerUids',
        'empowered_uids' => 'setEmpoweredUids',
        'provider_id' => 'setProviderId',
        'provider_name' => 'setProviderName',
        'service_id' => 'setServiceId',
        'service_name' => 'setServiceName',
        'volume_of_representation' => 'setVolumeOfRepresentation',
        'created_on' => 'setCreatedOn',
        'created_by' => 'setCreatedBy',
        'issuer_position' => 'setIssuerPosition',
        'xml_representation' => 'setXmlRepresentation',
        'denial_reason' => 'setDenialReason',
        'empowerment_withdrawals' => 'setEmpowermentWithdrawals',
        'empowerment_disagreements' => 'setEmpowermentDisagreements',
        'status_history' => 'setStatusHistory',
        'calculated_status_on' => 'setCalculatedStatusOn'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'number' => 'getNumber',
        'start_date' => 'getStartDate',
        'expiry_date' => 'getExpiryDate',
        'status' => 'getStatus',
        'uid' => 'getUid',
        'uid_type' => 'getUidType',
        'name' => 'getName',
        'on_behalf_of' => 'getOnBehalfOf',
        'authorizer_uids' => 'getAuthorizerUids',
        'empowered_uids' => 'getEmpoweredUids',
        'provider_id' => 'getProviderId',
        'provider_name' => 'getProviderName',
        'service_id' => 'getServiceId',
        'service_name' => 'getServiceName',
        'volume_of_representation' => 'getVolumeOfRepresentation',
        'created_on' => 'getCreatedOn',
        'created_by' => 'getCreatedBy',
        'issuer_position' => 'getIssuerPosition',
        'xml_representation' => 'getXmlRepresentation',
        'denial_reason' => 'getDenialReason',
        'empowerment_withdrawals' => 'getEmpowermentWithdrawals',
        'empowerment_disagreements' => 'getEmpowermentDisagreements',
        'status_history' => 'getStatusHistory',
        'calculated_status_on' => 'getCalculatedStatusOn'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('number', $data ?? [], null);
        $this->setIfExists('start_date', $data ?? [], null);
        $this->setIfExists('expiry_date', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('uid', $data ?? [], null);
        $this->setIfExists('uid_type', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('on_behalf_of', $data ?? [], null);
        $this->setIfExists('authorizer_uids', $data ?? [], null);
        $this->setIfExists('empowered_uids', $data ?? [], null);
        $this->setIfExists('provider_id', $data ?? [], null);
        $this->setIfExists('provider_name', $data ?? [], null);
        $this->setIfExists('service_id', $data ?? [], null);
        $this->setIfExists('service_name', $data ?? [], null);
        $this->setIfExists('volume_of_representation', $data ?? [], null);
        $this->setIfExists('created_on', $data ?? [], null);
        $this->setIfExists('created_by', $data ?? [], null);
        $this->setIfExists('issuer_position', $data ?? [], null);
        $this->setIfExists('xml_representation', $data ?? [], null);
        $this->setIfExists('denial_reason', $data ?? [], null);
        $this->setIfExists('empowerment_withdrawals', $data ?? [], null);
        $this->setIfExists('empowerment_disagreements', $data ?? [], null);
        $this->setIfExists('status_history', $data ?? [], null);
        $this->setIfExists('calculated_status_on', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets number
     *
     * @return string|null
     */
    public function getNumber()
    {
        return $this->container['number'];
    }

    /**
     * Sets number
     *
     * @param string|null $number number
     *
     * @return self
     */
    public function setNumber($number)
    {
        if (is_null($number)) {
            array_push($this->openAPINullablesSetToNull, 'number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['number'] = $number;

        return $this;
    }

    /**
     * Gets start_date
     *
     * @return \DateTime|null
     */
    public function getStartDate()
    {
        return $this->container['start_date'];
    }

    /**
     * Sets start_date
     *
     * @param \DateTime|null $start_date start_date
     *
     * @return self
     */
    public function setStartDate($start_date)
    {
        if (is_null($start_date)) {
            throw new \InvalidArgumentException('non-nullable start_date cannot be null');
        }
        $this->container['start_date'] = $start_date;

        return $this;
    }

    /**
     * Gets expiry_date
     *
     * @return \DateTime|null
     */
    public function getExpiryDate()
    {
        return $this->container['expiry_date'];
    }

    /**
     * Sets expiry_date
     *
     * @param \DateTime|null $expiry_date expiry_date
     *
     * @return self
     */
    public function setExpiryDate($expiry_date)
    {
        if (is_null($expiry_date)) {
            array_push($this->openAPINullablesSetToNull, 'expiry_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('expiry_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['expiry_date'] = $expiry_date;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \RoSdk\Model\EmpowermentStatementStatus|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \RoSdk\Model\EmpowermentStatementStatus|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets uid
     *
     * @return string|null
     */
    public function getUid()
    {
        return $this->container['uid'];
    }

    /**
     * Sets uid
     *
     * @param string|null $uid uid
     *
     * @return self
     */
    public function setUid($uid)
    {
        if (is_null($uid)) {
            array_push($this->openAPINullablesSetToNull, 'uid');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('uid', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['uid'] = $uid;

        return $this;
    }

    /**
     * Gets uid_type
     *
     * @return \RoSdk\Model\IdentifierType|null
     */
    public function getUidType()
    {
        return $this->container['uid_type'];
    }

    /**
     * Sets uid_type
     *
     * @param \RoSdk\Model\IdentifierType|null $uid_type uid_type
     *
     * @return self
     */
    public function setUidType($uid_type)
    {
        if (is_null($uid_type)) {
            throw new \InvalidArgumentException('non-nullable uid_type cannot be null');
        }
        $this->container['uid_type'] = $uid_type;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets on_behalf_of
     *
     * @return \RoSdk\Model\OnBehalfOf|null
     */
    public function getOnBehalfOf()
    {
        return $this->container['on_behalf_of'];
    }

    /**
     * Sets on_behalf_of
     *
     * @param \RoSdk\Model\OnBehalfOf|null $on_behalf_of on_behalf_of
     *
     * @return self
     */
    public function setOnBehalfOf($on_behalf_of)
    {
        if (is_null($on_behalf_of)) {
            throw new \InvalidArgumentException('non-nullable on_behalf_of cannot be null');
        }
        $this->container['on_behalf_of'] = $on_behalf_of;

        return $this;
    }

    /**
     * Gets authorizer_uids
     *
     * @return \RoSdk\Model\UidResult[]|null
     */
    public function getAuthorizerUids()
    {
        return $this->container['authorizer_uids'];
    }

    /**
     * Sets authorizer_uids
     *
     * @param \RoSdk\Model\UidResult[]|null $authorizer_uids authorizer_uids
     *
     * @return self
     */
    public function setAuthorizerUids($authorizer_uids)
    {
        if (is_null($authorizer_uids)) {
            array_push($this->openAPINullablesSetToNull, 'authorizer_uids');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authorizer_uids', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['authorizer_uids'] = $authorizer_uids;

        return $this;
    }

    /**
     * Gets empowered_uids
     *
     * @return \RoSdk\Model\UidResult[]|null
     */
    public function getEmpoweredUids()
    {
        return $this->container['empowered_uids'];
    }

    /**
     * Sets empowered_uids
     *
     * @param \RoSdk\Model\UidResult[]|null $empowered_uids empowered_uids
     *
     * @return self
     */
    public function setEmpoweredUids($empowered_uids)
    {
        if (is_null($empowered_uids)) {
            array_push($this->openAPINullablesSetToNull, 'empowered_uids');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('empowered_uids', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['empowered_uids'] = $empowered_uids;

        return $this;
    }

    /**
     * Gets provider_id
     *
     * @return string|null
     */
    public function getProviderId()
    {
        return $this->container['provider_id'];
    }

    /**
     * Sets provider_id
     *
     * @param string|null $provider_id provider_id
     *
     * @return self
     */
    public function setProviderId($provider_id)
    {
        if (is_null($provider_id)) {
            array_push($this->openAPINullablesSetToNull, 'provider_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('provider_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['provider_id'] = $provider_id;

        return $this;
    }

    /**
     * Gets provider_name
     *
     * @return string|null
     */
    public function getProviderName()
    {
        return $this->container['provider_name'];
    }

    /**
     * Sets provider_name
     *
     * @param string|null $provider_name provider_name
     *
     * @return self
     */
    public function setProviderName($provider_name)
    {
        if (is_null($provider_name)) {
            array_push($this->openAPINullablesSetToNull, 'provider_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('provider_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['provider_name'] = $provider_name;

        return $this;
    }

    /**
     * Gets service_id
     *
     * @return int|null
     */
    public function getServiceId()
    {
        return $this->container['service_id'];
    }

    /**
     * Sets service_id
     *
     * @param int|null $service_id service_id
     *
     * @return self
     */
    public function setServiceId($service_id)
    {
        if (is_null($service_id)) {
            throw new \InvalidArgumentException('non-nullable service_id cannot be null');
        }
        $this->container['service_id'] = $service_id;

        return $this;
    }

    /**
     * Gets service_name
     *
     * @return string|null
     */
    public function getServiceName()
    {
        return $this->container['service_name'];
    }

    /**
     * Sets service_name
     *
     * @param string|null $service_name service_name
     *
     * @return self
     */
    public function setServiceName($service_name)
    {
        if (is_null($service_name)) {
            array_push($this->openAPINullablesSetToNull, 'service_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('service_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['service_name'] = $service_name;

        return $this;
    }

    /**
     * Gets volume_of_representation
     *
     * @return \RoSdk\Model\VolumeOfRepresentationResult[]|null
     */
    public function getVolumeOfRepresentation()
    {
        return $this->container['volume_of_representation'];
    }

    /**
     * Sets volume_of_representation
     *
     * @param \RoSdk\Model\VolumeOfRepresentationResult[]|null $volume_of_representation volume_of_representation
     *
     * @return self
     */
    public function setVolumeOfRepresentation($volume_of_representation)
    {
        if (is_null($volume_of_representation)) {
            array_push($this->openAPINullablesSetToNull, 'volume_of_representation');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('volume_of_representation', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['volume_of_representation'] = $volume_of_representation;

        return $this;
    }

    /**
     * Gets created_on
     *
     * @return \DateTime|null
     */
    public function getCreatedOn()
    {
        return $this->container['created_on'];
    }

    /**
     * Sets created_on
     *
     * @param \DateTime|null $created_on created_on
     *
     * @return self
     */
    public function setCreatedOn($created_on)
    {
        if (is_null($created_on)) {
            array_push($this->openAPINullablesSetToNull, 'created_on');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('created_on', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['created_on'] = $created_on;

        return $this;
    }

    /**
     * Gets created_by
     *
     * @return string|null
     */
    public function getCreatedBy()
    {
        return $this->container['created_by'];
    }

    /**
     * Sets created_by
     *
     * @param string|null $created_by created_by
     *
     * @return self
     */
    public function setCreatedBy($created_by)
    {
        if (is_null($created_by)) {
            array_push($this->openAPINullablesSetToNull, 'created_by');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('created_by', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['created_by'] = $created_by;

        return $this;
    }

    /**
     * Gets issuer_position
     *
     * @return string|null
     */
    public function getIssuerPosition()
    {
        return $this->container['issuer_position'];
    }

    /**
     * Sets issuer_position
     *
     * @param string|null $issuer_position issuer_position
     *
     * @return self
     */
    public function setIssuerPosition($issuer_position)
    {
        if (is_null($issuer_position)) {
            array_push($this->openAPINullablesSetToNull, 'issuer_position');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('issuer_position', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['issuer_position'] = $issuer_position;

        return $this;
    }

    /**
     * Gets xml_representation
     *
     * @return string|null
     */
    public function getXmlRepresentation()
    {
        return $this->container['xml_representation'];
    }

    /**
     * Sets xml_representation
     *
     * @param string|null $xml_representation xml_representation
     *
     * @return self
     */
    public function setXmlRepresentation($xml_representation)
    {
        if (is_null($xml_representation)) {
            array_push($this->openAPINullablesSetToNull, 'xml_representation');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('xml_representation', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['xml_representation'] = $xml_representation;

        return $this;
    }

    /**
     * Gets denial_reason
     *
     * @return \RoSdk\Model\EmpowermentsDenialReason|null
     */
    public function getDenialReason()
    {
        return $this->container['denial_reason'];
    }

    /**
     * Sets denial_reason
     *
     * @param \RoSdk\Model\EmpowermentsDenialReason|null $denial_reason denial_reason
     *
     * @return self
     */
    public function setDenialReason($denial_reason)
    {
        if (is_null($denial_reason)) {
            throw new \InvalidArgumentException('non-nullable denial_reason cannot be null');
        }
        $this->container['denial_reason'] = $denial_reason;

        return $this;
    }

    /**
     * Gets empowerment_withdrawals
     *
     * @return \RoSdk\Model\EmpowermentWithdrawResult[]|null
     */
    public function getEmpowermentWithdrawals()
    {
        return $this->container['empowerment_withdrawals'];
    }

    /**
     * Sets empowerment_withdrawals
     *
     * @param \RoSdk\Model\EmpowermentWithdrawResult[]|null $empowerment_withdrawals empowerment_withdrawals
     *
     * @return self
     */
    public function setEmpowermentWithdrawals($empowerment_withdrawals)
    {
        if (is_null($empowerment_withdrawals)) {
            array_push($this->openAPINullablesSetToNull, 'empowerment_withdrawals');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('empowerment_withdrawals', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['empowerment_withdrawals'] = $empowerment_withdrawals;

        return $this;
    }

    /**
     * Gets empowerment_disagreements
     *
     * @return \RoSdk\Model\EmpowermentDisagreementResult[]|null
     */
    public function getEmpowermentDisagreements()
    {
        return $this->container['empowerment_disagreements'];
    }

    /**
     * Sets empowerment_disagreements
     *
     * @param \RoSdk\Model\EmpowermentDisagreementResult[]|null $empowerment_disagreements empowerment_disagreements
     *
     * @return self
     */
    public function setEmpowermentDisagreements($empowerment_disagreements)
    {
        if (is_null($empowerment_disagreements)) {
            array_push($this->openAPINullablesSetToNull, 'empowerment_disagreements');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('empowerment_disagreements', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['empowerment_disagreements'] = $empowerment_disagreements;

        return $this;
    }

    /**
     * Gets status_history
     *
     * @return \RoSdk\Model\StatusHistoryResult[]|null
     */
    public function getStatusHistory()
    {
        return $this->container['status_history'];
    }

    /**
     * Sets status_history
     *
     * @param \RoSdk\Model\StatusHistoryResult[]|null $status_history status_history
     *
     * @return self
     */
    public function setStatusHistory($status_history)
    {
        if (is_null($status_history)) {
            array_push($this->openAPINullablesSetToNull, 'status_history');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('status_history', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['status_history'] = $status_history;

        return $this;
    }

    /**
     * Gets calculated_status_on
     *
     * @return \RoSdk\Model\CalculatedEmpowermentStatus|null
     */
    public function getCalculatedStatusOn()
    {
        return $this->container['calculated_status_on'];
    }

    /**
     * Sets calculated_status_on
     *
     * @param \RoSdk\Model\CalculatedEmpowermentStatus|null $calculated_status_on calculated_status_on
     *
     * @return self
     */
    public function setCalculatedStatusOn($calculated_status_on)
    {
        if (is_null($calculated_status_on)) {
            throw new \InvalidArgumentException('non-nullable calculated_status_on cannot be null');
        }
        $this->container['calculated_status_on'] = $calculated_status_on;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


