<?php
/**
 * EmpowermentsFromMeFilterStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  RoSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eID - RO HTTP API
 *
 * Регистър на овластяванията (РО)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace RoSdk\Model;
use \RoSdk\ObjectSerializer;

/**
 * EmpowermentsFromMeFilterStatus Class Doc Comment
 *
 * @category Class
 * @package  RoSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EmpowermentsFromMeFilterStatus
{
    /**
     * Possible values of this enum
     */
    public const CREATED = 'Created';

    public const VERIFIED = 'Verified';

    public const COLLECTING_AUTHORIZER_SIGNATURES = 'CollectingAuthorizerSignatures';

    public const ACTIVE = 'Active';

    public const DENIED = 'Denied';

    public const DISAGREEMENT_DECLARED = 'DisagreementDeclared';

    public const COLLECTING_WITHDRAWAL_SIGNATURES = 'CollectingWithdrawalSignatures';

    public const WITHDRAWN = 'Withdrawn';

    public const EXPIRED = 'Expired';

    public const UNCONFIRMED = 'Unconfirmed';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CREATED,
            self::VERIFIED,
            self::COLLECTING_AUTHORIZER_SIGNATURES,
            self::ACTIVE,
            self::DENIED,
            self::DISAGREEMENT_DECLARED,
            self::COLLECTING_WITHDRAWAL_SIGNATURES,
            self::WITHDRAWN,
            self::EXPIRED,
            self::UNCONFIRMED
        ];
    }
}


