<?php
/**
 * ProviderServiceResult
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  RoSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eID - RO HTTP API
 *
 * Регистър на овластяванията (РО)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace RoSdk\Model;

use \ArrayAccess;
use \RoSdk\ObjectSerializer;

/**
 * ProviderServiceResult Class Doc Comment
 *
 * @category Class
 * @package  RoSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ProviderServiceResult implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ProviderServiceResult';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'service_number' => 'int',
        'name' => 'string',
        'description' => 'string',
        'payment_info_normal_cost' => 'float',
        'is_empowerment' => 'bool',
        'is_external' => 'bool',
        'is_deleted' => 'bool',
        'provider_details_id' => 'string',
        'provider_section_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'service_number' => 'int64',
        'name' => null,
        'description' => null,
        'payment_info_normal_cost' => 'double',
        'is_empowerment' => null,
        'is_external' => null,
        'is_deleted' => null,
        'provider_details_id' => 'uuid',
        'provider_section_id' => 'uuid'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'service_number' => false,
        'name' => true,
        'description' => true,
        'payment_info_normal_cost' => true,
        'is_empowerment' => false,
        'is_external' => false,
        'is_deleted' => false,
        'provider_details_id' => false,
        'provider_section_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'service_number' => 'serviceNumber',
        'name' => 'name',
        'description' => 'description',
        'payment_info_normal_cost' => 'paymentInfoNormalCost',
        'is_empowerment' => 'isEmpowerment',
        'is_external' => 'isExternal',
        'is_deleted' => 'isDeleted',
        'provider_details_id' => 'providerDetailsId',
        'provider_section_id' => 'providerSectionId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'service_number' => 'setServiceNumber',
        'name' => 'setName',
        'description' => 'setDescription',
        'payment_info_normal_cost' => 'setPaymentInfoNormalCost',
        'is_empowerment' => 'setIsEmpowerment',
        'is_external' => 'setIsExternal',
        'is_deleted' => 'setIsDeleted',
        'provider_details_id' => 'setProviderDetailsId',
        'provider_section_id' => 'setProviderSectionId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'service_number' => 'getServiceNumber',
        'name' => 'getName',
        'description' => 'getDescription',
        'payment_info_normal_cost' => 'getPaymentInfoNormalCost',
        'is_empowerment' => 'getIsEmpowerment',
        'is_external' => 'getIsExternal',
        'is_deleted' => 'getIsDeleted',
        'provider_details_id' => 'getProviderDetailsId',
        'provider_section_id' => 'getProviderSectionId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('service_number', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('payment_info_normal_cost', $data ?? [], null);
        $this->setIfExists('is_empowerment', $data ?? [], null);
        $this->setIfExists('is_external', $data ?? [], null);
        $this->setIfExists('is_deleted', $data ?? [], null);
        $this->setIfExists('provider_details_id', $data ?? [], null);
        $this->setIfExists('provider_section_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets service_number
     *
     * @return int|null
     */
    public function getServiceNumber()
    {
        return $this->container['service_number'];
    }

    /**
     * Sets service_number
     *
     * @param int|null $service_number service_number
     *
     * @return self
     */
    public function setServiceNumber($service_number)
    {
        if (is_null($service_number)) {
            throw new \InvalidArgumentException('non-nullable service_number cannot be null');
        }
        $this->container['service_number'] = $service_number;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets payment_info_normal_cost
     *
     * @return float|null
     */
    public function getPaymentInfoNormalCost()
    {
        return $this->container['payment_info_normal_cost'];
    }

    /**
     * Sets payment_info_normal_cost
     *
     * @param float|null $payment_info_normal_cost payment_info_normal_cost
     *
     * @return self
     */
    public function setPaymentInfoNormalCost($payment_info_normal_cost)
    {
        if (is_null($payment_info_normal_cost)) {
            array_push($this->openAPINullablesSetToNull, 'payment_info_normal_cost');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('payment_info_normal_cost', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['payment_info_normal_cost'] = $payment_info_normal_cost;

        return $this;
    }

    /**
     * Gets is_empowerment
     *
     * @return bool|null
     */
    public function getIsEmpowerment()
    {
        return $this->container['is_empowerment'];
    }

    /**
     * Sets is_empowerment
     *
     * @param bool|null $is_empowerment is_empowerment
     *
     * @return self
     */
    public function setIsEmpowerment($is_empowerment)
    {
        if (is_null($is_empowerment)) {
            throw new \InvalidArgumentException('non-nullable is_empowerment cannot be null');
        }
        $this->container['is_empowerment'] = $is_empowerment;

        return $this;
    }

    /**
     * Gets is_external
     *
     * @return bool|null
     */
    public function getIsExternal()
    {
        return $this->container['is_external'];
    }

    /**
     * Sets is_external
     *
     * @param bool|null $is_external is_external
     *
     * @return self
     */
    public function setIsExternal($is_external)
    {
        if (is_null($is_external)) {
            throw new \InvalidArgumentException('non-nullable is_external cannot be null');
        }
        $this->container['is_external'] = $is_external;

        return $this;
    }

    /**
     * Gets is_deleted
     *
     * @return bool|null
     */
    public function getIsDeleted()
    {
        return $this->container['is_deleted'];
    }

    /**
     * Sets is_deleted
     *
     * @param bool|null $is_deleted is_deleted
     *
     * @return self
     */
    public function setIsDeleted($is_deleted)
    {
        if (is_null($is_deleted)) {
            throw new \InvalidArgumentException('non-nullable is_deleted cannot be null');
        }
        $this->container['is_deleted'] = $is_deleted;

        return $this;
    }

    /**
     * Gets provider_details_id
     *
     * @return string|null
     */
    public function getProviderDetailsId()
    {
        return $this->container['provider_details_id'];
    }

    /**
     * Sets provider_details_id
     *
     * @param string|null $provider_details_id provider_details_id
     *
     * @return self
     */
    public function setProviderDetailsId($provider_details_id)
    {
        if (is_null($provider_details_id)) {
            throw new \InvalidArgumentException('non-nullable provider_details_id cannot be null');
        }
        $this->container['provider_details_id'] = $provider_details_id;

        return $this;
    }

    /**
     * Gets provider_section_id
     *
     * @return string|null
     */
    public function getProviderSectionId()
    {
        return $this->container['provider_section_id'];
    }

    /**
     * Sets provider_section_id
     *
     * @param string|null $provider_section_id provider_section_id
     *
     * @return self
     */
    public function setProviderSectionId($provider_section_id)
    {
        if (is_null($provider_section_id)) {
            throw new \InvalidArgumentException('non-nullable provider_section_id cannot be null');
        }
        $this->container['provider_section_id'] = $provider_section_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


