<?php
/**
 * SignatureProvider
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  RoSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eID - RO HTTP API
 *
 * Регистър на овластяванията (РО)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace RoSdk\Model;
use \RoSdk\ObjectSerializer;

/**
 * SignatureProvider Class Doc Comment
 *
 * @category Class
 * @package  RoSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SignatureProvider
{
    /**
     * Possible values of this enum
     */
    public const NOT_SPECIFIED = 'NotSpecified';

    public const KEP = 'KEP';

    public const EVROTRUST = 'Evrotrust';

    public const BORICA = 'Borica';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NOT_SPECIFIED,
            self::KEP,
            self::EVROTRUST,
            self::BORICA
        ];
    }
}


