namespace eID.PIVR.Contracts;

public enum LogEventCode
{
    None = 0,
    REGIX_SEARCH = 1,
    GET_DATE_OF_DEATH = 2,
    GET_DATE_OF_PROHIBITION = 3,
    TR_GET_ACTUAL_STATE_V3 = 4,
    VERIFY_SIGNATURE = 5,
    MVR_GET_FOREIGN_IDENTITY_V2 = 6,
    MVR_GET_PERSONAL_IDENTITY_V2 = 7,
    GRAO_RELATIONS_SEARCH = 8,
    GET_DECEASED_BY_PERIOD = 9,
    BULSTAT_GET_STATE_OF_PLAY = 10,
    GET_ID_CHANGES = 11,
    GET_STATUT_CHANGES = 12,
    CHECK_UID_RESTRICTIONS = 13,
}
