namespace eID.MIS.Contracts;

public enum LogEventCode
{
    NONE = 0,
    CREATE_PAYMENT_REQUEST = 1,
    GET_PAYMENT_REQUEST_STATUS = 2,
    GET_PAYMENT_REQUESTS = 3,
    GET_CLIENTS_BY_EIK = 4,
    CREATE_PASSIVE_INDIVIDUAL_PROFILE = 5,
    SEARCH_PROFILE = 6,
    GET_PROFILE = 7,
    SEND_MESSAGE_ON_BEHALF = 8,
    UPLOAD_BLOB = 9,
    GET_DELIVERIES = 10,
    SEND_MESSAGE = 11,
    UPLOAD_BLOB_ON_BEHALF_OF = 12
}
