server:
  port: 8090
  ssl:
    enabled: false
    trust-store:
    trust-store-password:
    trust-store-type: PKCS12
logging:
  secret-key:
spring:
  rabbitmq:
    host:
    username:
    password:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
          audiences:
            - eid_rei
keycloak:
  auth-server-url:
  realm:
  oauth-scheme-name: keycloak
custom:
  rabbitmq:
    queue-prefix: rei.rpcqueue.
    routing-key-prefix: rei.routingkey.
    rpc-exchange: rei.rpc.exchange
    reply-exchange: rei.reply.exchange
    reply-queue: rei.reply.rpcqueue