#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run custom version bump logic first
bash .githooks/pre-commit || exit 1

cd src/eID.PUN.AdminUI
npx lint-staged -r


cd ..

echo "dotnet build"

dotnet clean; dotnet build
rc=$?

if [[ $rc != 0 ]] ; then
    echo -e "build failed"
    exit $rc
fi

dotnet test

rc=$?

if [[ $rc != 0 ]] ; then
    echo -e "test failed"
    exit $rc
fi

exit 0
