namespace eID.Signing.Contracts;

public enum LogEventCode
{
    None = 0,
    EVROTRUST_SIGN_DOCUMENT = 1,
    EVROTRUST_GET_FILE_STATUS = 2,
    EVROTRUST_DOWNLOAD_FILE = 3,
    EVROTRUST_CHECK_USER = 4,
    BORICA_SIGN_DOCUMENT = 5,
    BORICA_GET_FILE_STATUS = 6,
    BORICA_DOWNLOAD_FILE = 7,
    BORICA_CHECK_USER = 8,
    KEP_GET_DATA_TO_SIGN = 9,
    KEP_SIGN_DATA = 10,
    BORICA_ASRSIGN_DOCUMENT = 11,
    BORICA_SEND_CONSENT = 12,
    BORICA_CHECK_CONSENT_STATUS = 13,
    BORICA_GET_ACCESS_TOKENS = 14,
    BORICA_ADD_ACCESS_TOKEN = 15,
}
