/*
 * eID - RO HTTP API
 * Регистър на овластяванията (РО)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AuthorizerIdentifierData;
import org.openapitools.client.model.IdentifierType;
import org.openapitools.client.model.OnBehalfOf;
import org.openapitools.client.model.TypeOfEmpowerment;
import org.openapitools.client.model.UserIdentifierData;
import org.openapitools.client.model.VolumeOfRepresentationRequest;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AddEmpowermentStatementsRequest
 */
public class AddEmpowermentStatementsRequestTest {
    private final AddEmpowermentStatementsRequest model = new AddEmpowermentStatementsRequest();

    /**
     * Model tests for AddEmpowermentStatementsRequest
     */
    @Test
    public void testAddEmpowermentStatementsRequest() {
        // TODO: test AddEmpowermentStatementsRequest
    }

    /**
     * Test the property 'onBehalfOf'
     */
    @Test
    public void onBehalfOfTest() {
        // TODO: test onBehalfOf
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'uid'
     */
    @Test
    public void uidTest() {
        // TODO: test uid
    }

    /**
     * Test the property 'uidType'
     */
    @Test
    public void uidTypeTest() {
        // TODO: test uidType
    }

    /**
     * Test the property 'empoweredUids'
     */
    @Test
    public void empoweredUidsTest() {
        // TODO: test empoweredUids
    }

    /**
     * Test the property 'typeOfEmpowerment'
     */
    @Test
    public void typeOfEmpowermentTest() {
        // TODO: test typeOfEmpowerment
    }

    /**
     * Test the property 'providerId'
     */
    @Test
    public void providerIdTest() {
        // TODO: test providerId
    }

    /**
     * Test the property 'providerName'
     */
    @Test
    public void providerNameTest() {
        // TODO: test providerName
    }

    /**
     * Test the property 'serviceId'
     */
    @Test
    public void serviceIdTest() {
        // TODO: test serviceId
    }

    /**
     * Test the property 'serviceName'
     */
    @Test
    public void serviceNameTest() {
        // TODO: test serviceName
    }

    /**
     * Test the property 'issuerPosition'
     */
    @Test
    public void issuerPositionTest() {
        // TODO: test issuerPosition
    }

    /**
     * Test the property 'volumeOfRepresentation'
     */
    @Test
    public void volumeOfRepresentationTest() {
        // TODO: test volumeOfRepresentation
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'expiryDate'
     */
    @Test
    public void expiryDateTest() {
        // TODO: test expiryDate
    }

    /**
     * Test the property 'authorizerUids'
     */
    @Test
    public void authorizerUidsTest() {
        // TODO: test authorizerUids
    }

}
