/*
 * eID - RO HTTP API
 * Регистър на овластяванията (РО)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EmpowermentWithdrawalReasonTranslationResult
 */
public class EmpowermentWithdrawalReasonTranslationResultTest {
    private final EmpowermentWithdrawalReasonTranslationResult model = new EmpowermentWithdrawalReasonTranslationResult();

    /**
     * Model tests for EmpowermentWithdrawalReasonTranslationResult
     */
    @Test
    public void testEmpowermentWithdrawalReasonTranslationResult() {
        // TODO: test EmpowermentWithdrawalReasonTranslationResult
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
