/*
 * eID - RO HTTP API
 * Регистър на овластяванията (РО)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.EmpowermentsByEikFilterStatus;
import org.openapitools.client.model.EmpowermentsByEikSortBy;
import org.openapitools.client.model.SortDirection;
import org.openapitools.client.model.UserIdentifierData;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetEmpowermentsByEikFilterRequest
 */
public class GetEmpowermentsByEikFilterRequestTest {
    private final GetEmpowermentsByEikFilterRequest model = new GetEmpowermentsByEikFilterRequest();

    /**
     * Model tests for GetEmpowermentsByEikFilterRequest
     */
    @Test
    public void testGetEmpowermentsByEikFilterRequest() {
        // TODO: test GetEmpowermentsByEikFilterRequest
    }

    /**
     * Test the property 'eik'
     */
    @Test
    public void eikTest() {
        // TODO: test eik
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'providerName'
     */
    @Test
    public void providerNameTest() {
        // TODO: test providerName
    }

    /**
     * Test the property 'serviceName'
     */
    @Test
    public void serviceNameTest() {
        // TODO: test serviceName
    }

    /**
     * Test the property 'validToDate'
     */
    @Test
    public void validToDateTest() {
        // TODO: test validToDate
    }

    /**
     * Test the property 'showOnlyNoExpiryDate'
     */
    @Test
    public void showOnlyNoExpiryDateTest() {
        // TODO: test showOnlyNoExpiryDate
    }

    /**
     * Test the property 'authorizerUids'
     */
    @Test
    public void authorizerUidsTest() {
        // TODO: test authorizerUids
    }

    /**
     * Test the property 'sortBy'
     */
    @Test
    public void sortByTest() {
        // TODO: test sortBy
    }

    /**
     * Test the property 'sortDirection'
     */
    @Test
    public void sortDirectionTest() {
        // TODO: test sortDirection
    }

    /**
     * Test the property 'pageSize'
     */
    @Test
    public void pageSizeTest() {
        // TODO: test pageSize
    }

    /**
     * Test the property 'pageIndex'
     */
    @Test
    public void pageIndexTest() {
        // TODO: test pageIndex
    }

}
