/*
 * eID - RO HTTP API
 * Регистър на овластяванията (РО)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProviderServiceResult
 */
public class ProviderServiceResultTest {
    private final ProviderServiceResult model = new ProviderServiceResult();

    /**
     * Model tests for ProviderServiceResult
     */
    @Test
    public void testProviderServiceResult() {
        // TODO: test ProviderServiceResult
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'serviceNumber'
     */
    @Test
    public void serviceNumberTest() {
        // TODO: test serviceNumber
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'paymentInfoNormalCost'
     */
    @Test
    public void paymentInfoNormalCostTest() {
        // TODO: test paymentInfoNormalCost
    }

    /**
     * Test the property 'isEmpowerment'
     */
    @Test
    public void isEmpowermentTest() {
        // TODO: test isEmpowerment
    }

    /**
     * Test the property 'isExternal'
     */
    @Test
    public void isExternalTest() {
        // TODO: test isExternal
    }

    /**
     * Test the property 'isDeleted'
     */
    @Test
    public void isDeletedTest() {
        // TODO: test isDeleted
    }

    /**
     * Test the property 'providerDetailsId'
     */
    @Test
    public void providerDetailsIdTest() {
        // TODO: test providerDetailsId
    }

    /**
     * Test the property 'providerSectionId'
     */
    @Test
    public void providerSectionIdTest() {
        // TODO: test providerSectionId
    }

}
