methods:
  post:
    summary: Upload Document For Application
    operationId: uploadDocumentForApplication
    tags:
      - FileUpload
    parameters:
      - name: id
        in: path
        description: 'Id'
        required: true
        schema:
          type: string
          format: uuid
    requestBody:
      required: true
      content:
        application/json;charset=UTF-8:
          schema:
            type: array
            items:
              $ref: '../../components/common/document.yaml#/schemas/DocumentDTO'
    responses:
      '200':
        description: Success
        content:
          application/json;charset=UTF-8:
            schema:
              type: array
              items:
                $ref: '../../components/common/document.yaml#/schemas/DocumentDTO'
      '400':
        description: Bad Request
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/validation_problem_details_v1.yaml#/schemas/ValidationProblemDetailsDTO'
      '404':
        description: Not Found
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/problem_details_v1.yaml#/schemas/ProblemDetailsDTO'
      '409':
        description: Conflict
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/problem_details_v1.yaml#/schemas/ProblemDetailsDTO'
      '500':
        description: Server Error
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/problem_details_v1.yaml#/schemas/ProblemDetailsDTO'
      '504':
        description: Time Out
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/problem_details_v1.yaml#/schemas/ProblemDetailsDTO'