spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
custom:
  rabbitmq:
    queue-prefix: rei.rpcqueue.
    routing-key-prefix: rei.routingkey.
    rpc-exchange: rei.rpc.exchange
    reply-exchange: rei.reply.exchange
    reply-queue: rei.reply.rpcqueue