spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${KEYCLOAK_BASE_URL}/realms/${KEYCLOAK_REALM}
          audiences:
            - eid_rei
keycloak:
  auth-server-url: https://${KEYCLOAK_BASE_URL}
  realm: ${KEYCLOAK_REALM}
  oauth-scheme-name: keycloak