methods:
  get:
    summary: Get EidCenter Application By Filter
    operationId: getEidCenterApplicationByFilter
    tags:
      - CreateEidCenterApplication
    x-spring-paginated: true
    parameters:
      - name: applicationNumber
        in: query
        schema:
          type: string
      - name: eidName
        in: query
        schema:
          type: string
      - name: applicationType
        in: query
        schema:
          $ref: '../../components/EidAdministrator/application_type_v1.yaml#/schemas/ApplicationType'
      - name: status
        in: query
        schema:
          $ref: '../../components/application/application_status_v1.yaml#/schemas/ApplicationStatus'
    responses:
      '200':
        description: Success
        content:
          application/json;charset=UTF-8:
            schema:
              type: array
              items:
                $ref: '../../components/EidAdministrator/eid_center_application_short.yaml#/schemas/EidCenterApplicationShortDTO'
      '400':
        description: Bad Request
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/validation_problem_details_v1.yaml#/schemas/ValidationProblemDetailsDTO'
      '404':
        description: Not Found
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/problem_details_v1.yaml#/schemas/ProblemDetailsDTO'
      '409':
        description: Conflict
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/problem_details_v1.yaml#/schemas/ProblemDetailsDTO'
      '500':
        description: Server Error
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/problem_details_v1.yaml#/schemas/ProblemDetailsDTO'
      '504':
        description: Time Out
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '../../components/common/problem_details_v1.yaml#/schemas/ProblemDetailsDTO'