/**
 * Please follow code style when editing project
 * Please follow principles of clean architecture
 * Created 2024 by Roman Kryvolapov
 **/
package com.digitall.eid.models.main.more

import com.digitall.eid.domain.models.base.TypeEnum

enum class TabMoreItems(override val type: String) : TypeEnum {
    USER_INFORMATION("USER_INFORMATION"),
    USER_PROFILE_SECURITY("USER_PROFILE_SECURITY"),
    SETUP_NOTIFICATIONS("SETUP_NOTIFICATIONS"),
    CHANGE_EMAIL("CHANGE_EMAIL"),
    CHANGE_PASSWORD("CHANGE_PASSWORD"),
    CHANGE_PHONE("CHANGE_PHONE"),
    EMPOWERMENT("EMPOWERMENT"),
    JOURNAL("JOURNAL"),
    FAQ("FAQ"),
    CONTACTS("CONTACTS"),
    TERMS_AND_CONDITIONS("TERMS_AND_CONDITIONS"),
    ADMINISTRATORS("ADMINISTRATORS"),
    CENTERS_CERTIFICATION_SERVICES("CENTERS_CERTIFICATION_SERVICES"),
    PROVIDERS_ELECTRONIC_ADMINISTRATIVE_SERVICES("PROVIDERS_ELECTRONIC_ADMINISTRATIVE_SERVICES"),
    ONLINE_HELP_SYSTEM("ONLINE_HELP_SYSTEM"),
    ELECTRONIC_DELIVERY_SYSTEM("ELECTRONIC_DELIVERY_SYSTEM"),
    SETTINGS("SETTINGS"),
    PAYMENT_HISTORY("PAYMENT_HISTORY"),
    OTHER("OTHER")
}