openapi: 3.0.1
info:
  description: API reference documentation for Register of administrators of electronic identity and electronic identity Centers
  version: '1.0'
  title: RAEICEI REST Interface
paths:
# EidAdministrator
  "/raeicei/api/v1/eidadministrator/{id}":
    $ref: 'paths_v1/eidadministrator/eidadministrator-internal.yaml#/methods'
  "/raeicei/api/v1/eidadministrator/create":
    $ref: 'paths_v1/eidadministrator/eidadministrator-create.yaml#/methods'
  "/raeicei/api/v1/eidadministrator/getAll":
    $ref: 'paths_v1/eidadministrator/eidadministrator_list.yaml#/methods'
  "/raeicei/api/v1/eidadministrator/history/getAll":
    $ref: 'paths_v1/eidadministrator/eidadministrator_history_list.yaml#/methods'
  "/raeicei/api/v1/eidadministrator/{id}/employee":
    $ref: 'paths_v1/employee/employee-aei-check.yaml#/methods'

# EidCenter
  "/raeicei/api/v1/eidcenter/{id}":
    $ref: 'paths_v1/eidcenter/eidcenter-internal.yaml#/methods'
  "/raeicei/api/v1/eidcenter/create":
    $ref: 'paths_v1/eidcenter/eidcenter-create.yaml#/methods'
  "/raeicei/api/v1/eidcenter/getAll":
    $ref: 'paths_v1/eidcenter/eidcenter_list.yaml#/methods'
  "/raeicei/api/v1/eidcenter/history/getAll":
    $ref: 'paths_v1/eidcenter/eidcenter_history_list.yaml#/methods'
  "/raeicei/api/v1/eidcenter/{id}/employee":
    $ref: 'paths_v1/employee/employee-cei-check.yaml#/methods'

# Device
  "/raeicei/api/v1/device":
    $ref: 'paths_v1/device/device-type.yaml#/methods'
  "/raeicei/api/v1/device/getAll":
    $ref: 'paths_v1/device/device_list.yaml#/methods'
  "/raeicei/api/v1/device/aei/{aeiId}":
    $ref: 'paths_v1/device/device-administrator.yaml#/methods'
  "/raeicei/api/v1/device/{id}":
    $ref: 'paths_v1/device/device-get-by-id.yaml#/methods'

# Tariff
  "/raeicei/api/v1/tariff/getByDate":
    $ref: 'paths_v1/tariff/tariff-getByDate.yaml#/methods'
  "/raeicei/api/v1/tariff/getAll/{eidManagerId}":
    $ref: 'paths_v1/tariff/tariff-getAll.yaml#/methods'
  "/raeicei/api/v1/tariff/{id}":
    $ref: 'paths_v1/tariff/tariff-by-id.yaml#/methods'

# Discount
  "/raeicei/api/v1/discount/getAll/{eidManagerId}":
    $ref: 'paths_v1/discount/discount-getAll.yaml#/methods'
  "/raeicei/api/v1/discount/getByDate":
    $ref: 'paths_v1/discount/discount-getByDate.yaml#/methods'
  "/raeicei/api/v1/discount/{id}":
    $ref: 'paths_v1/discount/discount-by-id.yaml#/methods'

# DeviceTarrif
  "/raeicei/api/v1/deviceTariff/create":
    $ref: 'paths_v1/device-tariff/device-tariff-create.yaml#/methods'
  "/raeicei/api/v1/deviceTariff/getAll/{eidManagerId}":
    $ref: 'paths_v1/device-tariff/device-tariff-getAll.yaml#/methods'
  "/raeicei/api/v1/deviceTariff/getByDate":
    $ref: 'paths_v1/device-tariff/device-tariff-getByDate.yaml#/methods'
  
# EidManagerFrontOffice
  "/raeicei/api/v1/eidmanagerfrontoffice":
    $ref: 'paths_v1/eidmanagerfrontoffice/eidmanagerfrontoffice-name.yaml#/methods'
  "/raeicei/api/v1/eidmanagerfrontoffice/getAll/region/{region}":
    $ref: 'paths_v1/eidmanagerfrontoffice/eidmanagerfrontoffice_list_by_region.yaml#/methods'
  "/raeicei/api/v1/eidmanagerfrontoffice/getAll/{eidManagerId}":
    $ref: 'paths_v1/eidmanagerfrontoffice/eidmanagerfrontoffice_list.yaml#/methods'
  "/raeicei/api/v1/eidmanagerfrontoffice/{id}":
    $ref: 'paths_v1/eidmanagerfrontoffice/eidmanagerfrontoffice-get-by-id.yaml#/methods'
  
# CalculateTariff
  "/raeicei/api/v1/calculateTariff":
    $ref: 'paths_v1/calculate-tariff/calculate-tariff.yaml#/methods'

# ProvidedService
  "/raeicei/api/v1/providedservice/create":
    $ref: 'paths_v1/provided-service/provided-service-create.yaml#/methods'
  "/raeicei/api/v1/providedservice/update/{id}":
    $ref: 'paths_v1/provided-service/provided-service-update.yaml#/methods'
  "/raeicei/api/v1/providedservice/delete/{id}":
    $ref: 'paths_v1/provided-service/provided-service-delete.yaml#/methods'
  "/raeicei/api/v1/providedservice/get/{id}":
    $ref: 'paths_v1/provided-service/provided-service-get-by-id.yaml#/methods'
  "/raeicei/api/v1/providedservice/get/applicationType/{type}":
    $ref: 'paths_v1/provided-service/provided-service-get-by-application-type.yaml#/methods'
  "/raeicei/api/v1/providedservice/getAll":
    $ref: 'paths_v1/provided-service/provided-service-list.yaml#/methods'

# Attachment
  "/raeicei/api/v1/application/document/upload/{id}":
    $ref: 'paths_v1/document/upload-document-for-application.yaml#/methods'
  "/raeicei/api/v1/eidmanager/document/upload":
    $ref: 'paths_v1/document/upload-document-for-eid-manager.yaml#/methods'
  "/raeicei/api/v1/document/get/{id}":
    $ref: 'paths_v1/document/document-by-id.yaml#/methods'
#  "/raeicei/api/v1/document/delete/{id}":
#    $ref: 'paths_v1/document/delete-document.yaml#/methods'
  "/raeicei/api/v1/document/export/technicalcheck":
    $ref: 'paths_v1/document/technical-check.yaml#/methods'

# Document Type
  "/raeicei/api/v1/document-type/create":
    $ref: 'paths_v1/document/document_type-create.yaml#/methods'
  "/raeicei/api/v1/document-type/update":
    $ref: 'paths_v1/document/document_type-update.yaml#/methods'
  "/raeicei/api/v1/document-type/{id}":
    $ref: 'paths_v1/document/document_type-by-id.yaml#/methods'
  "/raeicei/api/v1/document-type/list":
    $ref: 'paths_v1/document/document_type-list.yaml#/methods'
  "/raeicei/api/v1/document-type/delete/{id}":
    $ref: 'paths_v1/document/document_type-delete.yaml#/methods'

# EidAdministratorApplication
  "/raeicei/api/v1/eidadministratorapplication/create":
    $ref: 'paths_v1/eidadministrator/create-eid-administrator-application.yaml#/methods'
  "/raeicei/api/v1/eidadministratorapplication/list":
    $ref: 'paths_v1/eidadministrator/eid-administrator-application-list.yaml#/methods'
  "/raeicei/api/v1/eidadministratorapplication/{id}":
    $ref: 'paths_v1/eidadministrator/eid-administrator-application-by-id.yaml#/methods'

# EidCenterApplication
  "/raeicei/api/v1/eidcenterapplication/create":
    $ref: 'paths_v1/eidcenter/create-eid-center-application.yaml#/methods'
  "/raeicei/api/v1/eidcenterapplication/list":
    $ref: 'paths_v1/eidcenter/eid-center-application-list.yaml#/methods'
  "/raeicei/api/v1/eidcenterapplication/{id}":
    $ref: 'paths_v1/eidcenter/eid-center-application-by-id.yaml#/methods'

# EmployeeService
  "/raeicei/api/v1/employee/list/{systemId}":
    $ref: 'paths_v1/employee/employee-list.yaml#/methods'

# Region
  "/raeicei/api/v1/region/list":
    $ref: 'paths_v1/region/region-list.yaml#/methods'

# ChangeApplicationStatus
  "/raeicei/api/v1/application-status/change/{id}":
    $ref: 'paths_v1/status/change-application-status.yaml#/methods'
  "/raeicei/api/v1/application-status/documentsnotes/{id}":
    $ref: 'paths_v1/status/documents-notes-for-application.yaml#/methods'

# ChangeCircumstances
  "/raeicei/api/v1/circs/device/create":
    $ref: 'paths_v1/change-circumstances/device-create.yaml#/methods'
  "/raeicei/api/v1/circs/device/update":
    $ref: 'paths_v1/change-circumstances/device-update.yaml#/methods'
  "/raeicei/api/v1/circs/tariff/create":
    $ref: 'paths_v1/change-circumstances/tariff-create.yaml#/methods'
  "/raeicei/api/v1/circs/tariff/update/{id}":
    $ref: 'paths_v1/change-circumstances/tariff-update.yaml#/methods'
  "/raeicei/api/v1/circs/tariff/delete/{id}":
    $ref: 'paths_v1/change-circumstances/tariff-delete.yaml#/methods'
  "/raeicei/api/v1/circs/discount/create":
    $ref: 'paths_v1/change-circumstances/discount-create.yaml#/methods'
  "/raeicei/api/v1/circs/discount/update/{id}":
    $ref: 'paths_v1/change-circumstances/discount-update.yaml#/methods'
  "/raeicei/api/v1/circs/discount/delete/{id}":
    $ref: 'paths_v1/change-circumstances/discount-delete.yaml#/methods'
  "/raeicei/api/v1/circs/eidmanagerfrontoffice/create":
    $ref: 'paths_v1/change-circumstances/eidmanagerfrontoffice-create.yaml#/methods'
  "/raeicei/api/v1/circs/eidmanagerfrontoffice/update":
    $ref: 'paths_v1/change-circumstances/eidmanagerfrontoffice-update.yaml#/methods'

# ApproveNewCircumstances
  "/raeicei/api/v1/newcircs/eidadministrator/findbystatus/{status}":
    $ref: 'paths_v1/approve-new-circumstances/eid-administrator-by-status.yaml#/methods'
  "/raeicei/api/v1/newcircs/eidadministrator/details/{id}":
    $ref: 'paths_v1/approve-new-circumstances/full-eidadministrator-by-id.yaml#/methods'
  "/raeicei/api/v1/newcircs/eidadministrator/approve/{id}":
    $ref: 'paths_v1/approve-new-circumstances/approve-eid-administrator.yaml#/methods'
  "/raeicei/api/v1/newcircs/eidcenter/findbystatus/{status}":
    $ref: 'paths_v1/approve-new-circumstances/eid-center-by-status.yaml#/methods'
  "/raeicei/api/v1/newcircs/eidcenter/details/{id}":
    $ref: 'paths_v1/approve-new-circumstances/full-eidcenter-by-id.yaml#/methods'
  "/raeicei/api/v1/newcircs/eidcenter/approve/{id}":
    $ref: 'paths_v1/approve-new-circumstances/approve-eid-center.yaml#/methods'
  "/raeicei/api/v1/circs/eidmanager/documentsnotes":
    $ref: 'paths_v1/approve-new-circumstances/documents-notes-for-eid-manager.yaml#/methods'

# Code
  "/raeicei/api/v1/checkcode/{code}":
    $ref: 'paths_v1/code/check-code.yaml#/methods'

# Report
  "/raeicei/api/v1/reports/administrators":
    $ref: 'paths_v1/report/eid_administrator_report.yaml#/methods'
  "/raeicei/api/v1/reports/centers":
    $ref: 'paths_v1/report/eid_center_report.yaml#/methods'