<?php
/**
 * X509CertificateCodeFlowControllerApi
 * PHP version 8.1
 *
 * @category Class
 * @package  IsceiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ISCEI HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IsceiSdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use IsceiSdk\ApiException;
use IsceiSdk\Configuration;
use IsceiSdk\FormDataProcessor;
use IsceiSdk\HeaderSelector;
use IsceiSdk\ObjectSerializer;

/**
 * X509CertificateCodeFlowControllerApi Class Doc Comment
 *
 * @category Class
 * @package  IsceiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class X509CertificateCodeFlowControllerApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'codeFlowAuth' => [
            'application/json',
        ],
        'codeFlowToken' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation codeFlowAuth
     *
     * @param  string $client_id client_id (required)
     * @param  string $response_type response_type (required)
     * @param  string $state state (required)
     * @param  string $redirect_uri redirect_uri (required)
     * @param  string $code_challenge code_challenge (required)
     * @param  string $code_challenge_method code_challenge_method (required)
     * @param  \IsceiSdk\Model\SignedChallenge $signed_challenge signed_challenge (required)
     * @param  string[]|null $scope scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['codeFlowAuth'] to see the possible values for this operation
     *
     * @throws \IsceiSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return string
     */
    public function codeFlowAuth($client_id, $response_type, $state, $redirect_uri, $code_challenge, $code_challenge_method, $signed_challenge, $scope = null, string $contentType = self::contentTypes['codeFlowAuth'][0])
    {
        list($response) = $this->codeFlowAuthWithHttpInfo($client_id, $response_type, $state, $redirect_uri, $code_challenge, $code_challenge_method, $signed_challenge, $scope, $contentType);
        return $response;
    }

    /**
     * Operation codeFlowAuthWithHttpInfo
     *
     * @param  string $client_id (required)
     * @param  string $response_type (required)
     * @param  string $state (required)
     * @param  string $redirect_uri (required)
     * @param  string $code_challenge (required)
     * @param  string $code_challenge_method (required)
     * @param  \IsceiSdk\Model\SignedChallenge $signed_challenge (required)
     * @param  string[]|null $scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['codeFlowAuth'] to see the possible values for this operation
     *
     * @throws \IsceiSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function codeFlowAuthWithHttpInfo($client_id, $response_type, $state, $redirect_uri, $code_challenge, $code_challenge_method, $signed_challenge, $scope = null, string $contentType = self::contentTypes['codeFlowAuth'][0])
    {
        $request = $this->codeFlowAuthRequest($client_id, $response_type, $state, $redirect_uri, $code_challenge, $code_challenge_method, $signed_challenge, $scope, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'string',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'string',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation codeFlowAuthAsync
     *
     * @param  string $client_id (required)
     * @param  string $response_type (required)
     * @param  string $state (required)
     * @param  string $redirect_uri (required)
     * @param  string $code_challenge (required)
     * @param  string $code_challenge_method (required)
     * @param  \IsceiSdk\Model\SignedChallenge $signed_challenge (required)
     * @param  string[]|null $scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['codeFlowAuth'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function codeFlowAuthAsync($client_id, $response_type, $state, $redirect_uri, $code_challenge, $code_challenge_method, $signed_challenge, $scope = null, string $contentType = self::contentTypes['codeFlowAuth'][0])
    {
        return $this->codeFlowAuthAsyncWithHttpInfo($client_id, $response_type, $state, $redirect_uri, $code_challenge, $code_challenge_method, $signed_challenge, $scope, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation codeFlowAuthAsyncWithHttpInfo
     *
     * @param  string $client_id (required)
     * @param  string $response_type (required)
     * @param  string $state (required)
     * @param  string $redirect_uri (required)
     * @param  string $code_challenge (required)
     * @param  string $code_challenge_method (required)
     * @param  \IsceiSdk\Model\SignedChallenge $signed_challenge (required)
     * @param  string[]|null $scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['codeFlowAuth'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function codeFlowAuthAsyncWithHttpInfo($client_id, $response_type, $state, $redirect_uri, $code_challenge, $code_challenge_method, $signed_challenge, $scope = null, string $contentType = self::contentTypes['codeFlowAuth'][0])
    {
        $returnType = 'string';
        $request = $this->codeFlowAuthRequest($client_id, $response_type, $state, $redirect_uri, $code_challenge, $code_challenge_method, $signed_challenge, $scope, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'codeFlowAuth'
     *
     * @param  string $client_id (required)
     * @param  string $response_type (required)
     * @param  string $state (required)
     * @param  string $redirect_uri (required)
     * @param  string $code_challenge (required)
     * @param  string $code_challenge_method (required)
     * @param  \IsceiSdk\Model\SignedChallenge $signed_challenge (required)
     * @param  string[]|null $scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['codeFlowAuth'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function codeFlowAuthRequest($client_id, $response_type, $state, $redirect_uri, $code_challenge, $code_challenge_method, $signed_challenge, $scope = null, string $contentType = self::contentTypes['codeFlowAuth'][0])
    {

        // verify the required parameter 'client_id' is set
        if ($client_id === null || (is_array($client_id) && count($client_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $client_id when calling codeFlowAuth'
            );
        }

        // verify the required parameter 'response_type' is set
        if ($response_type === null || (is_array($response_type) && count($response_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $response_type when calling codeFlowAuth'
            );
        }

        // verify the required parameter 'state' is set
        if ($state === null || (is_array($state) && count($state) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $state when calling codeFlowAuth'
            );
        }

        // verify the required parameter 'redirect_uri' is set
        if ($redirect_uri === null || (is_array($redirect_uri) && count($redirect_uri) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $redirect_uri when calling codeFlowAuth'
            );
        }

        // verify the required parameter 'code_challenge' is set
        if ($code_challenge === null || (is_array($code_challenge) && count($code_challenge) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code_challenge when calling codeFlowAuth'
            );
        }

        // verify the required parameter 'code_challenge_method' is set
        if ($code_challenge_method === null || (is_array($code_challenge_method) && count($code_challenge_method) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code_challenge_method when calling codeFlowAuth'
            );
        }

        // verify the required parameter 'signed_challenge' is set
        if ($signed_challenge === null || (is_array($signed_challenge) && count($signed_challenge) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $signed_challenge when calling codeFlowAuth'
            );
        }

        

        $resourcePath = '/api/v1/code-flow/auth';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $client_id,
            'client_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $response_type,
            'response_type', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $state,
            'state', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $scope,
            'scope', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $redirect_uri,
            'redirect_uri', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $code_challenge,
            'code_challenge', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $code_challenge_method,
            'code_challenge_method', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($signed_challenge)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($signed_challenge));
            } else {
                $httpBody = $signed_challenge;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation codeFlowToken
     *
     * @param  string $client_id client_id (required)
     * @param  string $grant_type grant_type (required)
     * @param  string|null $code code (optional)
     * @param  string|null $redirect_uri redirect_uri (optional)
     * @param  string|null $code_verifier code_verifier (optional)
     * @param  string|null $refresh_token refresh_token (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['codeFlowToken'] to see the possible values for this operation
     *
     * @throws \IsceiSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return string
     */
    public function codeFlowToken($client_id, $grant_type, $code = null, $redirect_uri = null, $code_verifier = null, $refresh_token = null, string $contentType = self::contentTypes['codeFlowToken'][0])
    {
        list($response) = $this->codeFlowTokenWithHttpInfo($client_id, $grant_type, $code, $redirect_uri, $code_verifier, $refresh_token, $contentType);
        return $response;
    }

    /**
     * Operation codeFlowTokenWithHttpInfo
     *
     * @param  string $client_id (required)
     * @param  string $grant_type (required)
     * @param  string|null $code (optional)
     * @param  string|null $redirect_uri (optional)
     * @param  string|null $code_verifier (optional)
     * @param  string|null $refresh_token (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['codeFlowToken'] to see the possible values for this operation
     *
     * @throws \IsceiSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function codeFlowTokenWithHttpInfo($client_id, $grant_type, $code = null, $redirect_uri = null, $code_verifier = null, $refresh_token = null, string $contentType = self::contentTypes['codeFlowToken'][0])
    {
        $request = $this->codeFlowTokenRequest($client_id, $grant_type, $code, $redirect_uri, $code_verifier, $refresh_token, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'string',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'string',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation codeFlowTokenAsync
     *
     * @param  string $client_id (required)
     * @param  string $grant_type (required)
     * @param  string|null $code (optional)
     * @param  string|null $redirect_uri (optional)
     * @param  string|null $code_verifier (optional)
     * @param  string|null $refresh_token (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['codeFlowToken'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function codeFlowTokenAsync($client_id, $grant_type, $code = null, $redirect_uri = null, $code_verifier = null, $refresh_token = null, string $contentType = self::contentTypes['codeFlowToken'][0])
    {
        return $this->codeFlowTokenAsyncWithHttpInfo($client_id, $grant_type, $code, $redirect_uri, $code_verifier, $refresh_token, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation codeFlowTokenAsyncWithHttpInfo
     *
     * @param  string $client_id (required)
     * @param  string $grant_type (required)
     * @param  string|null $code (optional)
     * @param  string|null $redirect_uri (optional)
     * @param  string|null $code_verifier (optional)
     * @param  string|null $refresh_token (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['codeFlowToken'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function codeFlowTokenAsyncWithHttpInfo($client_id, $grant_type, $code = null, $redirect_uri = null, $code_verifier = null, $refresh_token = null, string $contentType = self::contentTypes['codeFlowToken'][0])
    {
        $returnType = 'string';
        $request = $this->codeFlowTokenRequest($client_id, $grant_type, $code, $redirect_uri, $code_verifier, $refresh_token, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'codeFlowToken'
     *
     * @param  string $client_id (required)
     * @param  string $grant_type (required)
     * @param  string|null $code (optional)
     * @param  string|null $redirect_uri (optional)
     * @param  string|null $code_verifier (optional)
     * @param  string|null $refresh_token (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['codeFlowToken'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function codeFlowTokenRequest($client_id, $grant_type, $code = null, $redirect_uri = null, $code_verifier = null, $refresh_token = null, string $contentType = self::contentTypes['codeFlowToken'][0])
    {

        // verify the required parameter 'client_id' is set
        if ($client_id === null || (is_array($client_id) && count($client_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $client_id when calling codeFlowToken'
            );
        }

        // verify the required parameter 'grant_type' is set
        if ($grant_type === null || (is_array($grant_type) && count($grant_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $grant_type when calling codeFlowToken'
            );
        }






        $resourcePath = '/api/v1/code-flow/token';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $client_id,
            'client_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $grant_type,
            'grant_type', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $code,
            'code', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $redirect_uri,
            'redirect_uri', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $code_verifier,
            'code_verifier', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $refresh_token,
            'refresh_token', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
